Repository brainstormforce/astra, pull requests merged in 2019-11, with the labels that each got.

#1494 docs: Screenshot update
  README.md
  readme.txt
  screenshot.jpg
  style.css
Labels: ready to merge

#1478 fix: Customizer WP 5.3 compatibility
  assets/css/minified/customizer-controls.min-rtl.css
  assets/css/minified/customizer-controls.min.css
  assets/css/unminified/customizer-controls-rtl.css
  assets/css/unminified/customizer-controls.css
  inc/assets/css/astra-notices-rtl.css
  inc/assets/css/astra-notices.css
  inc/core/class-astra-admin-settings.php
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/background-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/background.css
  inc/customizer/custom-controls/assets/css/unminified/color-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/color.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/assets/css/unminified/customizer-style-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/customizer-style.css
  inc/customizer/custom-controls/assets/css/unminified/responsive-color-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/responsive-color.css
  inc/customizer/custom-controls/assets/css/unminified/settings-group-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/settings-group.css
  inc/customizer/custom-controls/background/background.scss
  inc/customizer/custom-controls/color/color.scss
  inc/customizer/custom-controls/customizer-style.scss
  inc/customizer/custom-controls/responsive-color/responsive-color.scss
  inc/customizer/custom-controls/settings-group/settings-group.scss
  inc/metabox/class-astra-meta-boxes.php
Labels: ready to merge

#1496 Full width stretched fixes in WordPress editor
  inc/core/class-gutenberg-editor-css.php
Labels: ready to merge

#1500 fix: Added filter that returns true while acessing request_filesystem_cred…
  inc/class-astra-filesystem.php
Labels: ready to merge

#1454 fix: Replace tags with classes for menu selectors 2
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  assets/css/unminified/style-rtl.css
  assets/css/unminified/style.css
  assets/js/minified/customizer-preview.min.js
  assets/js/unminified/customizer-preview.js
  inc/addons/transparent-header/assets/js/minified/customizer-preview.min.js
  inc/addons/transparent-header/assets/js/unminified/customizer-preview.js
  inc/addons/transparent-header/classes/dynamic-css/dynamic.css.php
  inc/addons/transparent-header/classes/dynamic-css/header-sections-dynamic.css.php
  inc/assets/css/block-editor-styles-rtl.css
  inc/assets/css/block-editor-styles.css
  inc/class-astra-dynamic-css.php
  inc/compatibility/class-astra-amp.php
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  sass/site/footer/_footer-sml-layout-2.scss
  sass/site/header/_header-main.scss
  sass/site/navigation/_primary-menu.scss
Labels: ready to merge

#1501 revert: post format not standard changes
  inc/extras.php
Labels: ready to merge

#1493 docs: replaced starter sites doc link
  inc/core/class-astra-admin-settings.php
Labels: ready to merge

#1502 style: Removed transition property from primary header to fix menu jump issue
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  assets/css/unminified/style-rtl.css
  assets/css/unminified/style.css
  inc/assets/css/block-editor-styles-rtl.css
  inc/assets/css/block-editor-styles.css
  sass/site/header/_header-common.scss
Labels: needs-review

#1240 refactor: batch processing
  functions.php
  inc/lib/batch-processing/class-wp-async-request.php
  inc/lib/batch-processing/class-wp-background-process.php
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-theme-background-updater.php
  inc/theme-update/class-astra-theme-update.php
  inc/theme-update/class-wp-background-process-astra-theme.php
  phpcs.xml.dist
Labels: needs-review

#1451 fix: Menu open below header not working fix
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  assets/css/unminified/style-rtl.css
  assets/css/unminified/style.css
  inc/class-astra-dynamic-css.php
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-theme-background-updater.php
  sass/site/header/_header-layouts.scss
  style.css
Labels: needs-review, ready to merge

#1445 fix: Header merge case with last menu item
  inc/extras.php
Labels: ready to merge

#1505 chore: Changelog update
  changelog.txt
Labels: needs-review

#1455 feat: Added schema markup class to disable schema using filters
  functions.php
  inc/addons/breadcrumbs/class-astra-breadcrumb-trail.php
  inc/addons/breadcrumbs/class-astra-breadcrumbs-markup.php
  inc/blog/blog-config.php
  inc/blog/blog.php
  inc/extras.php
  inc/schema/class-astra-breadcrumb-schema.php
  inc/schema/class-astra-creativework-schema.php
  inc/schema/class-astra-organization-schema.php
  inc/schema/class-astra-person-schema.php
  inc/schema/class-astra-schema.php
  inc/schema/class-astra-site-navigation-schema.php
  inc/schema/class-astra-wpfooter-schema.php
  inc/schema/class-astra-wpheader-schema.php
  inc/schema/class-astra-wpsidebar-schema.php
  sidebar.php
  template-parts/blog/blog-layout.php
  template-parts/content-blog.php
  template-parts/content-page.php
  template-parts/content-single.php
  template-parts/content.php
  template-parts/single/single-layout.php
Labels: needs-review

#1507 chore: Updated changelog
  changelog.txt
Labels: needs-review

#1508 fix: Astra welcome notice btn height fix.
  inc/assets/css/astra-notices-rtl.css
  inc/assets/css/astra-notices.css
Labels: ready to merge

#1503 fix: border issue with img tag in anchor tag
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  assets/css/unminified/style-rtl.css
  assets/css/unminified/style.css
  inc/assets/css/block-editor-styles-rtl.css
  inc/assets/css/block-editor-styles.css
  sass/site/navigation/_primary-menu.scss
Labels: needs-review

#1511 fix: Open below header adding extra padding 10px to the website.
  inc/class-astra-dynamic-css.php
  inc/theme-update/astra-update-functions.php
Labels: ready to merge

#1512 fix: color rtl opacity position fix
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/color-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/color.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/color/color.scss
Labels: needs-review

#1513 Next release
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/color-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/color.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/color/color.scss
Labels: ready to merge

#1510 fix: removed inherit css value in astra_get_css_value function when type i…
  inc/core/common-functions.php
Labels: needs-review

#1515 Version 2.1.3
  assets/fonts/google-fonts.json
  changelog.txt
  inc/assets/css/astra-notices-rtl.css
  inc/assets/css/astra-notices.css
  inc/class-astra-dynamic-css.php
  inc/core/common-functions.php
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/color-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/color.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/color/color.scss
  inc/lib/batch-processing/class-wp-background-process.php
  inc/theme-update/astra-update-functions.php
  languages/astra.pot
Labels: ready to merge

#1516 fix: removed role attribute from header and footer tags
  inc/extras.php
Labels: ready to merge

#1523 Added author instead of author-name in creative work schema
  inc/extras.php
  inc/schema/class-astra-creativework-schema.php
  inc/schema/class-astra-person-schema.php
Labels: needs-review

#1529 fix: Spacing issue fix in weight and text transform field in typography
  assets/css/minified/customizer-controls.min-rtl.css
  assets/css/minified/customizer-controls.min.css
  assets/css/unminified/customizer-controls-rtl.css
  assets/css/unminified/customizer-controls.css
  inc/addons/heading-colors/assets/js/minified/customizer-preview.min.js
Labels: needs-review

#1531 fix: Search button accessibility issue.
  inc/core/common-functions.php
Labels: ready to merge

#1522 fix: Brizy elements not editable when transparent header enabled.
  inc/addons/transparent-header/classes/dynamic-css/dynamic.css.php
  inc/theme-update/class-astra-theme-update.php
Labels: needs-review

#1518 fix: date changed to gmdate due to PHPCS.
  inc/theme-update/class-astra-theme-update.php
Labels: ready to merge
