Repository brainstormforce/astra, pull requests merged in 2019-09, with the labels that each got.

#1426 fix: No post naviagtion padding issue with comment and main content.
  assets/css/minified/skin-1.min-rtl.css
  assets/css/minified/skin-1.min.css
  assets/css/minified/style-modern.min.css
  assets/css/unminified/skin-1-rtl.css
  assets/css/unminified/skin-1.css
  assets/css/unminified/style-modern.css
  sass/site/layout/_layout-skin-1.scss
Labels: new-theme-design

#1421 fix: Transparent Header menu background color not working.
  inc/addons/transparent-header/classes/dynamic-css/dynamic.css.php
Labels: needs-review

#1438 Fix: don't set Astra_Cache in admin
  inc/cache/class-astra-cache-base.php
Labels: needs-review, ready to merge

#1440 chore: Add inverted commas to the label in the GitHub action
  .github/workflows/label_approved_pr.yml
Labels: ready to merge

#1447 refactor: css file generation
  composer.lock
  functions.php
  inc/assets/js/astra-admin-menu-settings.js
  inc/cache/class-astra-cache-base.php
  inc/cache/class-astra-cache.php
  inc/core/class-astra-admin-settings.php
  inc/core/class-astra-enqueue-scripts.php
Labels: needs-review, ready to merge

#1458 Style: dependency fix
  inc/core/class-astra-enqueue-scripts.php
Labels: needs-review, ready to merge

#1449 fix: .hidden class renamed to .ast-hidden
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  assets/css/unminified/style-rtl.css
  assets/css/unminified/style.css
  inc/class-astra-dynamic-css.php
  inc/theme-update/class-astra-theme-update.php
  sass/site/layout/_layout.scss
Labels: needs-review, ready to merge
