Repository brainstormforce/astra, pull requests merged in 2019-08, with the labels that each got.

#1389 Displaying notice for minimum version for Astra Pro addon
  functions.php
  inc/core/class-astra-admin-settings.php
  inc/lib/notices/class-astra-notices.php
Labels: needs-review

#1391 Update google fonts
  assets/fonts/google-fonts.json
Labels: needs-review

#1393 Updated changelog for rtl fixes
  changelog.txt
Labels: needs-review

#1394 Remove group js functions
  assets/js/minified/customizer-preview.min.js
  assets/js/unminified/customizer-preview.js
  inc/core/common-functions.php
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
Labels: needs-review

#1395 udpate translations
  languages/astra.pot
Labels: needs-review

#1382 fix: Introducing getter for Theme Options Page Slug.
  inc/core/class-astra-admin-settings.php
Labels: needs-review

#1402 fix: Omit printing skip-focus-fix script on AMP content
  inc/core/class-astra-enqueue-scripts.php
Labels: needs-review

#1403 chore: Add action to delete branches after a PR is merged
  .github/workflows/delete-merged-branches.workflow
Labels: needs-review

#1404 fix: rename function astra_is_emp_endpoint to astra_is_amp_endpoint
  inc/compatibility/class-astra-amp.php
  inc/core/class-astra-enqueue-scripts.php
  inc/core/common-functions.php
  inc/core/deprecated/deprecated-functions.php
  inc/extras.php
Labels: needs-review

#1409 refactor: Add a filter for astra pro URL
  inc/core/common-functions.php
Labels: needs-review

#1186 Fix: Default button styling support for Gutenberg button using class 'ast-gtn-btn'
  inc/class-astra-dynamic-css.php
Labels: needs-review

#1406 refactor: use astra_attr to build markup where schema tags are added.
  inc/extras.php
  sidebar.php
Labels: needs-review

#1415 revert: gutenberg button style support
  inc/class-astra-dynamic-css.php
Labels: needs-review

#1407 style: Redesign admin notice for Astra Starter Sites plugin.
  inc/assets/css/astra-notices-rtl.css
  inc/assets/css/astra-notices.css
  inc/assets/images/astra-logo.svg
  inc/core/class-astra-admin-settings.php
Labels: ready to merge

#1418 fixed menu css issue with ios version lower then 11
  inc/class-astra-dynamic-css.php
Labels: needs-review

#1419 Added filter for social snap upgrade affiliate link
  .gitignore
  inc/extras.php
Labels: needs-review

#1380 fix: Paragraph margin CSS option not working for single post / Page fix.
  inc/class-astra-dynamic-css.php
Labels: new-theme-design

#1410 fix: Comment count top and bottom spacing added.
  assets/css/minified/skin-1.min-rtl.css
  assets/css/minified/skin-1.min.css
  assets/css/minified/style-modern.min-rtl.css
  assets/css/minified/style-modern.min.css
  assets/css/unminified/skin-1-rtl.css
  assets/css/unminified/skin-1.css
  assets/css/unminified/style-modern-rtl.css
  assets/css/unminified/style-modern.css
  sass/site/blog/single-post-layouts/_comment-form-skin-1.scss
Labels: new-theme-design

#1400 fix: WooCommerce new skin spacing changes with backward compatibility.
  Gruntfile.js
  assets/css/minified/compatibility/woocommerce/woocommerce-style-1.min.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-style-1-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-style-1.css
  inc/class-astra-skins.php
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  sass/site/compatibility/woocommerce/woocommerce-style-1.scss
Labels: new-theme-design

#1376 Fix: Search form stack no gap fix
  assets/css/minified/skin-1.min-rtl.css
  assets/css/minified/skin-1.min.css
  assets/css/minified/style-modern.min-rtl.css
  assets/css/minified/style-modern.min.css
  assets/css/unminified/skin-1-rtl.css
  assets/css/unminified/skin-1.css
  assets/css/unminified/style-modern-rtl.css
  assets/css/unminified/style-modern.css
  sass/site/layout/_layout-skin-1.scss
Labels: new-theme-design

#1371 Fix: Full width archive margin bottom
  assets/css/minified/skin-1.min-rtl.css
  assets/css/minified/skin-1.min.css
  assets/css/minified/style-modern.min-rtl.css
  assets/css/minified/style-modern.min.css
  assets/css/unminified/skin-1-rtl.css
  assets/css/unminified/skin-1.css
  assets/css/unminified/style-modern-rtl.css
  assets/css/unminified/style-modern.css
  sass/site/layout/_layout-skin-1.scss
Labels: new-theme-design

#1381 fix: ast-pagination wrapper div appearing on all archive pages ev…
  inc/extras.php
Labels: new-theme-design

#1420 fix: Check if ClassList exists before using it
  assets/js/minified/navigation.min.js
  assets/js/minified/style.min.js
  assets/js/unminified/navigation.js
  assets/js/unminified/style.js
Labels: needs-review

#1425 fix: Customizer Scrollbar not scroll-able with mouse click and drag.
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/assets/css/unminified/customizer-style-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/customizer-style.css
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/custom-controls/customizer-style.scss
  inc/customizer/custom-controls/settings-group/settings-group.js
Labels: needs-review

#1424 fix: search icon not working for android/tablet devices
  assets/js/minified/navigation.min.js
  assets/js/minified/style.min.js
  assets/js/unminified/navigation.js
  assets/js/unminified/style.js
  package-lock.json
  package.json
Labels: needs-review

#1428 fix: Load CSS JS on the basis of filter to disable enqueueing of assets.
  inc/cache/class-astra-cache.php
  inc/core/class-astra-enqueue-scripts.php
Labels: needs-review

#1411 refactor: CSS file generation for Astra Dynamic CSS
  functions.php
  inc/addons/breadcrumbs/dynamic-css/dynamic.css.php
  inc/addons/transparent-header/classes/dynamic-css/dynamic.css.php
  inc/addons/transparent-header/classes/dynamic-css/header-sections-dynamic.css.php
  inc/assets/js/astra-admin-menu-settings.js
  inc/cache/class-astra-cache-base.php
  inc/cache/class-astra-cache.php
  inc/class-astra-dynamic-css.php
  inc/class-astra-filesystem.php
  inc/compatibility/learndash/class-astra-learndash.php
  inc/core/class-astra-admin-settings.php
  inc/core/class-astra-enqueue-scripts.php
  inc/core/common-functions.php
  inc/customizer/class-astra-font-families.php
  inc/extras.php
Labels: needs-review

#1427 Disable comment time
  inc/blog/single-blog.php
Labels: needs-review

#1431 new: Version 2.1.0
  .gitignore
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  assets/css/unminified/style-rtl.css
  assets/css/unminified/style.css
  assets/fonts/google-fonts.json
  assets/js/minified/navigation.min.js
  assets/js/minified/style.min.js
  assets/js/unminified/navigation.js
  assets/js/unminified/style.js
  changelog.txt
  composer.lock
  functions.php
  inc/addons/breadcrumbs/dynamic-css/dynamic.css.php
  inc/addons/transparent-header/classes/dynamic-css/dynamic.css.php
  inc/addons/transparent-header/classes/dynamic-css/header-sections-dynamic.css.php
  inc/assets/css/astra-notices-rtl.css
  inc/assets/css/astra-notices.css
  inc/assets/css/block-editor-styles-rtl.css
  inc/assets/css/block-editor-styles.css
  inc/assets/images/astra-logo.svg
  inc/assets/js/astra-admin-menu-settings.js
  inc/blog/single-blog.php
  inc/cache/class-astra-cache-base.php
  inc/cache/class-astra-cache.php
  inc/class-astra-after-setup-theme.php
  inc/class-astra-dynamic-css.php
  inc/class-astra-filesystem.php
  inc/class-astra-mobile-header.php
  inc/compatibility/learndash/class-astra-learndash.php
  inc/core/class-astra-admin-settings.php
  inc/core/class-astra-enqueue-scripts.php
  inc/core/common-functions.php
  inc/customizer/class-astra-font-families.php
  inc/customizer/configurations/layout/class-astra-header-layout-configs.php
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/assets/css/unminified/customizer-style-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/customizer-style.css
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/custom-controls/customizer-style.scss
  inc/customizer/custom-controls/settings-group/settings-group.js
  inc/extras.php
  languages/astra.pot
  package.json
  sass/admin/block-editor-styles.scss
  sass/site/header/_header-main.scss
  sidebar.php
  style.css
Labels: needs-review

#1434 fix: dynamic css filter should always return values
  inc/addons/transparent-header/classes/dynamic-css/dynamic.css.php
  inc/compatibility/learndash/class-astra-learndash.php
  inc/extras.php
Labels: needs-review
