Repository brainstormforce/astra, pull requests merged in 2019-10, with the labels that each got.

#1469 removed unwanted schema meta of comment from creative work schema
  inc/blog/blog-config.php
Labels: needs-review, ready to merge

#1442 fix: Upload Theme button not working.
  inc/core/class-astra-admin-settings.php
Labels: needs-review, ready to merge

#1383 fix: added inline edd dynamic css to file
  inc/compatibility/edd/class-astra-edd.php
Labels: ready to merge

#1471 feat: Filter to disable Breadcrumb Schema.
  inc/addons/breadcrumbs/class-astra-breadcrumb-trail.php
  inc/addons/breadcrumbs/class-astra-breadcrumbs-markup.php
  inc/schema/class-astra-breadcrumb-schema.php
  inc/schema/class-astra-schema.php
Labels: ready to merge

#1473 Fix: markup issue for header and footer
  changelog.txt
  functions.php
  inc/extras.php
  package.json
  sidebar.php
  style.css
  template-parts/content-blog.php
  template-parts/content-page.php
  template-parts/content-single.php
  template-parts/content.php
Labels: needs-review, ready to merge

#1466 added style and script html5 theme support
  inc/class-astra-after-setup-theme.php
Labels: ready to merge

#1462 feat: Custom layouts should be hidden from sitemap
  functions.php
  inc/compatibility/class-astra-yoast-seo.php
Labels: needs-review

#1467 fix: Gutenberg - Add correct admin styles for fullwidth stretch layout.
  inc/core/class-gutenberg-editor-css.php
Labels: needs-review

#1448 Fix: Replace tags with classes for menu selectors
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  assets/css/unminified/style-rtl.css
  assets/css/unminified/style.css
  assets/js/minified/customizer-preview.min.js
  assets/js/minified/navigation.min.js
  assets/js/minified/style.min.js
  assets/js/unminified/customizer-preview.js
  assets/js/unminified/navigation.js
  assets/js/unminified/style.js
  inc/addons/transparent-header/assets/js/minified/customizer-preview.min.js
  inc/addons/transparent-header/assets/js/unminified/customizer-preview.js
  inc/addons/transparent-header/classes/dynamic-css/dynamic.css.php
  inc/class-astra-dynamic-css.php
  inc/compatibility/class-astra-amp.php
  inc/extras.php
  sass/site/header/_header-layouts.scss
  sass/site/header/_header-main.scss
  sass/site/navigation/_primary-menu.scss
Labels: ready to merge

#1475 fix: transparent header css not working
  inc/addons/transparent-header/classes/dynamic-css/dynamic.css.php
  inc/addons/transparent-header/classes/dynamic-css/header-sections-dynamic.css.php
Labels: ready to merge

#1443 fix: WooCommerce gb product grid blocks compatibility.
  assets/css/minified/compatibility/woocommerce/woocommerce.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce.css
  inc/assets/css/block-editor-styles-rtl.css
  inc/assets/css/block-editor-styles.css
  inc/class-astra-dynamic-css.php
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  inc/core/class-gutenberg-editor-css.php
  package-lock.json
  package.json
  sass/admin/block-editor-styles.scss
  sass/site/compatibility/woocommerce/woocommerce.scss
Labels: needs-review, ready to merge

#1479 fix: Skip appending unit when value is inherit.
  composer.lock
  inc/core/common-functions.php
  package-lock.json
  package.json
Labels: ready to merge

#1460 feat: Post format compatibility with excerpt.
  .github/workflows/label_approved_pr.yml
  inc/extras.php
Labels: ready to merge

#1483 chore: Changelog modified.
  changelog.txt
Labels: ready to merge

#1485 ci: Resolved conflicts
  .gitignore
  package-lock.json
Labels: ready to merge

#1486 updated version number
  changelog.txt
  functions.php
  inc/compatibility/class-astra-yoast-seo.php
  inc/extras.php
  package.json
  style.css
Labels: needs-review

#1482 Next release
  .github/workflows/label_approved_pr.yml
  assets/css/minified/compatibility/woocommerce/woocommerce.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce.css
  assets/fonts/google-fonts.json
  changelog.txt
  functions.php
  inc/assets/css/block-editor-styles-rtl.css
  inc/assets/css/block-editor-styles.css
  inc/blog/blog-config.php
  inc/class-astra-after-setup-theme.php
  inc/class-astra-dynamic-css.php
  inc/compatibility/class-astra-yoast-seo.php
  inc/compatibility/edd/class-astra-edd.php
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  inc/core/class-astra-admin-settings.php
  inc/core/class-gutenberg-editor-css.php
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/color-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/color.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/color/color.scss
  inc/extras.php
  inc/metabox/class-astra-meta-boxes.php
  languages/astra.pot
  package-lock.json
  package.json
  sass/admin/block-editor-styles.scss
  sass/site/compatibility/woocommerce/woocommerce.scss
  style.css
Labels: ready to merge

#1488 chore: updated changelog
  changelog.txt
Labels: ready to merge

#1487 Version 2.1.2
  .github/workflows/label_approved_pr.yml
  assets/css/minified/compatibility/woocommerce/woocommerce.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce.css
  assets/fonts/google-fonts.json
  changelog.txt
  composer.lock
  functions.php
  inc/addons/transparent-header/classes/dynamic-css/dynamic.css.php
  inc/addons/transparent-header/classes/dynamic-css/header-sections-dynamic.css.php
  inc/assets/css/block-editor-styles-rtl.css
  inc/assets/css/block-editor-styles.css
  inc/blog/blog-config.php
  inc/class-astra-after-setup-theme.php
  inc/class-astra-dynamic-css.php
  inc/compatibility/class-astra-yoast-seo.php
  inc/compatibility/edd/class-astra-edd.php
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  inc/core/class-astra-admin-settings.php
  inc/core/class-gutenberg-editor-css.php
  inc/core/common-functions.php
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/color-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/color.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/color/color.scss
  inc/extras.php
  inc/metabox/class-astra-meta-boxes.php
  languages/astra.pot
  package-lock.json
  package.json
  sass/admin/block-editor-styles.scss
  sass/site/compatibility/woocommerce/woocommerce.scss
  style.css
Labels: ready to merge

#1477 Replace tags with classes for menu selectors 1
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  assets/css/unminified/style-rtl.css
  assets/css/unminified/style.css
  inc/addons/transparent-header/assets/js/minified/customizer-preview.min.js
  inc/addons/transparent-header/assets/js/unminified/customizer-preview.js
  inc/extras.php
  package-lock.json
  package.json
  sass/site/header/_header-common.scss
  sass/site/header/_header-main.scss
Labels: ready to merge

#1492 revert: Remove database migration for .hidden CSS compatibility.
  inc/class-astra-dynamic-css.php
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-theme-background-updater.php
Labels: needs-review

#1476 fix: Gutenberg WordPress 5.3 compatibility.
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  assets/css/unminified/style-rtl.css
  assets/css/unminified/style.css
  inc/assets/css/block-editor-styles-rtl.css
  inc/assets/css/block-editor-styles.css
  inc/core/class-gutenberg-editor-css.php
  package-lock.json
  package.json
  sass/admin/block-editor-styles.scss
  sass/site/primary/_gutenberg.scss
Labels: ready to merge

#1490 Blog template
  inc/template-parts.php
Labels: ready to merge

#1484 fix: updated astra_responsive_spacing function with new parameter
  inc/core/common-functions.php
Labels: ready to merge

#1498 chore: updated copyright years
  style.css
Labels: needs-review
