Repository brainstormforce/astra, pull requests merged in 2020-07, with the labels that each got.

#1768 chore: Reverted changes for Responsive support in theme for Footer & Footer Widget
  assets/js/minified/customizer-preview.min.js
  assets/js/unminified/customizer-preview.js
  inc/class-astra-dynamic-css.php
  inc/core/class-astra-theme-options.php
  inc/customizer/class-astra-customizer.php
  inc/customizer/configurations/colors-background/class-astra-advanced-footer-colors-configs.php
  inc/customizer/configurations/colors-background/class-astra-footer-colors-configs.php
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/custom-controls/background/background.js
  inc/customizer/custom-controls/background/background.scss
  inc/customizer/custom-controls/background/class-astra-control-background.php
  inc/customizer/customizer-controls.php
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-theme-background-updater.php
Labels: ready to merge

#1772 fix: Gutenberg margin issue with Full Width/Contained layout when Transparent Header is enabled.
  inc/class-astra-dynamic-css.php
  inc/customizer/configurations/layout/class-astra-site-identity-configs.php
Labels: ready to merge

#1765 fix: woo commerce selectWoo.js vulnerability fix.
  inc/customizer/custom-controls/typography/selectWoo.js
Labels: ready to merge

#1764 improvement: Divided extras.php into markup-extras.php and extras.php.
  functions.php
  inc/extras.php
  inc/markup-extras.php
Labels: ready to merge

#1758 improvement: CSS optimizations & many more for all Headers including mega menu compatibility
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  assets/css/unminified/style-rtl.css
  assets/css/unminified/style.css
  assets/js/minified/customizer-preview.min.js
  assets/js/minified/navigation.min.js
  assets/js/minified/style.min.js
  assets/js/unminified/customizer-preview.js
  assets/js/unminified/navigation.js
  assets/js/unminified/style.js
  functions.php
  inc/addons/transparent-header/assets/js/minified/customizer-preview.min.js
  inc/addons/transparent-header/assets/js/unminified/customizer-preview.js
  inc/addons/transparent-header/classes/dynamic-css/dynamic.css.php
  inc/addons/transparent-header/classes/dynamic-css/header-sections-dynamic.css.php
  inc/class-astra-dynamic-css.php
  inc/compatibility/class-astra-amp.php
  inc/compatibility/class-astra-elementor.php
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  languages/astra.pot
  package-lock.json
  sass/site/footer/_footer-sml-layout-2.scss
  sass/site/header/_header-common.scss
  sass/site/header/_header-layouts.scss
  sass/site/header/_header-main.scss
  sass/site/navigation/_primary-menu.scss
Labels: ready to merge

#1760 fix: resolved the warnings displayed in the latest update of Theme Check plugin.
  comments.php
  inc/customizer/class-astra-customizer.php
  inc/customizer/custom-controls/background/class-astra-control-background.php
  inc/customizer/custom-controls/responsive-background/class-astra-control-responsive-background.php
  style.css
Labels: ready to merge

#1784 fix: checked the button border empty color and woo gutenberg block cases.
  inc/compatibility/woocommerce/class-astra-woocommerce.php
Labels: needs-review

#1719 improvement: Change method of loading Google Fonts from JSON to PHP Array.
  Gruntfile.js
  assets/fonts/google-fonts.json
  inc/core/deprecated/deprecated-filters.php
  inc/customizer/class-astra-font-families.php
  inc/google-fonts.php
  package-lock.json
  package.json
Labels: ready to merge

#1781 fix: Updations in Astra headers PR as per Support & QA points
  inc/class-astra-dynamic-css.php
  inc/markup-extras.php
Labels: needs-review

#1788 fix: global button comp to woo commerce button.
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-theme-background-updater.php
Labels: ready to merge

#1780 improvement: CSS optimizations & Header related all changes including mega menu compatibility
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  assets/css/unminified/style-rtl.css
  assets/css/unminified/style.css
  assets/js/minified/customizer-preview.min.js
  assets/js/minified/navigation.min.js
  assets/js/minified/style.min.js
  assets/js/unminified/customizer-preview.js
  assets/js/unminified/navigation.js
  assets/js/unminified/style.js
  functions.php
  inc/addons/transparent-header/assets/js/minified/customizer-preview.min.js
  inc/addons/transparent-header/assets/js/unminified/customizer-preview.js
  inc/addons/transparent-header/classes/dynamic-css/dynamic.css.php
  inc/addons/transparent-header/classes/dynamic-css/header-sections-dynamic.css.php
  inc/class-astra-dynamic-css.php
  inc/compatibility/class-astra-amp.php
  inc/compatibility/class-astra-elementor.php
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  inc/customizer/configurations/colors-background/class-astra-footer-colors-configs.php
  inc/markup-extras.php
  languages/astra.pot
  package-lock.json
  sass/site/footer/_footer-sml-layout-2.scss
  sass/site/header/_header-common.scss
  sass/site/header/_header-layouts.scss
  sass/site/header/_header-main.scss
  sass/site/navigation/_primary-menu.scss
Labels: needs-review

#1805 Theme trac listed fixes
  assets/css/minified/editor-style.min-rtl.css
  assets/css/minified/editor-style.min.css
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  assets/css/unminified/editor-style-rtl.css
  assets/css/unminified/editor-style.css
  assets/css/unminified/style-rtl.css
  assets/css/unminified/style.css
  assets/js/minified/navigation.min.js
  assets/js/minified/style.min.js
  assets/js/unminified/navigation.js
  assets/js/unminified/style.js
  inc/assets/css/block-editor-styles-rtl.css
  inc/assets/css/block-editor-styles.css
  sass/modules/_accessibility.scss
  sass/site/forms/_common.scss
  sass/site/header/_header-main.scss
  sass/site/navigation/_navigation.scss
  sass/site/secondary/_widgets.scss
  sass/site/site-normalize/site-normalize.scss
Labels: ready to merge

#1790 fix: added the global styling for the woocommerce gutenberg editor buttons.
  inc/core/class-gutenberg-editor-css.php
Labels: ready to merge

#1801 fix: Last button menu item misaligned in headers update
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  assets/css/unminified/style-rtl.css
  assets/css/unminified/style.css
  sass/site/navigation/_primary-menu.scss
Labels: ready to merge

#1789 chore: v2.5.0 update.
  README.md
  admin/bsf-analytics/Gruntfile.js
  admin/bsf-analytics/assets/css/minified/style-rtl.min.css
  admin/bsf-analytics/class-bsf-analytics-stats.php
  admin/bsf-analytics/class-bsf-analytics.php
  assets/fonts/google-fonts.json
  changelog.txt
  inc/class-astra-dynamic-css.php
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  inc/customizer/class-astra-font-families.php
  inc/google-fonts.php
  inc/markup-extras.php
  inc/theme-update/astra-update-functions.php
  languages/astra.pot
  package.json
  readme.txt
Labels: ready to merge

#1807 chore: WPForms upgrade affiliate link
  inc/extras.php
Labels: ready to merge

#1809 chore: v2.5.0 release
  assets/fonts/google-fonts.json
  changelog.txt
  inc/google-fonts.php
  languages/astra.pot
Labels: ready to merge

#1813 fix: added is_callable check for astra_woocommerce class.
  inc/core/class-gutenberg-editor-css.php
Labels: ready to merge

#1798 feat: Responsive Spacing Control PHP to ReactJS.
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/custom-controls/responsive-spacing/class-astra-control-responsive-spacing.php
  inc/customizer/custom-controls/responsive-spacing/responsive-spacing.js
  inc/customizer/react/build/index.asset.php
  inc/customizer/react/build/index.js
  inc/customizer/react/src/index.js
  inc/customizer/react/src/responsive-spacing/control.js
  inc/customizer/react/src/responsive-spacing/responsive-spacing-component.js
Labels: has patch

#1814 chore: Merge next-release - dev.
  assets/fonts/google-fonts.json
  inc/core/class-gutenberg-editor-css.php
  inc/google-fonts.php
  languages/astra.pot
Labels: needs-review

#1818 chore: Merge dev and master v2.5.0.
  assets/fonts/google-fonts.json
  inc/core/class-gutenberg-editor-css.php
  inc/google-fonts.php
  languages/astra.pot
Labels: needs-review

#1797 feat: Responsive Slider Control PHP to ReactJS.
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/custom-controls/responsive-slider/class-astra-control-responsive-slider.php
  inc/customizer/custom-controls/responsive-slider/responsive-slider.js
  inc/customizer/react/build/index.asset.php
  inc/customizer/react/build/index.js
  inc/customizer/react/src/index.js
  inc/customizer/react/src/responsive-slider/control.js
  inc/customizer/react/src/responsive-slider/responsive-slider-component.js
Labels: react-controls

#1822 fix: Third party menu plugins compatibility added with nav_menu_link_attributes
  assets/js/minified/navigation.min.js
  assets/js/minified/style.min.js
  assets/js/unminified/navigation.js
  assets/js/unminified/style.js
  inc/markup-extras.php
Labels: ready to merge

#1823 chore: v2.5.1 release.
  README.md
  assets/fonts/google-fonts.json
  changelog.txt
  functions.php
  inc/google-fonts.php
  languages/astra.pot
  package.json
  readme.txt
  style.css
Labels: ready to merge

#1824 chore: Merge next-release & dev v2.5.1
  README.md
  assets/fonts/google-fonts.json
  assets/js/minified/navigation.min.js
  assets/js/minified/style.min.js
  assets/js/unminified/navigation.js
  assets/js/unminified/style.js
  changelog.txt
  functions.php
  inc/google-fonts.php
  inc/markup-extras.php
  languages/astra.pot
  package.json
  readme.txt
  style.css
Labels: ready to merge

#1825 chore: v2.5.1 dev and master.
  README.md
  assets/fonts/google-fonts.json
  assets/js/minified/navigation.min.js
  assets/js/minified/style.min.js
  assets/js/unminified/navigation.js
  assets/js/unminified/style.js
  changelog.txt
  functions.php
  inc/google-fonts.php
  inc/markup-extras.php
  languages/astra.pot
  package.json
  readme.txt
  style.css
Labels: ready to merge
