Repository brainstormforce/astra, pull requests merged in 2020-12, with the labels that each got.

#2046 refactor: astra_css changed with astra_generate_font_weight_css for font-weights in customizer preview
  assets/css/minified/frontend.min.css
  assets/css/unminified/frontend-rtl.css
  assets/css/unminified/frontend.css
  assets/js/minified/customizer-preview.min.js
  assets/js/unminified/customizer-preview.js
  inc/addons/breadcrumbs/assets/js/minified/customizer-preview.min.js
  inc/addons/breadcrumbs/assets/js/unminified/customizer-preview.js
  inc/addons/heading-colors/assets/js/minified/customizer-preview.min.js
  inc/addons/heading-colors/assets/js/unminified/customizer-preview.js
  inc/assets/js/customizer-preview.js
  inc/builder/type/base/assets/js/customizer-preview.js
  inc/builder/type/header/menu/assets/js/customizer-preview.js
Labels: ready to merge

#2043 perf: Remove Smiley CSS to improve frontend.
  assets/css/minified/editor-style.min-rtl.css
  assets/css/minified/editor-style.min.css
  assets/css/minified/frontend.min.css
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  assets/css/unminified/editor-style-rtl.css
  assets/css/unminified/editor-style.css
  assets/css/unminified/frontend-rtl.css
  assets/css/unminified/frontend.css
  assets/css/unminified/style-rtl.css
  assets/css/unminified/style.css
  sass/media/_media.scss
Labels: needs-review

#2047 fix: Multiple menu animation CSS case.
  inc/core/class-astra-enqueue-scripts.php
Labels: ready to merge

#2032 fix: Site Identity and Menu elements style issues
  assets/css/minified/frontend.min.css
  assets/css/unminified/frontend-rtl.css
  assets/css/unminified/frontend.css
  inc/builder/type/header/menu/assets/js/customizer-preview.js
  inc/builder/type/header/menu/dynamic-css/dynamic.css.php
  inc/builder/type/header/site-identity/assets/js/customizer-preview.js
  sass/site/header/_header-builder-main.scss
Labels: ready to merge

#2027 fix: Site Icon media logo control position changed in HFB
  inc/customizer/configurations/builder/header/class-astra-customizer-site-identity-configs.php
  inc/customizer/configurations/layout/class-astra-site-identity-configs.php
  inc/customizer/override-defaults.php
Labels: ready to merge

#2060 fix: Merge Context new Logic.
  assets/js/minified/customizer-dependency.min.js
  assets/js/unminified/customizer-dependency.js
  inc/addons/breadcrumbs/customizer/class-astra-breadcrumbs-color-configs.php
  inc/addons/breadcrumbs/customizer/class-astra-breadcrumbs-configs.php
  inc/addons/breadcrumbs/customizer/class-astra-breadcrumbs-typo-configs.php
  inc/addons/transparent-header/classes/sections/class-astra-customizer-transparent-header-configs.php
  inc/compatibility/edd/customizer/sections/layout/class-astra-edd-archive-layout-configs.php
  inc/compatibility/lifterlms/class-astra-lifterlms.php
  inc/compatibility/woocommerce/customizer/sections/layout/class-astra-woo-shop-layout-configs.php
  inc/compatibility/woocommerce/customizer/sections/layout/class-astra-woo-shop-single-layout-configs.php
  inc/core/builder/class-astra-builder-helper.php
  inc/customizer/class-astra-builder-customizer.php
  inc/customizer/class-astra-customizer.php
  inc/customizer/configurations/builder/base/class-astra-divider-component-configs.php
  inc/customizer/configurations/builder/base/class-astra-social-icon-component-configs.php
  inc/customizer/configurations/builder/class-astra-builder-base-configuration.php
  inc/customizer/configurations/builder/footer/class-astra-customizer-above-footer-configs.php
  inc/customizer/configurations/builder/footer/class-astra-customizer-below-footer-configs.php
  inc/customizer/configurations/builder/footer/class-astra-customizer-footer-menu-configs.php
  inc/customizer/configurations/builder/footer/class-astra-customizer-primary-footer-configs.php
  inc/customizer/configurations/builder/header/class-astra-customizer-above-header-configs.php
  inc/customizer/configurations/builder/header/class-astra-customizer-below-header-configs.php
  inc/customizer/configurations/builder/header/class-astra-customizer-mobile-trigger-configs.php
  inc/customizer/configurations/builder/header/class-astra-customizer-off-canvas-configs.php
  inc/customizer/configurations/builder/header/class-astra-customizer-primary-header-configs.php
  inc/customizer/configurations/builder/header/class-astra-customizer-site-identity-configs.php
  inc/customizer/configurations/builder/header/class-astra-header-menu-component-configs.php
  inc/customizer/configurations/buttons/class-astra-customizer-button-configs.php
  inc/customizer/configurations/buttons/class-astra-existing-button-configs.php
  inc/customizer/configurations/colors-background/class-astra-advanced-footer-colors-configs.php
  inc/customizer/configurations/layout/class-astra-blog-layout-configs.php
  inc/customizer/configurations/layout/class-astra-blog-single-layout-configs.php
  inc/customizer/configurations/layout/class-astra-footer-layout-configs.php
  inc/customizer/configurations/layout/class-astra-header-layout-configs.php
  inc/customizer/configurations/layout/class-astra-site-identity-configs.php
  inc/customizer/configurations/layout/class-astra-site-layout-configs.php
  inc/customizer/configurations/typography/class-astra-archive-typo-configs.php
  inc/customizer/configurations/typography/class-astra-single-typo-configs.php
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
  inc/customizer/extend-custom-controls/src/ast-font-family/control.js
  inc/customizer/extend-custom-controls/src/control-customizer.js
  inc/customizer/extend-custom-controls/src/customizer.js
  inc/customizer/extend-custom-controls/src/html-editor/editor-component.js
  inc/customizer/extend-custom-controls/src/responsive-spacing/responsive-spacing-component.js
  inc/customizer/override-defaults.php
Labels: ready to merge

#2070 fix: Cart dropdown opens next to the header bottom line
  assets/css/minified/compatibility/edd.min-rtl.css
  assets/css/minified/compatibility/edd.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min.css
  assets/css/minified/frontend.min.css
  assets/css/unminified/compatibility/edd-rtl.css
  assets/css/unminified/compatibility/edd.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce.css
  assets/css/unminified/frontend-rtl.css
  assets/css/unminified/frontend.css
  inc/builder/type/header/above-header/dynamic-css/dynamic.css.php
  inc/builder/type/header/below-header/dynamic-css/dynamic.css.php
  inc/builder/type/header/primary-header/dynamic-css/dynamic.css.php
  inc/core/builder/class-astra-builder-options.php
  sass/site/compatibility/edd.scss
  sass/site/compatibility/woocommerce/woocommerce.scss
Labels: needs-review

#2075 fix: Transparent header bottom border cases handled for last used header row
  assets/css/minified/frontend.min.css
  assets/css/unminified/frontend-rtl.css
  assets/css/unminified/frontend.css
  inc/addons/transparent-header/assets/js/minified/customizer-preview.min.js
  inc/addons/transparent-header/assets/js/unminified/customizer-preview.js
  inc/addons/transparent-header/classes/class-astra-ext-transparent-header-loader.php
  inc/addons/transparent-header/classes/dynamic-css/dynamic.css.php
Labels: needs-review

#2039 feat: Multiple menu feature
  inc/addons/transparent-header/assets/js/minified/customizer-preview.min.js
  inc/addons/transparent-header/assets/js/unminified/customizer-preview.js
  inc/addons/transparent-header/classes/dynamic-css/dynamic.css.php
  inc/builder/type/header/menu/class-astra-header-menu-component.php
  inc/builder/type/header/menu/dynamic-css/dynamic.css.php
  inc/class-astra-mobile-header.php
  inc/core/builder/class-astra-builder-helper.php
  inc/core/class-astra-enqueue-scripts.php
  inc/markup-extras.php
Labels: ready to merge

#2079 feat: New hooks for Footer added for compatibility with HFB Footer markup.
  template-parts/footer/builder/footer-row.php
Labels: needs-review

#2051 fix: footer_content actions not working in new HFB
  inc/builder/markup/class-astra-builder-header.php
  template-parts/footer/builder/desktop-builder-layout.php
Labels: needs-review

#2054 perf: Remove unwanted/unused CSS from the frontend css files.
  assets/css/minified/frontend.min.css
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  assets/css/unminified/frontend-rtl.css
  assets/css/unminified/frontend.css
  assets/css/unminified/style-rtl.css
  assets/css/unminified/style.css
  package-lock.json
  sass/site/404/_404-common.scss
  sass/site/404/_404.scss
  sass/site/_frontend.scss
  sass/site/_site.scss
  sass/site/elements/element-email.scss
  sass/site/elements/element-search.scss
  sass/site/elements/element-social-follow.scss
  sass/site/responsive/_responsive.scss
  sass/typography/_copy.scss
  sass/typography/_typography.scss
Labels: ready to merge

#2086 fix: removed duplicate css and make it common.
  assets/css/minified/editor-style.min-rtl.css
  assets/css/minified/editor-style.min.css
  assets/css/minified/frontend.min.css
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  assets/css/unminified/editor-style-rtl.css
  assets/css/unminified/editor-style.css
  assets/css/unminified/frontend-rtl.css
  assets/css/unminified/frontend.css
  assets/css/unminified/style-rtl.css
  assets/css/unminified/style.css
  sass/grid/_grid.scss
Labels: needs-review

#2084 improvement: removed blank spaces from generated html
  footer.php
  header.php
  inc/builder/controllers/class-astra-builder-ui-controller.php
  inc/builder/markup/class-astra-builder-header.php
  inc/class-astra-loop.php
  inc/core/builder/class-astra-builder-helper.php
  index.php
  sidebar.php
  template-parts/content-blog.php
  template-parts/footer/builder/desktop-builder-layout.php
  template-parts/header/builder/desktop-builder-layout.php
  template-parts/header/builder/mobile-builder-layout.php
Labels: ready to merge

#2078 fix: Width of Gradient angle input number field restricts number selection in WP-5.6
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/color-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/color.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/assets/css/unminified/settings-group-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/settings-group.css
  inc/customizer/custom-controls/settings-group/settings-group.scss
Labels: ready to merge

#2089 fix: Possible fatal errors in PHP 8.0 with customizer partials callback
  inc/customizer/class-astra-customizer-partials.php
  inc/customizer/configurations/layout/class-astra-footer-layout-configs.php
  inc/customizer/configurations/layout/class-astra-header-layout-configs.php
  inc/customizer/configurations/layout/class-astra-site-identity-configs.php
  inc/customizer/override-defaults.php
Labels: ready to merge

#2090 imprv: Shifted cart icon static css from CSS file to php file.
  assets/css/minified/frontend.min.css
  assets/css/unminified/frontend-rtl.css
  assets/css/unminified/frontend.css
  inc/class-astra-dynamic-css.php
  sass/site/builder/_header.scss
Labels: ready to merge

#2061 perf: CSS optimization & implementation of var in Social Icons control
  assets/css/minified/frontend.min.css
  assets/css/unminified/frontend-rtl.css
  assets/css/unminified/frontend.css
  inc/builder/controllers/class-astra-builder-ui-controller.php
  inc/builder/type/base/dynamic-css/social/class-astra-social-component-dynamic-css.php
  inc/core/builder/class-astra-builder-options.php
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
  inc/customizer/extend-custom-controls/src/social-icons/item-component.js
  inc/customizer/extend-custom-controls/src/social-icons/social-component.js
Labels: ready to merge

#2101 chore: Merge v2.6.2-release and next-release
  README.md
  assets/fonts/google-fonts.json
  changelog.txt
  composer.lock
  functions.php
  inc/compatibility/lifterlms/class-astra-lifterlms.php
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/google-fonts.php
  languages/astra.pot
  package.json
  readme.txt
  style.css
Labels: ready to merge

#2102 chore: merge next-release and dev v2.6.2.
  .github/workflows/phpcs.yml
  .travis.yml
  README.md
  assets/fonts/google-fonts.json
  changelog.txt
  composer.lock
  functions.php
  inc/compatibility/lifterlms/class-astra-lifterlms.php
  inc/customizer/class-astra-customizer-partials.php
  inc/customizer/configurations/layout/class-astra-footer-layout-configs.php
  inc/customizer/configurations/layout/class-astra-header-layout-configs.php
  inc/customizer/configurations/layout/class-astra-site-identity-configs.php
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/color-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/color.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/assets/css/unminified/settings-group-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/settings-group.css
  inc/customizer/custom-controls/settings-group/settings-group.scss
  inc/customizer/extend-custom-controls/package-lock.json
  inc/customizer/override-defaults.php
  inc/google-fonts.php
  languages/astra.pot
  package-lock.json
  package.json
  readme.txt
  style.css
Labels: ready to merge

#2103 chore: Merge dev and master v2.6.2
  .github/workflows/phpcs.yml
  .travis.yml
  README.md
  assets/fonts/google-fonts.json
  changelog.txt
  composer.lock
  functions.php
  inc/compatibility/lifterlms/class-astra-lifterlms.php
  inc/customizer/class-astra-customizer-partials.php
  inc/customizer/configurations/layout/class-astra-footer-layout-configs.php
  inc/customizer/configurations/layout/class-astra-header-layout-configs.php
  inc/customizer/configurations/layout/class-astra-site-identity-configs.php
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/color-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/color.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/assets/css/unminified/settings-group-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/settings-group.css
  inc/customizer/custom-controls/settings-group/settings-group.scss
  inc/customizer/extend-custom-controls/package-lock.json
  inc/customizer/override-defaults.php
  inc/google-fonts.php
  languages/astra.pot
  package-lock.json
  package.json
  readme.txt
  style.css
Labels: ready to merge

#2030 refactor: Removed extra setting group control used for only single color control
  assets/css/minified/frontend.min.css
  assets/css/unminified/frontend-rtl.css
  assets/css/unminified/frontend.css
  inc/addons/breadcrumbs/customizer/class-astra-breadcrumbs-configs.php
  inc/addons/transparent-header/classes/sections/class-astra-customizer-colors-transparent-header-configs.php
  inc/addons/transparent-header/classes/sections/class-astra-customizer-transparent-header-configs.php
  inc/assets/css/ast-builder-customizer-rtl.css
  inc/assets/css/ast-builder-customizer.css
  inc/customizer/configurations/builder/footer/class-astra-customizer-above-footer-configs.php
  inc/customizer/configurations/builder/footer/class-astra-customizer-below-footer-configs.php
  inc/customizer/configurations/builder/footer/class-astra-customizer-primary-footer-configs.php
  inc/customizer/configurations/builder/header/class-astra-customizer-above-header-configs.php
  inc/customizer/configurations/builder/header/class-astra-customizer-below-header-configs.php
  inc/customizer/configurations/builder/header/class-astra-customizer-primary-header-configs.php
  inc/customizer/configurations/buttons/class-astra-customizer-button-configs.php
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/assets/css/unminified/responsive-color-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/responsive-color.css
  inc/customizer/custom-controls/responsive-color/responsive-color.scss
Labels: ready to merge

#2106 fix: Added missed ASTRA_THEME_SETTINGS to customizer controls
  inc/addons/transparent-header/classes/sections/class-astra-customizer-colors-transparent-header-configs.php
  inc/customizer/configurations/builder/footer/class-astra-customizer-above-footer-configs.php
  inc/customizer/configurations/builder/footer/class-astra-customizer-below-footer-configs.php
  inc/customizer/configurations/builder/footer/class-astra-customizer-primary-footer-configs.php
  inc/customizer/configurations/builder/header/class-astra-customizer-above-header-configs.php
  inc/customizer/configurations/builder/header/class-astra-customizer-below-header-configs.php
  inc/customizer/configurations/builder/header/class-astra-customizer-primary-header-configs.php
Labels: needs-review

#2034 perf: CSS load optimization
  assets/css/minified/editor-style.min-rtl.css
  assets/css/minified/editor-style.min.css
  assets/css/minified/frontend.min.css
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  assets/css/unminified/editor-style-rtl.css
  assets/css/unminified/editor-style.css
  assets/css/unminified/frontend-rtl.css
  assets/css/unminified/frontend.css
  assets/css/unminified/style-rtl.css
  assets/css/unminified/style.css
  footer.php
  header.php
  inc/addons/breadcrumbs/dynamic-css/dynamic.css.php
  inc/builder/controllers/class-astra-builder-ui-controller.php
  inc/builder/markup/class-astra-builder-header.php
  inc/builder/type/base/dynamic-css/social/class-astra-social-component-dynamic-css.php
  inc/builder/type/header/above-header/dynamic-css/dynamic.css.php
  inc/builder/type/header/below-header/dynamic-css/dynamic.css.php
  inc/builder/type/header/menu/class-astra-header-menu-component.php
  inc/class-astra-dynamic-css.php
  inc/class-astra-loop.php
  inc/core/builder/class-astra-builder-helper.php
  inc/core/builder/class-astra-builder-options.php
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
  inc/customizer/extend-custom-controls/src/social-icons/item-component.js
  inc/customizer/extend-custom-controls/src/social-icons/social-component.js
  inc/markup-extras.php
  index.php
  package-lock.json
  sass/grid/_grid.scss
  sass/media/_media.scss
  sass/site/404/_404-common.scss
  sass/site/404/_404.scss
  sass/site/_frontend.scss
  sass/site/_site.scss
  sass/site/blog/single-post-layouts/_comment-form.scss
  sass/site/blog/single-post-layouts/_single-post-layouts.scss
  sass/site/builder/_header.scss
  sass/site/elements/element-email.scss
  sass/site/elements/element-search.scss
  sass/site/elements/element-social-follow.scss
  sass/site/navigation/_navigation.scss
  sass/site/navigation/_primary-menu.scss
  sass/site/responsive/_responsive.scss
  sass/typography/_copy.scss
  sass/typography/_typography.scss
  sidebar.php
  template-parts/content-blog.php
  template-parts/footer/builder/components.php
  template-parts/footer/builder/desktop-builder-layout.php
  template-parts/header/builder/components.php
  template-parts/header/builder/desktop-builder-layout.php
  template-parts/header/builder/header-row.php
  template-parts/header/builder/mobile-builder-layout.php
  template-parts/header/builder/mobile-header-row.php
Labels: enhancement, ready to merge

#2117 fix: Inline overflow style adds white strip after builder layout
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
  inc/customizer/extend-custom-controls/src/customizer.js
Labels: needs-review

#2126 chore: Style frontend optimization changelog.
  changelog.txt
  inc/compatibility/edd/class-astra-edd.php
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  inc/customizer/class-astra-customizer.php
  inc/customizer/configurations/builder/header/class-astra-customizer-woo-cart-configs.php
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
  inc/customizer/extend-custom-controls/src/customizer.js
Labels: needs-review

#2120 fix: Issues from Beta 2 zip
  assets/css/minified/frontend.min-rtl.css
  assets/css/minified/frontend.min.css
  assets/css/unminified/frontend-rtl.css
  assets/css/unminified/frontend.css
  assets/js/minified/customizer-preview.min.js
  assets/js/unminified/customizer-preview.js
  inc/addons/transparent-header/classes/sections/class-astra-customizer-transparent-header-configs.php
  inc/assets/css/ast-builder-customizer-rtl.css
  inc/assets/css/ast-builder-customizer.css
  inc/builder/type/base/dynamic-css/divider/class-astra-divider-component-dynamic-css.php
  inc/builder/type/base/dynamic-css/html/class-astra-html-component-dynamic-css.php
  inc/builder/type/footer/primary-footer/dynamic-css/dynamic.css.php
  inc/builder/type/header/above-header/dynamic-css/dynamic.css.php
  inc/builder/type/header/below-header/dynamic-css/dynamic.css.php
  inc/builder/type/header/mobile-menu/dynamic-css/dynamic.css.php
  inc/builder/type/header/mobile-trigger/dynamic-css/dynamic.css.php
  inc/builder/type/header/primary-header/dynamic-css/dynamic.css.php
  inc/customizer/class-astra-customizer.php
  inc/customizer/configurations/layout/class-astra-blog-single-layout-configs.php
  inc/customizer/configurations/layout/class-astra-site-container-layout-configs.php
  inc/customizer/configurations/layout/class-astra-site-layout-configs.php
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
  inc/customizer/extend-custom-controls/src/customizer.js
  inc/customizer/extend-custom-controls/src/divider/divider-component.js
Labels: ready to merge

#2118 chore: v3 beta 2 release
  assets/css/minified/compatibility/woocommerce/woocommerce.min-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-rtl.css
  assets/js/minified/customizer-controls-toggle.min.js
  assets/js/minified/customizer-preview.min.js
  assets/js/minified/extend-customizer.min.js
  assets/js/minified/flexibility.min.js
  assets/js/minified/frontend.min.js
  assets/js/minified/navigation.min.js
  assets/js/minified/style.min.js
  changelog.txt
  inc/addons/heading-colors/assets/js/minified/customizer-preview.min.js
  inc/addons/transparent-header/assets/js/minified/customizer-preview.min.js
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  languages/astra.pot
  package-lock.json
Labels: needs-review

#2135 fix: Builder CSS messed up in RTL case
  assets/css/minified/frontend.min-rtl.css
  assets/css/minified/frontend.min.css
  assets/css/unminified/frontend-rtl.css
  assets/css/unminified/frontend.css
  inc/customizer/class-astra-customizer.php
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
  inc/customizer/extend-custom-controls/src/customizer.js
Labels: ready to merge

#2148 fix: Keyamoon link not working fixed.
  README.md
  package-lock.json
  package.json
  readme.txt
Labels: ready to merge

#2116 improvement : Grid layout CSS optimization.
  assets/css/minified/frontend.min-rtl.css
  assets/css/minified/frontend.min.css
  assets/css/unminified/frontend-rtl.css
  assets/css/unminified/frontend.css
  sass/frontend.scss
  sass/grid/_grid-frontend.scss
  sass/grid/bootstrap-frontend.scss
  sass/grid/mixins/_grid-framework.scss
Labels: ready to merge

#2136 fix: Zero values are not accepting in Icon size, Icon spacing, Icon BG space & Icon radius
  assets/css/minified/compatibility/woocommerce/woocommerce.min-rtl.css
  assets/css/minified/frontend.min-rtl.css
  assets/css/minified/frontend.min.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-rtl.css
  assets/css/unminified/frontend-rtl.css
  assets/css/unminified/frontend.css
  assets/js/minified/customizer-controls-toggle.min.js
  assets/js/minified/customizer-preview.min.js
  assets/js/minified/extend-customizer.min.js
  assets/js/minified/flexibility.min.js
  assets/js/minified/frontend.min.js
  assets/js/minified/navigation.min.js
  assets/js/minified/style.min.js
  inc/addons/heading-colors/assets/js/minified/customizer-preview.min.js
  inc/addons/transparent-header/assets/js/minified/customizer-preview.min.js
  inc/builder/type/base/dynamic-css/social/class-astra-social-component-dynamic-css.php
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
Labels: needs-review

#2144 improvements: separate pagination css file and load conditionally
  Gruntfile.js
  assets/css/minified/frontend.min-rtl.css
  assets/css/minified/frontend.min.css
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  assets/css/unminified/frontend-rtl.css
  assets/css/unminified/frontend.css
  assets/css/unminified/style-rtl.css
  assets/css/unminified/style.css
  footer.php
  header.php
  inc/blog/blog-config.php
  inc/builder/controllers/class-astra-builder-ui-controller.php
  inc/class-astra-dynamic-css.php
  inc/class-astra-loop.php
  inc/markup-extras.php
  index.php
  sass/site/blog/_blog.scss
  sass/site/blog/blog-pagination.scss
  sidebar.php
  template-parts/blog/blog-layout.php
  template-parts/content-blog.php
  template-parts/content-page.php
  template-parts/content-single.php
  template-parts/content.php
  template-parts/footer/builder/desktop-builder-layout.php
Labels: ready to merge

#2150 feat: fronend.js optimization
  assets/css/minified/compatibility/woocommerce/woocommerce.min-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-rtl.css
  assets/js/minified/customizer-controls-toggle.min.js
  assets/js/minified/customizer-preview.min.js
  assets/js/minified/extend-customizer.min.js
  assets/js/minified/flexibility.min.js
  assets/js/minified/frontend.min.js
  assets/js/minified/navigation.min.js
  assets/js/minified/style.min.js
  assets/js/unminified/frontend.js
  inc/addons/heading-colors/assets/js/minified/customizer-preview.min.js
  inc/addons/transparent-header/assets/js/minified/customizer-preview.min.js
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
Labels: ready to merge

#2172 fix: flex-wrap wrap CSS not covering menu into respective header
  assets/css/minified/frontend.min-rtl.css
  assets/css/minified/frontend.min.css
  assets/css/unminified/frontend-rtl.css
  assets/css/unminified/frontend.css
  sass/site/builder/_header.scss
Labels: needs-review

#2162 improvements: Added conditions in dynamic CSS to load when component is enabled
  assets/css/minified/compatibility/woocommerce/woocommerce.min-rtl.css
  assets/css/minified/frontend.min-rtl.css
  assets/css/minified/frontend.min.css
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-rtl.css
  assets/css/unminified/frontend-rtl.css
  assets/css/unminified/frontend.css
  assets/css/unminified/style-rtl.css
  assets/css/unminified/style.css
  assets/js/minified/customizer-controls-toggle.min.js
  assets/js/minified/customizer-preview.min.js
  assets/js/minified/extend-customizer.min.js
  assets/js/minified/flexibility.min.js
  assets/js/minified/frontend.min.js
  assets/js/minified/navigation.min.js
  assets/js/minified/style.min.js
  inc/addons/breadcrumbs/dynamic-css/dynamic.css.php
  inc/addons/heading-colors/assets/js/minified/customizer-preview.min.js
  inc/addons/transparent-header/assets/js/minified/customizer-preview.min.js
  inc/class-astra-dynamic-css.php
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  sass/site/compatibility/page-builder/vc-plugin.scss
  sass/site/layout/_layout.scss
  sass/site/secondary/_widgets.scss
Labels: ready to merge

#2152 improvement: revamp main header section div structure
  template-parts/header/builder/header-row.php
Labels: ready to merge

#2178 feat: Addon functionality related CSS removed
  assets/css/minified/frontend.min-rtl.css
  assets/css/minified/frontend.min.css
  assets/css/unminified/frontend-rtl.css
  assets/css/unminified/frontend.css
  sass/site/builder/_header.scss
Labels: ready to merge

#2179 fix: EDD cart hover icon color issue for none style
  inc/builder/type/header/edd-cart/dynamic-css/dynamic.css.php
Labels: needs-review

#2184 fix: Removed iframe from Astra options page as it's not allowed for theme in WordPress
  assets/css/minified/compatibility/woocommerce/woocommerce.min-rtl.css
  assets/css/minified/frontend.min-rtl.css
  assets/css/minified/frontend.min.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-rtl.css
  assets/css/unminified/frontend-rtl.css
  assets/css/unminified/frontend.css
  assets/js/minified/customizer-controls-toggle.min.js
  assets/js/minified/customizer-preview.min.js
  assets/js/minified/extend-customizer.min.js
  assets/js/minified/flexibility.min.js
  assets/js/minified/frontend.min.js
  assets/js/minified/navigation.min.js
  assets/js/minified/style.min.js
  inc/addons/heading-colors/assets/js/minified/customizer-preview.min.js
  inc/addons/transparent-header/assets/js/minified/customizer-preview.min.js
  inc/assets/css/astra-admin-menu-settings-rtl.css
  inc/assets/css/astra-admin-menu-settings.css
  inc/core/builder/class-astra-builder-admin.php
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/theme-update/class-astra-theme-background-updater.php
Labels: needs-review

#2185 fix: Removed NEW tag from customizer builder panels
  inc/assets/css/ast-builder-customizer-rtl.css
  inc/assets/css/ast-builder-customizer.css
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
  inc/customizer/extend-custom-controls/src/customizer.js
Labels: needs-review

#2186 Removed blank lines from markups.
  footer.php
  inc/markup-extras.php
  index.php
Labels: ready to merge
