Repository brainstormforce/astra, pull requests merged in 2021-07, with the labels that each got.

#2933 Include a update-stubs command to update Astra stubs
  composer.json
  composer.lock
  psalm.xml
  tests/php/static-analysis-stubs/astra-stubs.php
Labels: needs-review

#2928 AST-586 - Added add_theme_support for Rank Math breadcrumb
  changelog.txt
  inc/class-astra-after-setup-theme.php
Labels: ready to merge

#2924 AST-622 - Builder - WooCommerce & EDD cart - Cart and Checkout buttons not visible when multiple products added to cart flyout
  changelog.txt
  inc/class-astra-dynamic-css.php
Labels: ready to merge

#2935 AST-488 fix: removed the margin applied to menu items in the menu section
  changelog.txt
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/assets/css/unminified/customizer-style-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/customizer-style.css
  inc/customizer/custom-controls/customizer-style.scss
Labels: ready to merge

#2901 AST-461 - fix: Disable Footer and Footer Widgets option is missing in Page meta setting.
  changelog.txt
  inc/builder/type/footer/widget/dynamic-css/dynamic.css.php
  inc/metabox/class-astra-meta-boxes.php
  package-lock.json
  tests/php/static-analysis-stubs/astra-stubs.php
Labels: ready to merge

#2930 AST-648 - E2E initial setup for Related Posts correct author name.
  package-lock.json
  tests/e2e/config/bootstrap.js
  tests/e2e/e2e-plugin/rest-api/namespace.php
  tests/e2e/specs/customizer/related-posts/author.name.test.js
  tests/e2e/utils/create-new-user.js
  tests/e2e/utils/delete-user.js
Labels: ready to merge

#2931 AST-628 - fix: WP 5.8 JS console error in customizer due to widget settings.
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-rtl.css
  inc/assets/css/ast-builder-customizer-rtl.css
  inc/assets/css/ast-builder-customizer.css
  inc/customizer/class-astra-customizer.php
  inc/customizer/configurations/builder/class-astra-builder-base-configuration.php
  inc/customizer/configurations/builder/footer/class-astra-customizer-footer-builder-configs.php
  inc/customizer/configurations/builder/header/class-astra-customizer-header-builder-configs.php
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
  inc/customizer/extend-custom-controls/src/builder-layout/item-component.js
  inc/extras.php
  tests/php/static-analysis-stubs/astra-stubs.php
Labels: ready to merge

#2944 AST-658 : Customizer spacing issues.
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/assets/css/unminified/typography-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/typography.css
  inc/customizer/custom-controls/typography/typography.scss
Labels: ready to merge

#2941 Use Astra Notices as a composer packages
  composer.json
  composer.lock
  functions.php
  inc/lib/astra-notices/class-astra-notices.php
  inc/lib/astra-notices/composer.json
  inc/lib/astra-notices/notices.js
  phpcs.xml.dist
Labels: ready to merge

#2953 Dependbot npm commands
  .github/dependbot.yml
  package.json
Labels: ready to merge

#2954 Build: Release PR Astra v3.6.3 upcoming update with GB button padding support from global button settings
  README.md
  assets/fonts/google-fonts.json
  assets/js/minified/customizer-preview.min.js
  assets/js/unminified/customizer-preview.js
  changelog.txt
  functions.php
  inc/class-astra-dynamic-css.php
  inc/core/class-astra-theme-options.php
  inc/core/class-gutenberg-editor-css.php
  inc/customizer/class-astra-customizer.php
  inc/extras.php
  inc/google-fonts.php
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-theme-background-updater.php
  languages/astra.pot
  package-lock.json
  package.json
  readme.txt
  style.css
Labels: Release PR checklist, ready to merge

#2962 v3.6.3
  README.md
  assets/fonts/google-fonts.json
  assets/js/minified/customizer-preview.min.js
  assets/js/unminified/customizer-preview.js
  changelog.txt
  functions.php
  inc/class-astra-dynamic-css.php
  inc/core/class-astra-theme-options.php
  inc/core/class-gutenberg-editor-css.php
  inc/customizer/class-astra-customizer.php
  inc/extras.php
  inc/google-fonts.php
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-theme-background-updater.php
  languages/astra.pot
  package-lock.json
  package.json
  readme.txt
  style.css
Labels: ready to merge

#2945 AST-545 The mobile menu closes on scroll on mobile with a flyout and fullscreen off-canvas style.
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-rtl.css
  assets/js/minified/customizer-preview.min.js
  assets/js/minified/extend-customizer.min.js
  assets/js/minified/flexibility.min.js
  assets/js/minified/frontend-pro.min.js
  assets/js/minified/frontend.min.js
  assets/js/minified/mobile-cart.min.js
  assets/js/minified/navigation.min.js
  assets/js/minified/style.min.js
  assets/js/unminified/frontend.js
  changelog.txt
  inc/addons/heading-colors/assets/js/minified/customizer-preview.min.js
  inc/addons/transparent-header/assets/js/minified/customizer-preview.min.js
  inc/builder/type/footer/copyright/assets/js/minified/customizer-preview.min.js
  inc/builder/type/footer/html/assets/js/minified/customizer-preview.min.js
  inc/builder/type/footer/menu/assets/js/minified/customizer-preview.min.js
  inc/builder/type/header/above-header/assets/js/minified/customizer-preview.min.js
  inc/builder/type/header/account/assets/js/minified/customizer-preview.min.js
  inc/builder/type/header/below-header/assets/js/minified/customizer-preview.min.js
  inc/builder/type/header/edd-cart/assets/js/minified/customizer-preview.min.js
  inc/builder/type/header/menu/assets/js/minified/customizer-preview.min.js
  inc/builder/type/header/mobile-menu/assets/js/minified/customizer-preview.min.js
  inc/builder/type/header/mobile-trigger/assets/js/minified/customizer-preview.min.js
  inc/builder/type/header/off-canvas/assets/js/minified/customizer-preview.min.js
  inc/builder/type/header/primary-header/assets/js/minified/customizer-preview.min.js
  inc/builder/type/header/search/assets/js/minified/customizer-preview.min.js
  inc/builder/type/header/site-identity/assets/js/minified/customizer-preview.min.js
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  package-lock.json
Labels: ready to merge

#2964 Build: Release PR AST-679 - Introducing Content links underline option
  README.md
  assets/js/minified/customizer-preview.min.js
  assets/js/unminified/customizer-preview.js
  changelog.txt
  functions.php
  inc/class-astra-dynamic-css.php
  inc/core/class-astra-theme-options.php
  inc/core/class-gutenberg-editor-css.php
  inc/customizer/configurations/typography/class-astra-body-typo-configs.php
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-theme-background-updater.php
  languages/astra.pot
  package.json
  readme.txt
  style.css
Labels: Release PR checklist, needs-review

#2966 v3.6.4
  README.md
  assets/js/minified/customizer-preview.min.js
  assets/js/unminified/customizer-preview.js
  changelog.txt
  functions.php
  inc/class-astra-dynamic-css.php
  inc/core/class-astra-theme-options.php
  inc/core/class-gutenberg-editor-css.php
  inc/customizer/configurations/typography/class-astra-body-typo-configs.php
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-theme-background-updater.php
  languages/astra.pot
  package.json
  readme.txt
  style.css
Labels: ready to merge

#2967 Use chekalsky/phpcs-action for phpcs as this provides annotations
  .github/workflows/code-analysis.yml
  composer.json
  inc/theme-update/astra-update-functions.php
  package-lock.json
  tests/php/static-analysis-stubs/astra-stubs.php
Labels: ready to merge

#2979 Install Astra Notices from packagist.org
  composer.json
  composer.lock
Labels: ready to merge

#2947 AST-663 fix: UI changes in the customizer for WP 5.8
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/assets/css/unminified/customizer-style-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/customizer-style.css
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/customizer-style.scss
  sass/admin/block-editor-styles.scss
Labels: ready to merge

#2984 Remove puppeteer dependency
  bin/scripts/dynamic-css-to-file.js
  package-lock.json
  package.json
Labels: ready to merge

#2981 Create astra-stubs.php file if not exists to avoid error during removing this file.
  composer.json
  package-lock.json
  tests/php/static-analysis-stubs/astra-stubs.php
Labels: ready to merge

#2915 AST-623 - fix: Null border size showing solid border for headers on frontend
  changelog.txt
  inc/addons/transparent-header/classes/dynamic-css/dynamic.css.php
  inc/builder/type/header/above-header/assets/js/minified/customizer-preview.min.js
  inc/builder/type/header/above-header/assets/js/unminified/customizer-preview.js
  inc/builder/type/header/above-header/dynamic-css/dynamic.css.php
  inc/builder/type/header/below-header/assets/js/minified/customizer-preview.min.js
  inc/builder/type/header/below-header/assets/js/unminified/customizer-preview.js
  inc/builder/type/header/below-header/dynamic-css/dynamic.css.php
  inc/builder/type/header/primary-header/assets/js/minified/customizer-preview.min.js
  inc/builder/type/header/primary-header/assets/js/unminified/customizer-preview.js
  inc/builder/type/header/primary-header/dynamic-css/dynamic.css.php
Labels: needs-review

#2980 AST-667 - Widget shortcut icons size updated in builder area
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-rtl.css
  assets/js/minified/customizer-preview.min.js
  assets/js/minified/extend-customizer.min.js
  assets/js/minified/flexibility.min.js
  assets/js/minified/frontend-pro.min.js
  assets/js/minified/frontend.min.js
  assets/js/minified/mobile-cart.min.js
  assets/js/minified/navigation.min.js
  assets/js/minified/style.min.js
  inc/addons/heading-colors/assets/js/minified/customizer-preview.min.js
  inc/addons/transparent-header/assets/js/minified/customizer-preview.min.js
  inc/assets/css/ast-builder-customizer-rtl.css
  inc/assets/css/ast-builder-customizer.css
  inc/builder/type/footer/copyright/assets/js/minified/customizer-preview.min.js
  inc/builder/type/footer/html/assets/js/minified/customizer-preview.min.js
  inc/builder/type/footer/menu/assets/js/minified/customizer-preview.min.js
  inc/builder/type/header/above-header/assets/js/minified/customizer-preview.min.js
  inc/builder/type/header/account/assets/js/minified/customizer-preview.min.js
  inc/builder/type/header/below-header/assets/js/minified/customizer-preview.min.js
  inc/builder/type/header/edd-cart/assets/js/minified/customizer-preview.min.js
  inc/builder/type/header/menu/assets/js/minified/customizer-preview.min.js
  inc/builder/type/header/mobile-menu/assets/js/minified/customizer-preview.min.js
  inc/builder/type/header/mobile-trigger/assets/js/minified/customizer-preview.min.js
  inc/builder/type/header/off-canvas/assets/js/minified/customizer-preview.min.js
  inc/builder/type/header/primary-header/assets/js/minified/customizer-preview.min.js
  inc/builder/type/header/search/assets/js/minified/customizer-preview.min.js
  inc/builder/type/header/site-identity/assets/js/minified/customizer-preview.min.js
  inc/compatibility/woocommerce/woocommerce-common-functions.php
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
Labels: needs-review

#2982 AST-652 - Editor shrink issue resolved in WP-5.8
  changelog.txt
  inc/core/class-gutenberg-editor-css.php
Labels: ready to merge

#2992 AST-665 chore: Added tool tip for the icons in the widget component.
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-rtl.css
  assets/js/minified/customizer-preview.min.js
  assets/js/minified/extend-customizer.min.js
  assets/js/minified/flexibility.min.js
  assets/js/minified/frontend-pro.min.js
  assets/js/minified/frontend.min.js
  assets/js/minified/mobile-cart.min.js
  assets/js/minified/navigation.min.js
  assets/js/minified/style.min.js
  inc/addons/heading-colors/assets/js/minified/customizer-preview.min.js
  inc/addons/transparent-header/assets/js/minified/customizer-preview.min.js
  inc/builder/type/footer/copyright/assets/js/minified/customizer-preview.min.js
  inc/builder/type/footer/html/assets/js/minified/customizer-preview.min.js
  inc/builder/type/footer/menu/assets/js/minified/customizer-preview.min.js
  inc/builder/type/header/above-header/assets/js/minified/customizer-preview.min.js
  inc/builder/type/header/account/assets/js/minified/customizer-preview.min.js
  inc/builder/type/header/below-header/assets/js/minified/customizer-preview.min.js
  inc/builder/type/header/edd-cart/assets/js/minified/customizer-preview.min.js
  inc/builder/type/header/menu/assets/js/minified/customizer-preview.min.js
  inc/builder/type/header/mobile-menu/assets/js/minified/customizer-preview.min.js
  inc/builder/type/header/mobile-trigger/assets/js/minified/customizer-preview.min.js
  inc/builder/type/header/off-canvas/assets/js/minified/customizer-preview.min.js
  inc/builder/type/header/primary-header/assets/js/minified/customizer-preview.min.js
  inc/builder/type/header/search/assets/js/minified/customizer-preview.min.js
  inc/builder/type/header/site-identity/assets/js/minified/customizer-preview.min.js
  inc/customizer/configurations/builder/class-astra-builder-base-configuration.php
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
  inc/customizer/extend-custom-controls/src/builder-layout/item-component.js
Labels: ready to merge

#2951 AST-653 - Added compatibility for search block in WordPress 5.8
  assets/js/minified/customizer-preview.min.js
  assets/js/unminified/customizer-preview.js
  changelog.txt
  functions.php
  inc/class-astra-dynamic-css.php
  inc/core/class-gutenberg-editor-css.php
  inc/customizer/class-astra-customizer.php
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/dynamic-css/block-editor-compatibility.php
  inc/extras.php
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-theme-background-updater.php
Labels: needs-review

#2989 AST-664 - WordPress 5.8 blocks default design UI
  inc/dynamic-css/block-editor-compatibility.php
  package-lock.json
  tests/php/static-analysis-stubs/astra-stubs.php
Labels: needs-review

#2996 AST-692 - Updated Astra notice lib and notice register action
  inc/core/class-astra-admin-settings.php
  inc/lib/astra-notices/notices.js
Labels: needs-review

#3006 Revert "build(deps-dev): bump autoprefixer from 9.8.6 to 10.3.1"
  package-lock.json
  package.json
Labels: ready to merge

#3003 AST-696 chore: remmoved the above divider for the footer widget alignment control
  composer.lock
  inc/customizer/configurations/builder/class-astra-builder-base-configuration.php
Labels: ready to merge

#3004 AST-699 - GB editor padding issue with nested blocks
  inc/core/class-gutenberg-editor-css.php
Labels: needs-review

#3002 AST-702 - Builder widget sections search block don't apply block defaults
  assets/js/minified/customizer-preview.min.js
  assets/js/unminified/customizer-preview.js
  inc/class-astra-dynamic-css.php
  inc/dynamic-css/block-editor-compatibility.php
Labels: needs-review

#3008 AST-695 - Widget design settings not working in Block editor
  inc/assets/css/ast-builder-customizer-rtl.css
  inc/assets/css/ast-builder-customizer.css
  inc/builder/type/base/assets/js/customizer-preview.js
  inc/builder/type/base/dynamic-css/widget/class-astra-widget-component-dynamic-css.php
  inc/builder/type/class-astra-builder-base-dynamic-css.php
  inc/builder/type/footer/widget/class-astra-footer-widget-component-loader.php
  inc/builder/type/header/widget/class-astra-header-widget-component-loader.php
Labels: needs-review

#3007 AST-697 - Added bottom margin 20px space for widget-appender
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/assets/css/unminified/customizer-style-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/customizer-style.css
  inc/customizer/custom-controls/customizer-style.scss
Labels: needs-review

#3010 AST-705 - Update NPM dependencies
  Gruntfile.js
  package-lock.json
  package.json
Labels: needs-review

#3013 chore: Revamped code & build grunt
  assets/js/minified/customizer-preview.min.js
  assets/js/unminified/customizer-preview.js
  changelog.txt
  inc/class-astra-after-setup-theme.php
  inc/class-astra-dynamic-css.php
  inc/customizer/class-astra-customizer.php
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-theme-background-updater.php
Labels: needs-review

#3016 AST-698 chore: Added margin for the more settings for a block in customizer.
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/assets/css/unminified/customizer-style-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/customizer-style.css
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/customizer-style.scss
Labels: ready to merge

#3014 Build: Release PR v3.6.5
  changelog.txt
  inc/class-astra-dynamic-css.php
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/dynamic-css/block-editor-compatibility.php
  inc/extras.php
  inc/theme-update/astra-update-functions.php
  languages/astra.pot
  package-lock.json
  package.json
Labels: Release PR checklist, ready to merge

#2988 Install latest version of the theme-check plugin but theme-check action commit locked
  .github/workflows/theme-check.yml
Labels: ready to merge

#2990 AST-543 - OL tag's margin space affects on Elementor's TOC widget
  changelog.txt
  inc/builder/type/header/above-header/dynamic-css/dynamic.css.php
  inc/builder/type/header/below-header/dynamic-css/dynamic.css.php
  inc/builder/type/header/primary-header/dynamic-css/dynamic.css.php
  inc/compatibility/class-astra-elementor.php
  inc/extras.php
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-theme-background-updater.php
Labels: needs-review

#3027 chore: Missing changelog adding in next-release
  changelog.txt
Labels: needs-review

#3029 chore: next-release to release-candidate PR changes
  functions.php
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
  inc/customizer/extend-custom-controls/src/builder-layout/item-component.js
  inc/theme-update/astra-update-functions.php
Labels: needs-review

#3019 AST-707 - Customizer builder section not scollable which leads not acceble issue for many elements from builder
  changelog.txt
  inc/assets/css/ast-builder-customizer-rtl.css
  inc/assets/css/ast-builder-customizer.css
Labels: needs-review

#3031 AST-711 - Transparent header border showing in firefox even it's not set
  changelog.txt
  inc/addons/transparent-header/classes/dynamic-css/dynamic.css.php
  inc/builder/type/header/above-header/dynamic-css/dynamic.css.php
  inc/builder/type/header/below-header/dynamic-css/dynamic.css.php
  inc/builder/type/header/primary-header/dynamic-css/dynamic.css.php
  inc/core/common-functions.php
Labels: needs-review

#3045 AST-713 - QA reported issue fixed in v3.6.6 package
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/color-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/color.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/dynamic-css/pagination.php
Labels: ready to merge

#3048 v3.6.6 release - Ast notice triggers not working
  README.md
  changelog.txt
  functions.php
  inc/core/class-astra-admin-settings.php
  languages/astra.pot
  package.json
  readme.txt
  style.css
Labels: Release PR checklist, ready to merge

#3030 Build: v3.6.7 Release PR
  README.md
  assets/fonts/google-fonts.json
  changelog.txt
  functions.php
  inc/builder/type/footer/widget/dynamic-css/dynamic.css.php
  inc/core/class-astra-admin-settings.php
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/extras.php
  inc/google-fonts.php
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-theme-background-updater.php
  languages/astra.pot
  package-lock.json
  package.json
  readme.txt
  style.css
  tests/php/static-analysis-stubs/astra-stubs.php
Labels: Release PR checklist, needs-review

#3053 Clean the Astra build directory before recreating it
  Gruntfile.js
  tests/e2e/config/expect-extensions.js
  tests/e2e/utils/create-new-user.js
Labels: ready to merge

#3059 chore: Update next release with master
  README.md
  assets/fonts/google-fonts.json
  changelog.txt
  functions.php
  inc/addons/transparent-header/classes/dynamic-css/dynamic.css.php
  inc/builder/type/footer/widget/dynamic-css/dynamic.css.php
  inc/builder/type/header/above-header/dynamic-css/dynamic.css.php
  inc/builder/type/header/below-header/dynamic-css/dynamic.css.php
  inc/builder/type/header/primary-header/dynamic-css/dynamic.css.php
  inc/core/class-astra-admin-settings.php
  inc/core/common-functions.php
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/color-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/color.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/dynamic-css/pagination.php
  inc/extras.php
  inc/google-fonts.php
  inc/markup-extras.php
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-theme-background-updater.php
  languages/astra.pot
  package-lock.json
  package.json
  readme.txt
  style.css
  tests/php/static-analysis-stubs/astra-stubs.php
Labels: ready to merge
