Repository brainstormforce/astra, pull requests merged in 2021-09, with the labels that each got.

#3185 fix: reverted cart related CSS which was removed unexpectedly.
  inc/class-astra-dynamic-css.php
Labels: ready to merge

#3184 AST-868 - Gutenberg Editor content area showing white background color when Full-Width Contained / Stretched layout is active
  changelog.txt
  inc/core/class-gutenberg-editor-css.php
  tests/e2e/specs/customizer/global/typography.test.js
Labels: ready to merge

#3191 Build: v3.6.9 Release PR
  README.md
  assets/fonts/google-fonts.json
  changelog.txt
  inc/class-astra-dynamic-css.php
  inc/core/common-functions.php
  inc/customizer/class-astra-customizer.php
  inc/extras.php
  inc/google-fonts.php
  inc/lib/batch-processing/class-astra-wp-background-process.php
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-theme-background-updater.php
  languages/astra.pot
  package-lock.json
  package.json
  readme.txt
  style.css
Labels: ready to merge, Release PR checklist

#3173 Added functions to retrieve Palette and Typography preset option values
  inc/core/class-gutenberg-editor-css.php
  inc/core/common-functions.php
  inc/customizer/configurations/colors-background/class-astra-body-colors-configs.php
  inc/customizer/configurations/layout/class-astra-site-container-layout-configs.php
  inc/customizer/configurations/typography/class-astra-global-typo-configs.php
  inc/dynamic-css/content-background.php
  inc/dynamic-css/global-color-palette.php
  inc/extras.php
  inc/modules/related-posts/css/dynamic-css.php
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-theme-background-updater.php
  package-lock.json
  package.json
  tests/php/static-analysis-stubs/astra-stubs.php
Labels: ready to merge

#3180 Fix: content background color applying to comment area
  assets/js/minified/customizer-preview.min.js
  assets/js/unminified/customizer-preview.js
  inc/dynamic-css/content-background.php
Labels: ready to merge

#3181 GCP-139 Fix: alignment issue with font weight and text transform option
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/assets/css/unminified/customizer-style-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/customizer-style.css
  inc/customizer/custom-controls/customizer-style.scss
Labels: ready to merge

#3214 GCP-150 Modified labels for Palette colors
  inc/class-astra-global-palette.php
  inc/compatibility/class-astra-elementor.php
  inc/core/builder/class-astra-builder-options.php
Labels: ready to merge

#3217 GCP-154 Decreased timeout for reflecting color palette change in the preview
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
  inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
Labels: ready to merge

#3212 GCP-151 Added backward compatibility for copyright text color
  inc/builder/type/footer/copyright/dynamic-css/dynamic.css.php
  inc/core/builder/class-astra-builder-options.php
  inc/theme-update/astra-update-functions.php
Labels: ready to merge

#3202 AST-781 - Breadcrumb compatibility with SEOPress.
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min.css
  assets/css/minified/frontend.min-rtl.css
  assets/css/minified/frontend.min.css
  assets/css/minified/main.min-rtl.css
  assets/css/minified/main.min.css
  assets/css/minified/style-flex.min.css
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  changelog.txt
  inc/addons/breadcrumbs/assets/js/minified/customizer-preview.min.js
  inc/addons/breadcrumbs/assets/js/unminified/customizer-preview.js
  inc/addons/breadcrumbs/class-astra-breadcrumb-trail.php
  inc/addons/breadcrumbs/class-astra-breadcrumbs.php
  inc/addons/breadcrumbs/customizer/class-astra-breadcrumbs-configs.php
  inc/addons/breadcrumbs/dynamic-css/dynamic.css.php
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
Labels: ready to merge

#3215 AST-659 - fix: Default text for add widget is align in top
  assets/css/minified/frontend.min-rtl.css
  assets/css/minified/frontend.min.css
  assets/css/minified/main.min-rtl.css
  assets/css/minified/main.min.css
  assets/css/minified/style-flex.min.css
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  assets/css/unminified/frontend-rtl.css
  assets/css/unminified/frontend.css
  assets/css/unminified/main-rtl.css
  assets/css/unminified/main.css
  assets/css/unminified/style-flex-rtl.css
  assets/css/unminified/style-flex.css
  assets/css/unminified/style-rtl.css
  assets/css/unminified/style.css
  changelog.txt
  sass/site/secondary/_widgets.scss
Labels: needs-review

#3211 AST-801 - Updated label for Transparent Header > Social > Text color to Text / Icon as color supports icon too
  inc/addons/transparent-header/classes/sections/class-astra-customizer-transparent-header-configs.php
Labels: needs-review

#3107 AST-757 - Added black default color to editor component button in editor
  inc/assets/css/block-editor-styles-rtl.css
  inc/assets/css/block-editor-styles.css
  sass/admin/block-editor-styles.scss
Labels: needs-review

#3112 AST-762 - Hover block selection improved for GB editor
  inc/assets/css/block-editor-styles-rtl.css
  inc/assets/css/block-editor-styles.css
  sass/admin/block-editor-styles.scss
Labels: needs-review

#3115 AST-765 - Added editor left spacing for pre blocks for improving editor UI
  inc/assets/css/block-editor-styles-rtl.css
  inc/assets/css/block-editor-styles.css
  sass/admin/block-editor-styles.scss
Labels: needs-review

#3128 AST-766 - Table block alignment not working in Editor
  assets/css/minified/editor-style.min-rtl.css
  assets/css/minified/editor-style.min.css
  assets/css/minified/frontend.min-rtl.css
  assets/css/minified/frontend.min.css
  assets/css/minified/main.min-rtl.css
  assets/css/minified/main.min.css
  assets/css/minified/style-flex.min.css
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  assets/css/unminified/editor-style-rtl.css
  assets/css/unminified/editor-style.css
  assets/css/unminified/frontend-rtl.css
  assets/css/unminified/frontend.css
  assets/css/unminified/main-rtl.css
  assets/css/unminified/main.css
  assets/css/unminified/style-flex-rtl.css
  assets/css/unminified/style-flex.css
  assets/css/unminified/style-rtl.css
  assets/css/unminified/style.css
  inc/assets/css/block-editor-styles-rtl.css
  inc/assets/css/block-editor-styles.css
  sass/elements/_tables.scss
Labels: ready to merge

#3117 AST-770 - Added highlightening background color to spacer block in editor
  inc/assets/css/block-editor-styles-rtl.css
  inc/assets/css/block-editor-styles.css
  inc/assets/js/block-editor-script.js
  sass/admin/block-editor-styles.scss
Labels: needs-review

#3121 AST-772 - Added padding around some blocks to improve editor UI
  inc/assets/css/block-editor-styles-rtl.css
  inc/assets/css/block-editor-styles.css
  sass/admin/block-editor-styles.scss
Labels: needs-review

#3123 AST-774 - Override default large space margin by 20px for UL & OL in editor
  inc/assets/css/block-editor-styles-rtl.css
  inc/assets/css/block-editor-styles.css
  sass/admin/block-editor-styles.scss
Labels: needs-review

#3127 AST-776 - Social icon sizes not reflecting correctly as per their sizes in editor
  inc/assets/css/block-editor-styles-rtl.css
  inc/assets/css/block-editor-styles.css
  sass/admin/block-editor-styles.scss
Labels: needs-review

#3109 AST-760 - Removed left-right extra padding space in add buttons setting
  inc/assets/css/block-editor-styles-rtl.css
  inc/assets/css/block-editor-styles.css
  sass/admin/block-editor-styles.scss
Labels: needs-review

#3113 AST-764 - Editor lists blocks outside screen intent issue fixed
  inc/assets/css/block-editor-styles-rtl.css
  inc/assets/css/block-editor-styles.css
  sass/admin/block-editor-styles.scss
Labels: ready to merge

#3221 Build: Release PR Version 3.7.0
  README.md
  assets/fonts/google-fonts.json
  changelog.txt
  functions.php
  inc/class-astra-global-palette.php
  inc/compatibility/class-astra-elementor.php
  inc/customizer/configurations/typography/class-astra-headings-typo-configs.php
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/dynamic-css/content-background.php
  inc/dynamic-css/global-color-palette.php
  inc/extras.php
  inc/google-fonts.php
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-theme-background-updater.php
  languages/astra.pot
  package-lock.json
  package.json
  readme.txt
  style.css
  tests/php/static-analysis-stubs/astra-stubs.php
Labels: ready to merge, Release PR checklist

#3249 fix: Button radius preview not working in customizer
  assets/js/minified/customizer-preview.min.js
  assets/js/unminified/customizer-preview.js
Labels: ready to merge

#3251 Release candidate v3.7.0 - Preview GB Button issue fixed.
  assets/js/minified/customizer-preview.min.js
  assets/js/unminified/customizer-preview.js
Labels: ready to merge

#3258 Build: Release PR Fix: Group block full width fix
  README.md
  changelog.txt
  functions.php
  inc/compatibility/class-astra-gutenberg.php
  package-lock.json
  package.json
  readme.txt
  style.css
  tests/php/static-analysis-stubs/astra-stubs.php
Labels: ready to merge, Release PR checklist

#3265 Build: Release PR GCP-160 Remove global linking for site background option
  README.md
  assets/fonts/google-fonts.json
  changelog.txt
  functions.php
  inc/core/class-astra-theme-options.php
  inc/google-fonts.php
  package-lock.json
  package.json
  readme.txt
  style.css
Labels: ready to merge, Release PR checklist

#3268 Version 3.7.2 Release
  README.md
  assets/fonts/google-fonts.json
  changelog.txt
  functions.php
  inc/core/class-astra-theme-options.php
  inc/google-fonts.php
  package-lock.json
  package.json
  readme.txt
  style.css
Labels: ready to merge

#3196 AST-714 - Layer_1 duplicate ID in W3C validation
  assets/svg/svgs.json
  changelog.txt
  inc/assets/images/astra-logo.svg
  inc/assets/images/astra.svg
  inc/core/class-astra-icons.php
  template-parts/header/builder/components.php
Labels: needs-review

#3222 AST-268 - Color picker tooltip appear on hover of selection area & it's palette
  changelog.txt
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/color-group-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/color-group.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/custom-controls/color-group/color-group.scss
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
Labels: needs-review

#3279 Make it easier to copy the customizer settings on e2e environment
  .wp-env.json
  tests/e2e/e2e-plugin/customizer-settings/namespace.php
  tests/e2e/e2e-plugin/loader.php
  tests/e2e/e2e-plugin/rest-api/namespace.php
Labels: ready to merge

#3236 AST-715 - Fixing CSS parse errors
  changelog.txt
  inc/class-astra-dynamic-css.php
Labels: ready to merge

#3189 AST-701 - fix: duplicate site-navigation id for menus
  assets/css/minified/frontend.min-rtl.css
  assets/css/minified/frontend.min.css
  assets/css/minified/main.min-rtl.css
  assets/css/minified/main.min.css
  assets/css/minified/style-flex.min.css
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  assets/css/unminified/frontend-rtl.css
  assets/css/unminified/frontend.css
  assets/css/unminified/main-rtl.css
  assets/css/unminified/main.css
  assets/css/unminified/style-flex-rtl.css
  assets/css/unminified/style-flex.css
  assets/css/unminified/style-rtl.css
  assets/css/unminified/style.css
  changelog.txt
  functions.php
  inc/addons/transparent-header/assets/js/minified/customizer-preview.min.js
  inc/addons/transparent-header/assets/js/unminified/customizer-preview.js
  inc/addons/transparent-header/classes/dynamic-css/dynamic.css.php
  inc/builder/type/footer/menu/class-astra-footer-menu-component.php
  inc/builder/type/header/account/class-astra-header-account-component.php
  inc/builder/type/header/menu/class-astra-header-menu-component.php
  inc/builder/type/header/mobile-menu/class-astra-mobile-menu-component.php
  inc/core/class-astra-icons.php
  inc/markup-extras.php
  package-lock.json
  sass/site/navigation/_navigation.scss
Labels: ready to merge

#3108 AST-742 - Branch with complete GB editor improvements
  assets/css/minified/editor-style.min-rtl.css
  assets/css/minified/editor-style.min.css
  assets/css/minified/frontend.min-rtl.css
  assets/css/minified/frontend.min.css
  assets/css/minified/main.min-rtl.css
  assets/css/minified/main.min.css
  assets/css/minified/style-flex.min.css
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  assets/css/unminified/editor-style-rtl.css
  assets/css/unminified/editor-style.css
  assets/css/unminified/frontend-rtl.css
  assets/css/unminified/frontend.css
  assets/css/unminified/main-rtl.css
  assets/css/unminified/main.css
  assets/css/unminified/style-flex-rtl.css
  assets/css/unminified/style-flex.css
  assets/css/unminified/style-rtl.css
  assets/css/unminified/style.css
  changelog.txt
  functions.php
  inc/assets/css/block-editor-styles-rtl.css
  inc/assets/css/block-editor-styles.css
  inc/assets/js/block-editor-script.js
  inc/class-astra-dynamic-css.php
  inc/core/class-gutenberg-editor-css.php
  inc/dynamic-css/block-editor-compatibility.php
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-theme-background-updater.php
  sass/admin/block-editor-styles.scss
  sass/elements/_elements.scss
  sass/elements/_tables.scss
Labels: ready to merge

#3298 AST-932 - Fullsize & Widesize block layouts missed from core/image block
  changelog.txt
  theme.json
Labels: ready to merge

#3314 AST-955 - Block settings from customizer getting round shape by box-shadow CSS
  changelog.txt
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/assets/css/unminified/customizer-style-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/customizer-style.css
  inc/customizer/custom-controls/customizer-style.scss
Labels: needs-review

#3306 AST-939 - Offcanvas content directly visible on frontend when Toggle Button not dropped in builder area
  assets/js/minified/frontend.min.js
  assets/js/unminified/frontend.js
  changelog.txt
  template-parts/header/builder/desktop-builder-layout.php
Labels: ready to merge

#3312 AST-957 - Introduce filter to disable theme global colors in Elementor
  inc/class-astra-global-palette.php
  inc/compatibility/class-astra-elementor.php
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
  inc/customizer/extend-custom-controls/src/customizer.js
  inc/extras.php
  tests/php/static-analysis-stubs/astra-stubs.php
Labels: ready to merge

#3309 AST-956 - Modified theme and link color with sufficient contrast ratio
  inc/class-astra-global-palette.php
  inc/core/builder/class-astra-builder-options.php
Labels: ready to merge

#3317 AST-933 - Fix: Button Preset preview not working
  assets/js/minified/customizer-preview.min.js
  assets/js/unminified/customizer-preview.js
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
Labels: ready to merge

#3323 AST-953 - Fix: Palette change customizer preview not working
  changelog.txt
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
  inc/customizer/extend-custom-controls/src/customizer.js
  package-lock.json
Labels: ready to merge

#3327 AST-933 - chore: Updated changelog
  changelog.txt
Labels: ready to merge

#3328 AST-932 - Fix: (cherry pick) Fullsize & Widesize block layouts missed from core/image block
  changelog.txt
  theme.json
Labels: ready to merge

#3332 AST-956 - Chore: (cherry pick) Modified theme and link color with sufficient contrast ratio
  inc/class-astra-global-palette.php
  inc/core/builder/class-astra-builder-options.php
Labels: ready to merge

#3337 Build: Release PR v3.7.3
  README.md
  assets/fonts/google-fonts.json
  functions.php
  inc/google-fonts.php
  languages/astra.pot
  package-lock.json
  package.json
  readme.txt
  style.css
Labels: ready to merge, Release PR checklist

#3341 Release candidate
  README.md
  assets/fonts/google-fonts.json
  assets/js/minified/customizer-preview.min.js
  assets/js/minified/frontend.min.js
  assets/js/unminified/customizer-preview.js
  assets/js/unminified/frontend.js
  changelog.txt
  functions.php
  inc/class-astra-global-palette.php
  inc/core/builder/class-astra-builder-options.php
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/assets/css/unminified/customizer-style-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/customizer-style.css
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/custom-controls/customizer-style.scss
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
  inc/customizer/extend-custom-controls/package-lock.json
  inc/customizer/extend-custom-controls/src/customizer.js
  inc/google-fonts.php
  languages/astra.pot
  package-lock.json
  package.json
  readme.txt
  style.css
  template-parts/header/builder/desktop-builder-layout.php
  theme.json
Labels: ready to merge

#3247 AST-908 - Added PHPCS ruleset for adding astra prefix in code
  changelog.txt
  comments.php
  functions.php
  inc/blog/blog.php
  inc/builder/markup/class-astra-builder-footer.php
  inc/builder/markup/class-astra-builder-header.php
  inc/builder/type/footer/menu/dynamic-css/dynamic.css.php
  inc/builder/type/footer/widget/dynamic-css/dynamic.css.php
  inc/builder/type/header/above-header/dynamic-css/dynamic.css.php
  inc/builder/type/header/menu/class-astra-header-menu-component.php
  inc/builder/type/header/mobile-menu/class-astra-mobile-menu-component.php
  inc/class-astra-dynamic-css.php
  inc/compatibility/class-astra-beaver-builder.php
  inc/compatibility/class-astra-beaver-themer.php
  inc/compatibility/class-astra-elementor-pro.php
  inc/compatibility/class-astra-elementor.php
  inc/compatibility/lifterlms/class-astra-lifterlms.php
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  inc/core/builder/class-astra-builder-options.php
  inc/core/class-astra-admin-settings.php
  inc/core/class-astra-walker-page.php
  inc/core/class-gutenberg-editor-css.php
  inc/core/common-functions.php
  inc/core/deprecated/deprecated-filters.php
  inc/core/deprecated/deprecated-functions.php
  inc/core/deprecated/deprecated-hooks.php
  inc/core/theme-hooks.php
  inc/customizer/class-astra-fonts.php
  inc/customizer/configurations/layout/class-astra-site-identity-configs.php
  inc/customizer/customizer-controls.php
  inc/dynamic-css/comments-flex.php
  inc/dynamic-css/comments.php
  inc/dynamic-css/pagination.php
  inc/extras.php
  inc/markup-extras.php
  inc/metabox/class-astra-meta-box-operations.php
  inc/template-parts.php
  inc/theme-update/class-astra-theme-background-updater.php
  phpcs.xml.dist
  sidebar.php
  template-parts/advanced-footer/layout-4.php
  template-parts/footer/builder/components.php
  template-parts/footer/builder/footer-row.php
  template-parts/footer/footer-sml-layout-2.php
  template-parts/footer/footer-sml-layout.php
  template-parts/header/builder/components.php
  template-parts/header/builder/desktop-builder-layout.php
  template-parts/header/builder/header-row.php
  template-parts/header/builder/mobile-builder-layout.php
  template-parts/header/builder/mobile-header-row.php
  tests/php/psalm-baseline.xml
  tests/php/static-analysis-stubs/astra-stubs.php
Labels: ready to merge

#2881 AST-780 - Enable axe tests after e2e tests
  header.php
  sidebar.php
  tests/e2e/config/bootstrap.js
Labels: needs-review

#3345 AST-780 - v3.7.3 Master latest code into next-release
  README.md
  assets/fonts/google-fonts.json
  changelog.txt
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
  inc/customizer/extend-custom-controls/package-lock.json
  inc/google-fonts.php
  languages/astra.pot
  package-lock.json
  package.json
  readme.txt
  style.css
Labels: ready to merge
