Repository brainstormforce/astra, pull requests merged in 2021-11, with the labels that each got.

#3590 AST-1215 - Added setup prototype for starting adding compatibility for woocommerce elementor widgets
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce.css
  changelog.txt
  inc/compatibility/class-astra-elementor-pro.php
  inc/compatibility/class-astra-elementor.php
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  inc/extras.php
  sass/site/compatibility/woocommerce/woocommerce-grid.scss
  sass/site/compatibility/woocommerce/woocommerce.scss
  tests/e2e/config/expect-extensions.js
Labels: ready to merge

#3655 AST-1215 - Added compatibility for woocommerce elementor widgets
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce.css
  bin/scripts/pre-e2e-tests.sh
  changelog.txt
  inc/compatibility/class-astra-elementor-pro.php
  inc/compatibility/class-astra-elementor.php
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  inc/customizer/extend-custom-controls/package-lock.json
  inc/extras.php
  inc/lib/astra-notices/class-astra-notices.php
  inc/metabox/class-astra-meta-boxes.php
  package-lock.json
  package.json
  sass/site/compatibility/woocommerce/woocommerce-grid.scss
  sass/site/compatibility/woocommerce/woocommerce.scss
  tests/e2e/config/expect-extensions.js
  tests/php/static-analysis-stubs/astra-stubs.php
Labels: ready to merge

#3656 AST-1215 - Build: Release PR v3.7.5
  README.md
  changelog.txt
  functions.php
  inc/compatibility/class-astra-elementor-pro.php
  inc/extras.php
  languages/astra.pot
  package-lock.json
  package.json
  readme.txt
  style.css
Labels: ready to merge, Release PR checklist

#3660 AST-1284 - fix: disable above header option is not visible in the meta settings
  changelog.txt
  inc/metabox/class-astra-meta-boxes.php
Labels: ready to merge

#3663 AST-1286 - WPForm submit & normal button tags not inheriting customizer button color styles
  assets/css/minified/editor-style.min-rtl.css
  assets/css/minified/editor-style.min.css
  assets/css/minified/frontend.min-rtl.css
  assets/css/minified/frontend.min.css
  assets/css/minified/main.min-rtl.css
  assets/css/minified/main.min.css
  assets/css/minified/style-flex.min.css
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  assets/css/unminified/editor-style-rtl.css
  assets/css/unminified/editor-style.css
  assets/css/unminified/frontend-rtl.css
  assets/css/unminified/frontend.css
  assets/css/unminified/main-rtl.css
  assets/css/unminified/main.css
  assets/css/unminified/style-flex-rtl.css
  assets/css/unminified/style-flex.css
  assets/css/unminified/style-rtl.css
  assets/css/unminified/style.css
  changelog.txt
  inc/assets/css/block-editor-styles-rtl.css
  inc/assets/css/block-editor-styles.css
  sass/admin/block-editor-styles.scss
  sass/elements/_elements.scss
Labels: ready to merge

#3665 AST-1284 - fix: astra meta setting and WPform issues
  assets/css/minified/editor-style.min-rtl.css
  assets/css/minified/editor-style.min.css
  assets/css/minified/frontend.min-rtl.css
  assets/css/minified/frontend.min.css
  assets/css/minified/main.min-rtl.css
  assets/css/minified/main.min.css
  assets/css/minified/style-flex.min.css
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  assets/css/unminified/editor-style-rtl.css
  assets/css/unminified/editor-style.css
  assets/css/unminified/frontend-rtl.css
  assets/css/unminified/frontend.css
  assets/css/unminified/main-rtl.css
  assets/css/unminified/main.css
  assets/css/unminified/style-flex-rtl.css
  assets/css/unminified/style-flex.css
  assets/css/unminified/style-rtl.css
  assets/css/unminified/style.css
  changelog.txt
  inc/assets/css/block-editor-styles-rtl.css
  inc/assets/css/block-editor-styles.css
  inc/lib/astra-notices/class-astra-notices.php
  inc/metabox/class-astra-meta-boxes.php
  sass/admin/block-editor-styles.scss
  sass/elements/_elements.scss
Labels: ready to merge

#3469 AST-1026 - On Cart click open Cart Tray as Sidebar Canvas
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce-layout-grid.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-layout-grid.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce-layout.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-layout.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce-smallscreen-grid.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-smallscreen-grid.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce-smallscreen.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-smallscreen.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-layout-grid-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-layout-grid.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-layout-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-layout.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-smallscreen-grid-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-smallscreen-grid.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-smallscreen-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-smallscreen.css
  assets/css/unminified/compatibility/woocommerce/woocommerce.css
  assets/js/minified/mobile-cart.min.js
  assets/js/unminified/mobile-cart.js
  changelog.txt
  inc/builder/type/header/woo-cart/assets/js/minified/customizer-preview.min.js
  inc/builder/type/header/woo-cart/assets/js/unminified/customizer-preview.js
  inc/builder/type/header/woo-cart/dynamic-css/dynamic.css.php
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  inc/core/builder/class-astra-builder-options.php
  inc/core/class-astra-enqueue-scripts.php
  inc/customizer/configurations/builder/header/class-astra-customizer-woo-cart-configs.php
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/assets/css/unminified/customizer-style-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/customizer-style.css
  inc/customizer/custom-controls/customizer-style.scss
  inc/customizer/extend-custom-controls/src/common/responsive-helper.js
  sass/site/compatibility/woocommerce/_mixins.scss
  sass/site/compatibility/woocommerce/woocommerce-grid.scss
  sass/site/compatibility/woocommerce/woocommerce.scss
Labels: needs-review

#3666 AST-1284 - Build: Release PR v3.7.5
  inc/lib/astra-notices/class-astra-notices.php
  languages/astra.pot
  package.json
Labels: ready to merge, Release PR checklist

#3667 AST-1208 - Release v3.7.5
  assets/css/minified/editor-style.min-rtl.css
  assets/css/minified/editor-style.min.css
  assets/css/minified/frontend.min-rtl.css
  assets/css/minified/frontend.min.css
  assets/css/minified/main.min-rtl.css
  assets/css/minified/main.min.css
  assets/css/minified/style-flex.min.css
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  assets/css/unminified/editor-style-rtl.css
  assets/css/unminified/editor-style.css
  assets/css/unminified/frontend-rtl.css
  assets/css/unminified/frontend.css
  assets/css/unminified/main-rtl.css
  assets/css/unminified/main.css
  assets/css/unminified/style-flex-rtl.css
  assets/css/unminified/style-flex.css
  assets/css/unminified/style-rtl.css
  assets/css/unminified/style.css
  changelog.txt
  inc/assets/css/block-editor-styles-rtl.css
  inc/assets/css/block-editor-styles.css
  inc/metabox/class-astra-meta-boxes.php
  languages/astra.pot
  package.json
  sass/admin/block-editor-styles.scss
  sass/elements/_elements.scss
Labels: ready to merge

#3670 AST-1290 - fix: astra meta settings are not working for Learndash cource page
  changelog.txt
  inc/lib/astra-notices/class-astra-notices.php
  inc/metabox/class-astra-meta-boxes.php
Labels: ready to merge

#3672 AST-1290 - fix: LearnDash astra meta settings are not getting saved.
  changelog.txt
  inc/metabox/class-astra-meta-boxes.php
Labels: ready to merge

#3673 AST-1290 - Build: Release PR for v3.7.5
  inc/metabox/class-astra-meta-boxes.php
  languages/astra.pot
  package-lock.json
  package.json
Labels: ready to merge, Release PR checklist

#3674 AST-1290 - Build: Release PR for v3.7.5
  changelog.txt
  inc/metabox/class-astra-meta-boxes.php
  languages/astra.pot
  package-lock.json
Labels: ready to merge

#3680 AST-1290 - update with master branch
  inc/metabox/class-astra-meta-boxes.php
  languages/astra.pot
  package-lock.json
Labels: ready to merge

#3686 AST-1313 - improvement: Added filter to change position of web stories
  changelog.txt
  inc/compatibility/class-astra-web-stories.php
Labels: ready to merge

#3701 AST-1183 - Color group control's color items are hiding when trying to set in responsive devices
  changelog.txt
  inc/compatibility/class-astra-web-stories.php
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
  inc/customizer/extend-custom-controls/src/common/astra-color-picker-control.js
Labels: ready to merge

#3716 AST-1183 - Cherry picked color-group-control-hiding PR 3701
  changelog.txt
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
  inc/customizer/extend-custom-controls/src/common/astra-color-picker-control.js
Labels: needs-review

#3426 AST-1021 - Cart tray background color options
  .gitignore
  changelog.txt
  inc/builder/type/header/woo-cart/assets/js/minified/customizer-preview.min.js
  inc/builder/type/header/woo-cart/assets/js/unminified/customizer-preview.js
  inc/builder/type/header/woo-cart/dynamic-css/dynamic.css.php
  inc/core/builder/class-astra-builder-options.php
  inc/customizer/configurations/builder/header/class-astra-customizer-woo-cart-configs.php
Labels: ready to merge

#3676 AST-1233 - Inside breadcrumb color typo spacing
  tests/e2e/specs/customizer/breadcrumbs/after-breadcrumb-design-test.js
  tests/e2e/specs/customizer/breadcrumbs/test-breadcrumbs.test.js
Labels: e2e-tests

#3684 AST-1195 - Mobile menu does not close when you click a one page navigation link inside them
  assets/js/minified/frontend.min.js
  assets/js/unminified/frontend.js
  changelog.txt
Labels: ready to merge

#3641 AST-1274 - above header height
  tests/e2e/specs/customizer/header-builder/above-header/height.test.js
Labels: e2e-tests

#3588 AST-1275 - test case for above header bottom border size and bottom border color
  tests/e2e/specs/customizer/header-builder/above-header/bottom-border.test.js
Labels: e2e-tests

#3640 AST-1277 - responsive test case for above header padding
  tests/e2e/specs/customizer/header-builder/above-header/padding.test.js
Labels: e2e-tests

#3642 AST-1278 - added test case for above header margin
  tests/e2e/specs/customizer/header-builder/above-header/margin.test.js
Labels: e2e-tests

#3793 AST-1410 - Fix: JS console error when Custom Layout is added for header
  assets/js/minified/frontend.min.js
  assets/js/unminified/frontend.js
  changelog.txt
  package-lock.json
Labels: ready to merge

#3847 AST-1424 - Linked default builder element's colors to color palette colors to make them sync with switcher mode
  functions.php
  inc/core/builder/class-astra-builder-options.php
  inc/core/class-astra-theme-options.php
  inc/extras.php
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-theme-background-updater.php
  tests/php/static-analysis-stubs/astra-stubs.php
Labels: needs-review
