Repository brainstormforce/astra, pull requests merged in 2021-06, with the labels that each got.

#2809 AST-511 - fix: spacing CSS missing when inline logo and title option is enabled
  inc/class-astra-dynamic-css.php
Labels: ready to merge

#2807 AST-512 - fix: Theme warnings resolved in v3.5.0-beta-1 package
  assets/css/minified/frontend.min-rtl.css
  assets/css/minified/frontend.min.css
  assets/css/minified/main.min-rtl.css
  assets/css/minified/main.min.css
  assets/css/minified/style-flex.min.css
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  assets/css/unminified/frontend-rtl.css
  assets/css/unminified/frontend.css
  assets/css/unminified/main-rtl.css
  assets/css/unminified/main.css
  assets/css/unminified/style-flex-rtl.css
  assets/css/unminified/style-flex.css
  assets/css/unminified/style-rtl.css
  assets/css/unminified/style.css
  changelog.txt
  inc/customizer/configurations/layout/class-astra-site-identity-configs.php
  inc/dynamic-css/comments-flex.php
  inc/dynamic-css/comments.php
  sass/site/primary/_comments.scss
  sass/site/primary/_primary.scss
  searchform.php
Labels: ready to merge

#2446 chore: Changelog amp meta
  changelog.txt
Labels: Stale, dependencies, needs input, ready to merge

#2817 AST-525 - Fix: WooCommerce - Product's Sale bubble appears on the header on scroll due to z-index.
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce.css
  changelog.txt
  sass/site/compatibility/woocommerce/woocommerce-grid.scss
  sass/site/compatibility/woocommerce/woocommerce.scss
Labels: ready to merge

#2672 Global Palette Elementor Compatibility
  inc/assets/css/ast-elementor-editor-dark.css
  inc/assets/css/ast-elementor-editor-rtl.css
  inc/assets/css/ast-elementor-editor.css
  inc/class-astra-dynamic-css.php
  inc/class-astra-global-palette.php
  inc/compatibility/class-astra-elementor.php
  inc/customizer/class-astra-customizer.php
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/color-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/color.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
  inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
  inc/customizer/extend-custom-controls/src/common/astra-color-picker-control.js
  inc/customizer/extend-custom-controls/src/customizer.js
  inc/extras.php
  phpcs.xml.dist
Labels: ready to merge

#2819 AST-526 - refactor: As version_compare fails in beta release comparison added function for it
  README.md
  changelog.txt
  functions.php
  inc/builder/type/header/above-header/dynamic-css/dynamic.css.php
  inc/class-astra-dynamic-css.php
  inc/customizer/configurations/layout/class-astra-site-identity-configs.php
  inc/extras.php
  inc/theme-update/class-astra-theme-background-updater.php
  languages/astra.pot
  readme.txt
  style.css
Labels: ready to merge

#2831 AST-554 Fix: Customizer not working when Gutenberg plugin v10.7.0 and above is active.
  changelog.txt
  inc/customizer/class-astra-customizer.php
Labels: ready to merge

#2832 Build: Release PR Cherry picked fix of Customizer not working when Gutenberg plugin is active.
  README.md
  changelog.txt
  functions.php
  inc/customizer/class-astra-customizer.php
  languages/astra.pot
  package-lock.json
  package.json
  readme.txt
  style.css
Labels: Release PR checklist, ready to merge

#2813 AST-476 - Fix: Updated string from 'Logo' to 'Site Identity & Logo' to avoid confusion regarding missing 'Site Identity' option from new header builder.
  inc/core/builder/class-astra-builder-helper.php
Labels: ready to merge

#2812 AST-479 - fix: Cart Icon not working with Sticky Header after enabling the option "Hide when scrolling down" on mobile devices.
  assets/js/minified/mobile-cart.min.js
  assets/js/unminified/mobile-cart.js
  changelog.txt
Labels: ready to merge

#2830 AST-281 - fix: Secondary menu not expendable on mobile when outside of Off Canvas
  assets/js/minified/frontend.min.js
  assets/js/unminified/frontend.js
  changelog.txt
Labels: ready to merge

#2783 AST-408 - refactor: Added is header-footer builder active check in Footer builder class to avoid future fatal errors
  inc/builder/class-astra-builder-loader.php
  inc/builder/markup/class-astra-builder-footer.php
Labels: needs-review

#2782 AST-396 - fix: Max-width: 100%; CSS enlarges logo size in old header layout
  assets/css/minified/style-flex.min.css
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  assets/css/unminified/style-flex-rtl.css
  assets/css/unminified/style-flex.css
  assets/css/unminified/style-rtl.css
  assets/css/unminified/style.css
  assets/js/minified/customizer-preview.min.js
  assets/js/unminified/customizer-preview.js
  changelog.txt
  functions.php
  inc/class-astra-dynamic-css.php
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-theme-background-updater.php
  sass/site/header/_header-layouts.scss
Labels: needs-review

#2836 AST-556 - fix: Site title and tagline context issue for new HF builder
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
  inc/customizer/extend-custom-controls/src/common/responsive-helper.js
Labels: ready to merge

#2828 AST-448 - fix: Multiselect close icon not showing on selected items.
  changelog.txt
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls-plain.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/custom-controls/typography/selectWoo.js
Labels: ready to merge

#2840 AST-526 - refactor: Updated beta version check to stable 3.5.0 version
  functions.php
  inc/builder/type/header/above-header/dynamic-css/dynamic.css.php
  inc/class-astra-dynamic-css.php
  inc/customizer/configurations/layout/class-astra-site-identity-configs.php
  inc/extras.php
Labels: ready to merge

#2839 Changelog v3.5.0
  changelog.txt
Labels: ready to merge

#2842 Build: Release PR v3.5.0
  README.md
  changelog.txt
  inc/builder/type/class-astra-builder-base-dynamic-css.php
  inc/builder/type/footer/menu/dynamic-css/dynamic.css.php
  inc/builder/type/header/menu/dynamic-css/dynamic.css.php
  inc/builder/type/header/search/dynamic-css/dynamic.css.php
  inc/compatibility/class-astra-beaver-builder.php
  inc/compatibility/class-astra-visual-composer.php
  inc/core/class-astra-enqueue-scripts.php
  inc/customizer/configurations/layout/class-astra-site-identity-configs.php
  inc/dynamic-css/astra-icons.php
  inc/dynamic-css/custom-menu-old-header.php
  inc/dynamic-css/inline-on-mobile.php
  inc/extras.php
  inc/modules/related-posts/class-astra-related-posts-loader.php
  inc/modules/related-posts/class-astra-related-posts-markup.php
  inc/modules/related-posts/class-astra-related-posts.php
  inc/modules/related-posts/css/static-css.php
  inc/modules/related-posts/customizer/class-astra-related-posts-configs.php
  inc/theme-update/astra-update-functions.php
  languages/astra.pot
  package-lock.json
  package.json
  readme.txt
  style.css
Labels: Release PR checklist, ready to merge

#2843 Release candidate v3.5.0
  README.md
  assets/css/minified/frontend.min-rtl.css
  assets/css/minified/frontend.min.css
  assets/css/minified/main.min-rtl.css
  assets/css/minified/main.min.css
  assets/css/minified/style-flex.min.css
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  assets/css/unminified/frontend-rtl.css
  assets/css/unminified/frontend.css
  assets/css/unminified/main-rtl.css
  assets/css/unminified/main.css
  assets/css/unminified/style-flex-rtl.css
  assets/css/unminified/style-flex.css
  assets/css/unminified/style-rtl.css
  assets/css/unminified/style.css
  changelog.txt
  functions.php
  inc/builder/type/class-astra-builder-base-dynamic-css.php
  inc/builder/type/footer/menu/dynamic-css/dynamic.css.php
  inc/builder/type/header/above-header/dynamic-css/dynamic.css.php
  inc/builder/type/header/menu/dynamic-css/dynamic.css.php
  inc/builder/type/header/search/dynamic-css/dynamic.css.php
  inc/class-astra-dynamic-css.php
  inc/compatibility/class-astra-beaver-builder.php
  inc/compatibility/class-astra-visual-composer.php
  inc/core/class-astra-enqueue-scripts.php
  inc/customizer/configurations/layout/class-astra-site-identity-configs.php
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
  inc/customizer/extend-custom-controls/src/common/responsive-helper.js
  inc/dynamic-css/astra-icons.php
  inc/dynamic-css/custom-menu-old-header.php
  inc/dynamic-css/inline-on-mobile.php
  inc/extras.php
  inc/modules/related-posts/class-astra-related-posts-loader.php
  inc/modules/related-posts/class-astra-related-posts-markup.php
  inc/modules/related-posts/class-astra-related-posts.php
  inc/modules/related-posts/css/static-css.php
  inc/modules/related-posts/customizer/class-astra-related-posts-configs.php
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-theme-background-updater.php
  languages/astra.pot
  package-lock.json
  package.json
  readme.txt
  sass/site/_frontend.scss
  sass/site/_main.scss
  sass/site/_site-flex.scss
  sass/site/_site.scss
  screenshot.jpg
  style.css
Labels: ready to merge

#2848 AST-492 - imrpv: Changed customizer submenu control title from "Container Animations" to "Submenu Animation"
  changelog.txt
  inc/customizer/configurations/builder/header/class-astra-header-menu-component-configs.php
  inc/customizer/configurations/layout/class-astra-header-layout-configs.php
Labels: ready to merge

#2780 AST-499 - feat: added SVG logo height option to resolve the CLS issue
  inc/addons/transparent-header/classes/dynamic-css/dynamic.css.php
  inc/class-astra-dynamic-css.php
  inc/core/builder/class-astra-builder-options.php
  inc/customizer/configurations/layout/class-astra-site-identity-configs.php
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
  inc/customizer/extend-custom-controls/src/control-customizer.js
Labels: ready to merge

#2835 AST-534 - fix: product search widget button not align on other than shop and single product page
  changelog.txt
  inc/compatibility/woocommerce/class-astra-woocommerce.php
Labels: ready to merge

#2847 AST-495 - imprv: Changed submenu container animation option name from Default to None
  changelog.txt
  inc/customizer/configurations/builder/header/class-astra-header-menu-component-configs.php
  inc/customizer/configurations/layout/class-astra-header-layout-configs.php
Labels: ready to merge

#2814 AST-176 - feat: Introducing new self hosted Google fonts feature in Astra
  README.md
  functions.php
  inc/core/class-astra-theme-options.php
  inc/customizer/class-astra-customizer-register-sections-panels.php
  inc/customizer/class-astra-customizer.php
  inc/customizer/class-astra-fonts.php
  inc/customizer/configurations/performance/class-astra-performance-configs.php
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls-plain.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/custom-controls/typography/selectWoo.js
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
  inc/customizer/extend-custom-controls/package-lock.json
  inc/customizer/extend-custom-controls/src/customizer.js
  inc/extras.php
  inc/lib/webfont/class-astra-webfont-loader.php
  readme.txt
  style.css
Labels: ready to merge

#2795 AST-449 - improvement: Added heading font-weight support to widget title & added all font props support in GB editor as well
  changelog.txt
  inc/addons/heading-colors/assets/js/minified/customizer-preview.min.js
  inc/addons/heading-colors/assets/js/unminified/customizer-preview.js
  inc/assets/css/block-editor-styles-rtl.css
  inc/assets/css/block-editor-styles.css
  inc/class-astra-dynamic-css.php
  inc/core/class-gutenberg-editor-css.php
  inc/customizer/class-astra-customizer.php
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-theme-background-updater.php
  sass/admin/block-editor-styles.scss
Labels: needs-review

#2854 AST-496 - fix: Added transition CSS to site-identity to make shrink sticky layout smoothen
  assets/css/minified/frontend.min-rtl.css
  assets/css/minified/frontend.min.css
  assets/css/minified/main.min-rtl.css
  assets/css/minified/main.min.css
  assets/css/minified/style-flex.min.css
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  assets/css/unminified/frontend-rtl.css
  assets/css/unminified/frontend.css
  assets/css/unminified/main-rtl.css
  assets/css/unminified/main.css
  assets/css/unminified/style-flex-rtl.css
  assets/css/unminified/style-flex.css
  assets/css/unminified/style-rtl.css
  assets/css/unminified/style.css
  changelog.txt
  sass/site/builder/_header.scss
  sass/site/header/_header-layouts.scss
Labels: needs-review

#2857 chore: Corrected text-domain for astra
  inc/customizer/configurations/performance/class-astra-performance-configs.php
Labels: ready to merge

#2850 AST-490 - fix: Removed default border bottom for transparent header and make it as 0 value.
  changelog.txt
  inc/core/builder/class-astra-builder-options.php
  inc/extras.php
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-theme-background-updater.php
Labels: ready to merge

#2859 chore: Updated changelog sequence
  changelog.txt
Labels: needs-review

#2862 AST-574 - fix: cross button alignment on select2
  inc/customizer/custom-controls/typography/selectWoo.css
Labels: ready to merge

#2864 AST-576 - refactor: Updated assets images links for Astra screenshot
  README.md
  readme.txt
Labels: ready to merge

#2861 AST-567 - fix: Two search buttons visible on results page when Astra SVGs enabled
  assets/css/minified/editor-style.min-rtl.css
  assets/css/minified/editor-style.min.css
  assets/css/minified/frontend.min-rtl.css
  assets/css/minified/frontend.min.css
  assets/css/minified/main.min-rtl.css
  assets/css/minified/main.min.css
  assets/css/minified/style-flex.min.css
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  assets/css/unminified/editor-style-rtl.css
  assets/css/unminified/editor-style.css
  assets/css/unminified/frontend-rtl.css
  assets/css/unminified/frontend.css
  assets/css/unminified/main-rtl.css
  assets/css/unminified/main.css
  assets/css/unminified/style-flex-rtl.css
  assets/css/unminified/style-flex.css
  assets/css/unminified/style-rtl.css
  assets/css/unminified/style.css
  changelog.txt
  sass/_normalize-frontend.scss
  sass/_normalize.scss
  searchform.php
Labels: ready to merge

#2849 AST-537 - fix: Menu dropdown icon showing at incorrect position in RTL language setup
  changelog.txt
  inc/builder/type/header/off-canvas/dynamic-css/dynamic.css.php
  inc/class-astra-dynamic-css.php
Labels: ready to merge

#2860 Build: Release PR v3.6.0
  README.md
  changelog.txt
  inc/class-astra-dynamic-css.php
  inc/customizer/class-astra-customizer-register-sections-panels.php
  inc/customizer/class-astra-customizer.php
  inc/customizer/class-astra-fonts.php
  inc/customizer/configurations/performance/class-astra-performance-configs.php
  inc/extras.php
  inc/lib/webfont/class-astra-webfont-loader.php
  inc/theme-update/astra-update-functions.php
  languages/astra.pot
  package-lock.json
  package.json
  readme.txt
  style.css
Labels: Release PR checklist, needs-review

#2855 AST-563 - fix: Previous and Next pagination button is not aligned in mobile view.
  changelog.txt
  inc/dynamic-css/pagination.php
Labels: ready to merge

#2877 AST-585 - Added cache clearing batch function for v3.6.1 in Astra
  changelog.txt
  functions.php
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-theme-background-updater.php
Labels: ready to merge

#2883 Build: Release PR v3.6.1
  README.md
  inc/theme-update/astra-update-functions.php
  languages/astra.pot
  package-lock.json
  package.json
  readme.txt
  style.css
Labels: Release PR checklist, ready to merge

#2875 AST-580 - Fixed warnings in theme-check for search-role and compatibility with get_search_form function
  changelog.txt
  inc/core/common-functions.php
  inc/markup-extras.php
  searchform.php
Labels: ready to merge

#2885 Build: Release PR chore: Updated grunt bump version after mergin PR #2875
  languages/astra.pot
  package-lock.json
  searchform.php
Labels: Release PR checklist, ready to merge

#2884 Release candidate - v3.6.1
  README.md
  changelog.txt
  functions.php
  inc/core/common-functions.php
  inc/markup-extras.php
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-theme-background-updater.php
  languages/astra.pot
  package-lock.json
  package.json
  readme.txt
  searchform.php
  style.css
Labels: ready to merge

#2889 Setup psalm for static analysis
  .github/workflows/code-analysis.yml
  .github/workflows/phpcs.yml
  Gruntfile.js
  composer.json
  composer.lock
  inc/compatibility/edd/class-astra-edd.php
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  inc/core/builder/class-astra-builder-helper.php
  inc/customizer/class-astra-customizer.php
  inc/theme-update/class-astra-theme-background-updater.php
  package-lock.json
  phpcs.xml.dist
  psalm.xml
  tests/php/psalm-baseline.xml
  tests/php/static-analysis-stubs/astra-stubs.php
  tests/php/static-analysis-stubs/constants.php
Labels: ready to merge

#2886 use wp-env to setup the local environment
  .github/workflows/auto-cancel.yml
  .github/workflows/bundle-size.yml
  .github/workflows/ci.yml
  .wp-env.json
  docs/development/local-enviornment/readme.md
  package-lock.json
  package.json
Labels: ready to merge

#2890 Merge local environment using wp-env to master
  .github/workflows/auto-cancel.yml
  .github/workflows/bundle-size.yml
  .github/workflows/ci.yml
  .wp-env.json
  docs/development/local-enviornment/readme.md
  package-lock.json
  package.json
Labels: needs-review

#2898 Update npm packages
  package-lock.json
  package.json
Labels: ready to merge

#2903 AST-596 - Individual related post article showing meta markup based on current post filters
  changelog.txt
  inc/modules/related-posts/class-astra-related-posts-markup.php
Labels: ready to merge

#2902 AST-604 - 'Preload Local Fonts' option affects on height of Gutenberg Cover edit block
  changelog.txt
  inc/customizer/class-astra-fonts.php
Labels: ready to merge

#2904 Build: Release PR v3.6.2
  README.md
  functions.php
  languages/astra.pot
  package.json
  readme.txt
  style.css
Labels: Release PR checklist, ready to merge

#2906 v3.6.2 - release
  README.md
  changelog.txt
  functions.php
  inc/customizer/class-astra-fonts.php
  inc/modules/related-posts/class-astra-related-posts-markup.php
  languages/astra.pot
  package.json
  readme.txt
  style.css
Labels: ready to merge

#2911 Run Theme Check in GitHub Actions
  .github/workflows/bundle-size.yml
  .github/workflows/code-analysis.yml
  .github/workflows/theme-check.yml
  .wp-env.json
  Gruntfile.js
  bin/local-env/.env.wp
  bin/local-env/docker-compose.yml
  bin/local-env/includes.sh
  bin/local-env/install-composer.sh
  bin/local-env/install-node-nvm.sh
  bin/local-env/install-wordpress.sh
  bin/local-env/launch-containers.sh
  bin/local-env/start.sh
  bin/local-env/stop.sh
  package.json
Labels: ready to merge

#2888 E2E tests for Astra
  .eslintrc
  .github/workflows/code-analysis.yml
  .github/workflows/tests.yml
  .gitignore
  .wp-env.json
  Gruntfile.js
  bin/scripts/pre-e2e-tests.sh
  changelog.txt
  composer.json
  inc/core/class-gutenberg-editor-css.php
  package-lock.json
  package.json
  phpcs.xml.dist
  tests/e2e/config/bootstrap.js
  tests/e2e/config/expect-extensions.js
  tests/e2e/e2e-plugin/loader.php
  tests/e2e/e2e-plugin/rest-api/namespace.php
  tests/e2e/jest.config.js
  tests/e2e/specs/block-editor/typography.test.js
  tests/e2e/specs/customizer/global/typography.test.js
  tests/e2e/specs/hello.test.js
  tests/e2e/utils/post.js
  tests/e2e/utils/set-customize.js
Labels: ready to merge

#2909 AST-253 - Improvement: Rendered Addon dependent toggle code conditionally and removed unwanted code.
  assets/js/minified/frontend-pro.min.js
  assets/js/minified/frontend.min.js
  assets/js/unminified/frontend-pro.js
  assets/js/unminified/frontend.js
  changelog.txt
  inc/core/class-astra-enqueue-scripts.php
Labels: ready to merge

#2907 AST-412 - Footer widget margin-right space not working
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min-rtl.css
  assets/css/minified/frontend.min-rtl.css
  assets/css/minified/frontend.min.css
  assets/css/minified/main.min-rtl.css
  assets/css/minified/main.min.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-rtl.css
  assets/css/unminified/frontend-rtl.css
  assets/css/unminified/frontend.css
  assets/css/unminified/main-rtl.css
  assets/css/unminified/main.css
  changelog.txt
  functions.php
  inc/builder/type/base/dynamic-css/widget/class-astra-widget-component-dynamic-css.php
  inc/builder/type/footer/widget/dynamic-css/dynamic.css.php
  inc/class-astra-dynamic-css.php
  inc/extras.php
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-theme-background-updater.php
  sass/site/builder/_header.scss
Labels: ready to merge
