Repository brainstormforce/astra, pull requests merged in 2021-04, with the labels that each got.

#2507 AST-78 - fix: Extra divider appearing before sticky menu colors in Primary Menu Element
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/color-group-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/color-group.css
  inc/customizer/custom-controls/assets/css/unminified/color-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/color.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/assets/css/unminified/divider-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/divider.css
  inc/customizer/custom-controls/color-group/color-group.scss
Labels: ready to merge

#2566 AST-266 - fix: Menu clone - SVG Icons missing when menu is changed from cloned menu to some other menu.
  inc/extras.php
Labels: needs-review

#2493 AST-98 - fix: Spacing jerk issue getting in customizer with adjusting Stack on & Icon Spacing options in Footer Social element
  assets/css/minified/frontend.min-rtl.css
  assets/css/minified/frontend.min.css
  assets/css/minified/main.min-rtl.css
  assets/css/minified/main.min.css
  assets/css/unminified/frontend-rtl.css
  assets/css/unminified/frontend.css
  assets/css/unminified/main-rtl.css
  assets/css/unminified/main.css
  changelog.txt
  inc/builder/type/base/assets/js/customizer-preview.js
  inc/builder/type/base/dynamic-css/social/class-astra-social-component-dynamic-css.php
  sass/site/builder/_header.scss
Labels: ready to merge

#2544 AST-87 - fix: Transparent header Normal Colors not working for Transparent header if not colors set from Transparent Header settings.
  changelog.txt
  inc/class-astra-dynamic-css.php
Labels: ready to merge

#2558 AST-117 - fix: Search - Search Box opens & get's closed automatically on click of Search Icon in Slide search style on Mobile devices.
  assets/js/minified/frontend.min.js
  assets/js/unminified/frontend.js
  changelog.txt
Labels: ready to merge

#2536 chore: v3.3.0 release
  README.md
  assets/fonts/google-fonts.json
  changelog.txt
  functions.php
  inc/class-astra-dynamic-css.php
  inc/compatibility/learndash/class-astra-learndash.php
  inc/compatibility/lifterlms/class-astra-lifterlms.php
  inc/core/builder/class-astra-builder-helper.php
  inc/core/class-astra-icons.php
  inc/core/markup/class-astra-markup.php
  inc/dynamic-css/container-layouts.php
  inc/dynamic-css/pagination.php
  inc/extras.php
  inc/google-fonts.php
  inc/theme-update/astra-update-functions.php
  languages/astra.pot
  package-lock.json
  package.json
  readme.txt
  searchform.php
  style.css
Labels: needs-review

#2530 AST-44 - refactor: Block Editor & GB layout improvements
  inc/class-astra-dynamic-css.php
  inc/core/class-gutenberg-editor-css.php
  inc/customizer/class-astra-customizer.php
Labels: ready to merge

#2514 AST-11 - fix: Container Width option should only visible if Site Layout set to Full WIdth & slider range unit has left margin space
  changelog.txt
  inc/customizer/configurations/layout/class-astra-site-layout-configs.php
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/assets/css/unminified/responsive-slider-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/responsive-slider.css
Labels: needs-review

#2573 AST-276 Check size of the dynamic CSS
  .github/workflows/auto-cancel.yml
  .github/workflows/simple-size-check.yml
  .gitignore
  Gruntfile.js
  bin/scripts/dynamic-css-to-file.js
  package-lock.json
  package.json
Labels: ready to merge

#2549 AST-290 - Automatic deployments to dev branches
  .github/workflows/build-and-deploy.yml
  Gruntfile.js
  contributing.md
  docs/development/development-workflow.md
  docs/development/index.md
  package-lock.json
Labels: ready to merge

#2564 AST-270 - Local enviornment for e2e testing
  .github/workflows/auto-cancel.yml
  .github/workflows/simple-size-check.yml
  .gitignore
  Gruntfile.js
  bin/local-env/.env.wp
  bin/local-env/docker-compose.yml
  bin/local-env/includes.sh
  bin/local-env/install-composer.sh
  bin/local-env/install-node-nvm.sh
  bin/local-env/install-wordpress.sh
  bin/local-env/launch-containers.sh
  bin/local-env/start.sh
  bin/local-env/stop.sh
  bin/scripts/dynamic-css-to-file.js
  docs/development/local-enviornment/readme.md
  package-lock.json
  package.json
Labels: needs-review

#2578 Merge dev workflow changes to dev branch
  .github/workflows/auto-cancel.yml
  .github/workflows/build-and-deploy.yml
  .github/workflows/simple-size-check.yml
  .gitignore
  Gruntfile.js
  bin/local-env/.env.wp
  bin/local-env/docker-compose.yml
  bin/local-env/includes.sh
  bin/local-env/install-composer.sh
  bin/local-env/install-node-nvm.sh
  bin/local-env/install-wordpress.sh
  bin/local-env/launch-containers.sh
  bin/local-env/start.sh
  bin/local-env/stop.sh
  bin/scripts/dynamic-css-to-file.js
  contributing.md
  docs/development/development-workflow.md
  docs/development/index.md
  docs/development/local-enviornment/readme.md
  package-lock.json
  package.json
Labels: ready to merge

#2579 Merge development workflows to the master branch
  .github/workflows/auto-cancel.yml
  .github/workflows/build-and-deploy.yml
  .github/workflows/simple-size-check.yml
  .gitignore
  Gruntfile.js
  bin/local-env/.env.wp
  bin/local-env/docker-compose.yml
  bin/local-env/includes.sh
  bin/local-env/install-composer.sh
  bin/local-env/install-node-nvm.sh
  bin/local-env/install-wordpress.sh
  bin/local-env/launch-containers.sh
  bin/local-env/start.sh
  bin/local-env/stop.sh
  bin/scripts/dynamic-css-to-file.js
  contributing.md
  docs/development/development-workflow.md
  docs/development/index.md
  docs/development/local-enviornment/readme.md
  package-lock.json
  package.json
Labels: ready to merge

#2524 AST-109 - fix: Sidebar border visible directly in boxed layout which breaks UI on Blog
  inc/class-astra-dynamic-css.php
Labels: ready to merge

#2331 AST-110 - Change submenu animation default setting from fade to default.
  inc/core/builder/class-astra-builder-options.php
  inc/core/class-astra-enqueue-scripts.php
  inc/core/class-astra-theme-options.php
Labels: ready to merge

#2561 AST-26 - refactor: remove Popup from Mobile menu by default and make it Dropdown
  assets/css/minified/frontend.min-rtl.css
  assets/css/minified/frontend.min.css
  assets/css/minified/main.min-rtl.css
  assets/css/minified/main.min.css
  assets/css/minified/style-flex.min.css
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  assets/css/unminified/frontend-rtl.css
  assets/css/unminified/frontend.css
  assets/css/unminified/main-rtl.css
  assets/css/unminified/main.css
  assets/css/unminified/style-flex-rtl.css
  assets/css/unminified/style-flex.css
  assets/css/unminified/style-rtl.css
  assets/css/unminified/style.css
  inc/builder/type/header/off-canvas/dynamic-css/dynamic.css.php
  inc/core/builder/class-astra-builder-options.php
  sass/site/builder/_header.scss
  sass/site/navigation/_navigation.scss
Labels: ready to merge

#2581 AST-102 - fix: Deprecated the Cart Style None & added Backward compatibilty to it.
  changelog.txt
  functions.php
  inc/core/builder/class-astra-builder-options.php
  inc/customizer/configurations/builder/header/class-astra-customizer-edd-cart-configs.php
  inc/customizer/configurations/builder/header/class-astra-customizer-woo-cart-configs.php
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-theme-background-updater.php
Labels: ready to merge

#2567 AST-244 - fix: Context Switch does not work if there are no elements in Primary Header for both Desktop & Mobile.
  assets/js/minified/frontend.min.js
  assets/js/unminified/frontend.js
  changelog.txt
Labels: ready to merge

#2562 AST-255 - imprv: Improved the Footer Grid CSS for different layouts.
  assets/css/minified/frontend.min-rtl.css
  assets/css/minified/frontend.min.css
  assets/css/minified/main.min-rtl.css
  assets/css/minified/main.min.css
  assets/css/unminified/frontend-rtl.css
  assets/css/unminified/frontend.css
  assets/css/unminified/main-rtl.css
  assets/css/unminified/main.css
  inc/builder/type/class-astra-builder-base-dynamic-css.php
  inc/builder/type/footer/above-footer/dynamic-css/dynamic.css.php
  inc/builder/type/footer/below-footer/dynamic-css/dynamic.css.php
  inc/builder/type/footer/primary-footer/dynamic-css/dynamic.css.php
  inc/core/builder/class-astra-builder-helper.php
  sass/site/builder/_header.scss
Labels: ready to merge

#2592 v3.3.0 release into dev
  changelog.txt
  inc/extras.php
  languages/astra.pot
  package.json
Labels: needs-review

#2593 run on all pull_request events
  .github/workflows/update-pull-request.yml
Labels: update-branch

#2605 v3.3.1 release
  README.md
  changelog.txt
  functions.php
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  inc/core/builder/class-astra-builder-helper.php
  languages/astra.pot
  package.json
  readme.txt
  style.css
Labels: ready to merge

#2601 AST-330 - fix: Submenu top offset style CSS missing in _header-builder-main.css
  assets/css/minified/frontend.min-rtl.css
  assets/css/minified/frontend.min.css
  assets/css/minified/main.min-rtl.css
  assets/css/minified/main.min.css
  assets/css/unminified/frontend-rtl.css
  assets/css/unminified/frontend.css
  assets/css/unminified/main-rtl.css
  assets/css/unminified/main.css
  changelog.txt
  sass/site/header/_header-builder-main.scss
Labels: ready to merge

#2599 AST-334 - fix: blog archive layout-1 and layout-2 are not working for old users.
  changelog.txt
  inc/core/markup/class-astra-markup.php
Labels: ready to merge

#2607 AST-342 - fix: transparent header disappear if we have widget-2 in it
  changelog.txt
  template-parts/header/builder/components.php
Labels: ready to merge

#2609 v3.3.2 release
  README.md
  changelog.txt
  functions.php
  languages/astra.pot
  package-lock.json
  package.json
  readme.txt
  style.css
Labels: ready to merge

#2520 GCP-1 Global color palette
  inc/core/builder/class-astra-builder-options.php
  inc/customizer/configurations/colors-background/class-astra-body-colors-configs.php
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/color-palette-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/color-palette.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
  inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
  inc/customizer/extend-custom-controls/src/color-palette/control.js
  inc/customizer/extend-custom-controls/src/common/astra-common-functions.js
  inc/customizer/extend-custom-controls/src/index.js
  inc/customizer/extend-custom-controls/src/settings-group/control.js
Labels: ready to merge

#2616 Add changes back which were removed accidently when merging master to next-release
  .github/workflows/auto-cancel.yml
  .github/workflows/simple-size-check.yml
  assets/js/minified/frontend.min.js
  assets/js/unminified/frontend.js
Labels: ready to merge

#2568 GCP-4 Display Global color palette in all color option controls
  inc/core/builder/class-astra-builder-options.php
  inc/core/class-astra-theme-options.php
  inc/customizer/configurations/colors-background/class-astra-body-colors-configs.php
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/color-palette-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/color-palette.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/custom-controls/class-astra-customizer-control-base.php
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
  inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
  inc/customizer/extend-custom-controls/src/color-palette/control.js
  inc/customizer/extend-custom-controls/src/common/astra-color-picker-control.js
  inc/customizer/extend-custom-controls/src/common/astra-common-functions.js
  inc/customizer/extend-custom-controls/src/control-customizer.js
Labels: ready to merge

#2624 AST-354 - fix: RTL- woo shop page 2 grid layout not work for existing user
  changelog.txt
  inc/compatibility/woocommerce/class-astra-woocommerce.php
Labels: ready to merge

#2623 AST-352 - fix: Scroll does not work in Off-Canvas.
  changelog.txt
  inc/builder/type/header/off-canvas/dynamic-css/dynamic.css.php
Labels: ready to merge

#2615 AST-307 - feat: Added ast-selector control support in setting-group as sub-control
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
  inc/customizer/extend-custom-controls/src/settings-group/control.js
Labels: ready to merge

#2618 AST-326 - refactor: Added container layout support for Related Posts as well just like comment section
  inc/class-astra-dynamic-css.php
Labels: needs-review

#2619 AST-122 - refactor: Font typo sub-controls set with proper sequential pattern
  inc/customizer/configurations/builder/base/class-astra-button-component-configs.php
  inc/customizer/configurations/builder/class-astra-builder-base-configuration.php
  inc/customizer/configurations/typography/class-astra-header-typo-configs.php
Labels: ready to merge

#2632 AST-362 - fix: Border directly visible to last header bar though it's empty or 0 in Transparent header settings
  inc/addons/transparent-header/assets/js/minified/customizer-preview.min.js
  inc/addons/transparent-header/assets/js/unminified/customizer-preview.js
  inc/addons/transparent-header/classes/dynamic-css/dynamic.css.php
Labels: ready to merge

#2637 AST-375 - refactor: Added context dependency for Title-meta & color settings based on post structure
  inc/customizer/configurations/layout/class-astra-related-posts-configs.php
Labels: needs-review

#2640 AST-377 - fix: Spacing make equal to 1em in between all possible combinations in Related Posts
  inc/class-astra-dynamic-css.php
Labels: needs-review

#2638 AST-376 - improvement: Added default line-height & margin space for post title in Related Posts
  inc/class-astra-dynamic-css.php
  inc/core/class-astra-theme-options.php
  inc/customizer/configurations/layout/class-astra-related-posts-configs.php
Labels: needs-review

#2639 AST-372 - fix: Full width Stretched layout width compatibility with Related Posts section
  inc/class-astra-dynamic-css.php
Labels: needs-review

#2645 AST-379 - fix: Reposinsive control's label triggers window in responsive mode in customizer
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
  inc/customizer/extend-custom-controls/src/responsive/responsive-component.js
Labels: needs-review

#2646 AST-378 - fix: Related Posts QA reported improvements & fixes
  assets/css/minified/frontend.min-rtl.css
  assets/css/minified/frontend.min.css
  assets/css/minified/main.min-rtl.css
  assets/css/minified/main.min.css
  assets/css/minified/style-flex.min.css
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  assets/css/unminified/frontend-rtl.css
  assets/css/unminified/frontend.css
  assets/css/unminified/main-rtl.css
  assets/css/unminified/main.css
  assets/css/unminified/style-flex-rtl.css
  assets/css/unminified/style-flex.css
  assets/css/unminified/style-rtl.css
  assets/css/unminified/style.css
  assets/js/minified/customizer-preview.min.js
  assets/js/unminified/customizer-preview.js
  inc/class-astra-dynamic-css.php
  inc/core/class-astra-enqueue-scripts.php
  inc/core/class-astra-theme-options.php
  inc/dynamic-css/related-posts.php
  sass/site/layout/_layout-flex.scss
  sass/site/layout/_layout.scss
Labels: needs-review

#2559 AST-30 - feat: Related Posts on Single Post
  assets/css/minified/frontend.min-rtl.css
  assets/css/minified/frontend.min.css
  assets/css/minified/main.min-rtl.css
  assets/css/minified/main.min.css
  assets/css/minified/style-flex.min.css
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  assets/css/unminified/frontend-rtl.css
  assets/css/unminified/frontend.css
  assets/css/unminified/main-rtl.css
  assets/css/unminified/main.css
  assets/css/unminified/style-flex-rtl.css
  assets/css/unminified/style-flex.css
  assets/css/unminified/style-rtl.css
  assets/css/unminified/style.css
  assets/js/minified/customizer-preview.min.js
  assets/js/unminified/customizer-preview.js
  functions.php
  inc/blog/single-blog.php
  inc/builder/type/footer/below-footer/dynamic-css/dynamic.css.php
  inc/builder/type/footer/primary-footer/dynamic-css/dynamic.css.php
  inc/builder/type/header/off-canvas/dynamic-css/dynamic.css.php
  inc/class-astra-dynamic-css.php
  inc/core/builder/class-astra-builder-options.php
  inc/core/class-astra-enqueue-scripts.php
  inc/core/class-astra-theme-options.php
  inc/customizer/class-astra-customizer.php
  inc/customizer/configurations/layout/class-astra-blog-single-layout-configs.php
  inc/customizer/configurations/layout/class-astra-related-posts-configs.php
  inc/customizer/configurations/typography/class-astra-single-typo-configs.php
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/color-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/color.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/assets/css/unminified/settings-group-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/settings-group.css
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
  inc/customizer/extend-custom-controls/src/selector/selector-component.js
  inc/customizer/extend-custom-controls/src/settings-group/control.js
  inc/extras.php
  inc/modules/related-posts/dynamic-css/related-posts.php
  inc/modules/related-posts/related-posts.php
  package-lock.json
  sass/site/builder/_header.scss
  sass/site/layout/_layout-flex.scss
  sass/site/layout/_layout.scss
Labels: ready to merge

#2653 AST-383 - fix: Elementor archive page layout issue
  changelog.txt
  inc/compatibility/class-astra-elementor.php
Labels: ready to merge

#2652 chore: Changelog & pot file updated with dynamic-css file name
  changelog.txt
  inc/class-astra-dynamic-css.php
  inc/modules/related-posts/dynamic-css/dynamic-css.php
  inc/modules/related-posts/related-posts.php
  languages/astra.pot
Labels: needs-review

#2654 AST-384 - fix: Elementor editor issue while using responsive mode
  assets/js/minified/frontend.min.js
  assets/js/unminified/frontend.js
  changelog.txt
Labels: ready to merge

#2655 v3.3.3 Release
  README.md
  assets/fonts/google-fonts.json
  functions.php
  inc/google-fonts.php
  languages/astra.pot
  package-lock.json
  package.json
  readme.txt
  style.css
Labels: ready to merge

#2659 AST-387 - fix: Before icon content CSS issue in AMP version of Astra
  inc/compatibility/class-astra-amp.php
Labels: needs-review

#2665 AST-399 - fix: Lifter LMS section missing in customizer because file require code was missing from v3.0.0
  inc/compatibility/lifterlms/class-astra-lifterlms.php
  inc/compatibility/lifterlms/customizer/class-astra-liferlms-section-configs.php
  inc/compatibility/lifterlms/customizer/sections/layout/class-astra-lifter-general-configs.php
Labels: needs-review

#2663 AST-74 - refactor: Updated priorities of control in order to maintain correct sequence in customizer
  changelog.txt
  inc/customizer/configurations/layout/class-astra-related-posts-configs.php
  inc/customizer/configurations/typography/class-astra-single-typo-configs.php
Labels: needs-review

#2657 refactor: WP_Query corrected if current post is one of the post from loop & which reduces post count by 1
  assets/js/minified/customizer-preview.min.js
  assets/js/unminified/customizer-preview.js
  inc/customizer/configurations/layout/class-astra-related-posts-configs.php
  inc/modules/related-posts/related-posts.php
Labels: needs-review

#2621 Modified data format for palette option for single palette
  functions.php
  inc/class-astra-dynamic-css.php
  inc/class-astra-global-palette.php
  inc/compatibility/class-astra-elementor.php
  inc/core/builder/class-astra-builder-options.php
  inc/core/class-astra-theme-options.php
  inc/core/class-gutenberg-editor-css.php
  inc/core/common-functions.php
  inc/customizer/class-astra-customizer-sanitizes.php
  inc/customizer/class-astra-customizer.php
  inc/customizer/configurations/colors-background/class-astra-body-colors-configs.php
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/color-palette-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/color-palette.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
  inc/customizer/extend-custom-controls/src/color-group/control.js
  inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
  inc/customizer/extend-custom-controls/src/color-palette/control.js
  inc/customizer/extend-custom-controls/src/common/astra-color-picker-control.js
  inc/customizer/extend-custom-controls/src/control-customizer.js
  inc/dynamic-css/global-color-palette.php
Labels: ready to merge

#2628 Build: Release PR
  .github/workflows/release-pr-template.yml
  README.md
  changelog.txt
  functions.php
  inc/builder/type/header/off-canvas/dynamic-css/dynamic.css.php
  inc/class-astra-dynamic-css.php
  inc/compatibility/lifterlms/customizer/class-astra-liferlms-section-configs.php
  inc/core/class-astra-admin-settings.php
  inc/customizer/configurations/layout/class-astra-related-posts-configs.php
  inc/extras.php
  inc/modules/related-posts/dynamic-css/dynamic-css.php
  inc/modules/related-posts/related-posts.php
  inc/theme-update/astra-update-functions.php
  languages/astra.pot
  package-lock.json
  package.json
  readme.txt
  style.css
Labels: Release PR checklist, ready to merge

#2678 AST-411 - fix: Off-canvas - Left flyout style not working.
  changelog.txt
  inc/builder/type/header/off-canvas/dynamic-css/dynamic.css.php
Labels: ready to merge
