Repository brainstormforce/astra, pull requests merged in 2021-08, with the labels that each got.

#3052 AST-731 - Added missing 'astra' textdomain in astra-notices library
  .github/workflows/tests.yml
  inc/lib/astra-notices/class-astra-notices.php
Labels: ready to merge

#3061 AST-738 - Bulk action selection not working when Astra Get Started notice is active
  changelog.txt
  inc/core/class-astra-admin-settings.php
  psalm.xml
  tests/php/psalm-baseline.xml
Labels: ready to merge

#2961 AST-683 - E2E tests site tagline
  tests/e2e/specs/customizer/header-builder/Site-identity/site-tagline.test.js
  tests/e2e/specs/customizer/related-posts/author.name.test.js
  tests/e2e/utils/post.js
Labels: ready to merge

#3064 AST-657 - Added wpml-config file to support WPML translations
  changelog.txt
  wpml-config.xml
Labels: needs-review

#3068 AST-738 - Enqueue script missing for astra-admin-settings which throws console error
  inc/core/class-astra-admin-settings.php
Labels: needs-review

#3069 AST-739 - Offcanvas header's preview is displaying on Legacy widget's preview in customizer of WordPress 5.8.
  changelog.txt
  inc/builder/markup/class-astra-builder-header.php
Labels: ready to merge

#3049 AST-694 - Removing widget design options in WP-5.8 setup
  changelog.txt
  functions.php
  inc/addons/transparent-header/classes/sections/class-astra-customizer-transparent-header-configs.php
  inc/builder/type/base/dynamic-css/widget/class-astra-widget-component-dynamic-css.php
  inc/class-astra-dynamic-css.php
  inc/customizer/configurations/builder/class-astra-builder-base-configuration.php
  inc/extras.php
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-theme-background-updater.php
Labels: needs-review

#3073 AST-634 - Elementor Pro's Header-Footer theme builder layouts does not override theme's Header-Footer builder layouts
  changelog.txt
  inc/compatibility/class-astra-elementor-pro.php
Labels: ready to merge

#3076 AST-753 - Astra old-new builder migration postbox trigger cause JS error due to missing nonce
  inc/core/class-astra-admin-settings.php
Labels: ready to merge

#3088 chore: Cherry picked 3073 PR
  changelog.txt
  inc/compatibility/class-astra-elementor-pro.php
Labels: needs-review

#3083 AST-750 - Return flag corrected which deciding to hide/show widget design options
  inc/extras.php
Labels: ready to merge

#3082 Build: v3.6.8 Release PR
  .github/workflows/build-and-deploy.yml
  .github/workflows/deploy-developer-docs.yml
  .github/workflows/tests.yml
  Gruntfile.js
  README.md
  assets/css/minified/compatibility/lifterlms-flex.min.css
  assets/css/unminified/compatibility/lifterlms-flex-rtl.css
  assets/css/unminified/compatibility/lifterlms-flex.css
  changelog.txt
  composer.lock
  functions.php
  inc/addons/transparent-header/classes/sections/class-astra-customizer-transparent-header-configs.php
  inc/assets/css/ast-builder-customizer-rtl.css
  inc/assets/css/ast-builder-customizer.css
  inc/builder/markup/class-astra-builder-header.php
  inc/builder/type/base/dynamic-css/widget/class-astra-widget-component-dynamic-css.php
  inc/class-astra-dynamic-css.php
  inc/compatibility/class-astra-elementor-pro.php
  inc/core/class-astra-admin-settings.php
  inc/customizer/configurations/builder/class-astra-builder-base-configuration.php
  inc/customizer/extend-custom-controls/package-lock.json
  inc/customizer/extend-custom-controls/package.json
  inc/extras.php
  inc/lib/astra-notices/class-astra-notices.php
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-theme-background-updater.php
  languages/astra.pot
  package-lock.json
  package.json
  psalm.xml
  readme.txt
  sass/site/compatibility/lifterlms-flex.scss
  style.css
  tests/e2e/config/expect-extensions.js
  tests/e2e/specs/customizer/header-builder/Site-identity/site-tagline.test.js
  tests/e2e/specs/customizer/related-posts/author.name.test.js
  tests/e2e/utils/create-new-user.js
  tests/e2e/utils/post.js
  tests/php/psalm-baseline.xml
  tests/php/static-analysis-stubs/astra-stubs.php
  wpml-config.xml
Labels: ready to merge, Release PR checklist

#3090 v3.6.8 - Release candidate
  .github/workflows/build-and-deploy.yml
  .github/workflows/deploy-developer-docs.yml
  .github/workflows/tests.yml
  Gruntfile.js
  README.md
  assets/css/minified/compatibility/lifterlms-flex.min.css
  assets/css/unminified/compatibility/lifterlms-flex-rtl.css
  assets/css/unminified/compatibility/lifterlms-flex.css
  changelog.txt
  composer.lock
  functions.php
  inc/addons/transparent-header/classes/sections/class-astra-customizer-transparent-header-configs.php
  inc/assets/css/ast-builder-customizer-rtl.css
  inc/assets/css/ast-builder-customizer.css
  inc/builder/markup/class-astra-builder-header.php
  inc/builder/type/base/dynamic-css/widget/class-astra-widget-component-dynamic-css.php
  inc/class-astra-dynamic-css.php
  inc/compatibility/class-astra-elementor-pro.php
  inc/core/class-astra-admin-settings.php
  inc/customizer/configurations/builder/class-astra-builder-base-configuration.php
  inc/customizer/extend-custom-controls/package-lock.json
  inc/customizer/extend-custom-controls/package.json
  inc/extras.php
  inc/lib/astra-notices/class-astra-notices.php
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-theme-background-updater.php
  languages/astra.pot
  package-lock.json
  package.json
  psalm.xml
  readme.txt
  sass/site/compatibility/lifterlms-flex.scss
  style.css
  tests/e2e/config/expect-extensions.js
  tests/e2e/specs/customizer/header-builder/Site-identity/site-tagline.test.js
  tests/e2e/specs/customizer/related-posts/author.name.test.js
  tests/e2e/utils/create-new-user.js
  tests/e2e/utils/post.js
  tests/php/psalm-baseline.xml
  tests/php/static-analysis-stubs/astra-stubs.php
  wpml-config.xml
Labels: ready to merge

#3085 AST-582- imprv: Clear asset cache of the theme and addon on every new update of the theme
  changelog.txt
  inc/extras.php
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-theme-background-updater.php
Labels: ready to merge

#3089 AST-682 - Removing underline text-decoration from builder anchor elements to maintain their UI/UX
  changelog.txt
  functions.php
  inc/class-astra-dynamic-css.php
  inc/core/class-gutenberg-editor-css.php
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-theme-background-updater.php
Labels: needs-review

#3011 GCP-34 Typography Presets Feature
  assets/svg/svgs.json
  composer.lock
  functions.php
  inc/addons/breadcrumbs/class-astra-breadcrumb-trail.php
  inc/addons/heading-colors/assets/js/minified/customizer-preview.min.js
  inc/addons/heading-colors/assets/js/unminified/customizer-preview.js
  inc/addons/heading-colors/class-astra-heading-colors-loader.php
  inc/addons/heading-colors/customizer/class-astra-heading-colors-configs.php
  inc/addons/transparent-header/classes/class-astra-ext-transparent-header-markup.php
  inc/addons/transparent-header/classes/sections/class-astra-customizer-transparent-header-configs.php
  inc/class-astra-dynamic-css.php
  inc/core/builder/class-astra-builder-admin.php
  inc/core/class-astra-enqueue-scripts.php
  inc/customizer/class-astra-customizer.php
  inc/customizer/configurations/typography/class-astra-body-typo-configs.php
  inc/customizer/configurations/typography/class-astra-content-typo-configs.php
  inc/customizer/configurations/typography/class-astra-global-typo-configs.php
  inc/customizer/configurations/typography/class-astra-headings-typo-configs.php
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/assets/css/unminified/font-presets-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/font-presets.css
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls-plain.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/custom-controls/typography/typography.js
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
  inc/customizer/extend-custom-controls/package-lock.json
  inc/customizer/extend-custom-controls/package.json
  inc/customizer/extend-custom-controls/src/ast-font-family/ast-font-family.js
  inc/customizer/extend-custom-controls/src/ast-font-weight/control.js
  inc/customizer/extend-custom-controls/src/customizer.js
  inc/customizer/extend-custom-controls/src/index.js
  inc/customizer/extend-custom-controls/src/responsive-slider/responsive-slider-component.js
  inc/customizer/extend-custom-controls/src/responsive/responsive-component.js
  inc/customizer/extend-custom-controls/src/slider/slider-component.js
  inc/customizer/extend-custom-controls/src/typography-presets/control.js
  inc/customizer/extend-custom-controls/src/typography-presets/typo-presets-component.js
  inc/extras.php
  inc/markup-extras.php
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-pb-compatibility.php
  inc/theme-update/class-astra-theme-background-updater.php
  inc/theme-update/class-astra-theme-update.php
  package-lock.json
  package.json
  psalm.xml
  style.css
  tests/php/static-analysis-stubs/astra-stubs.php
Labels: ready to merge

#3105 Gutenberg nightly auto installed from wp-env
  .wp-env.json
  bin/scripts/pre-e2e-tests.sh
  tests/e2e/config/bootstrap.js
Labels: ready to merge

#3106 use separate wp-env for theme-check and e2e tests
  .github/.wp-env-themecheck.json
  .github/workflows/theme-check.yml
  .wp-env.json
  package.json
Labels: ready to merge

#3100 AST-583 - fix: Woo cart products count is overlapping on the submenu section
  changelog.txt
  inc/class-astra-dynamic-css.php
Labels: ready to merge

#3104 AST-794 - fix: desktop logo width is applying for a moment on mobile device
  changelog.txt
  inc/class-astra-dynamic-css.php
Labels: ready to merge

#3114 refactor: Button border radius preview updated for instant reflections
  assets/js/minified/customizer-preview.min.js
  assets/js/unminified/customizer-preview.js
  inc/class-astra-dynamic-css.php
  inc/customizer/configurations/buttons/class-astra-customizer-button-configs.php
  inc/customizer/configurations/typography/class-astra-body-typo-configs.php
  inc/customizer/configurations/typography/class-astra-headings-typo-configs.php
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
Labels: ready to merge

#3125 AST-601 fix: An issue with the DropDown target to link not working
  assets/js/minified/frontend.min.js
  assets/js/unminified/frontend.js
  changelog.txt
Labels: ready to merge

#2932 AST-599 - Added responsive or single colors class support for adding compatibility CSS
  changelog.txt
  inc/addons/transparent-header/assets/js/minified/customizer-preview.min.js
  inc/addons/transparent-header/assets/js/unminified/customizer-preview.js
  inc/addons/transparent-header/classes/sections/class-astra-customizer-transparent-header-configs.php
  inc/class-astra-dynamic-css.php
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/color-group-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/color-group.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/assets/css/unminified/settings-group-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/settings-group.css
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/custom-controls/color-group/color-group.scss
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
  inc/customizer/extend-custom-controls/src/color-group/color-group-component.js
  inc/theme-update/astra-update-functions.php
Labels: ready to merge

#3124 AST-777 - Overflow & min-width updated for editor tag lists UI
  inc/assets/css/block-editor-styles-rtl.css
  inc/assets/css/block-editor-styles.css
  sass/admin/block-editor-styles.scss
Labels: needs-review

#3179 chore: changelog for v3.6.9 updated as per PR review comments
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min.css
  assets/css/minified/frontend.min-rtl.css
  assets/css/minified/frontend.min.css
  assets/css/minified/main.min-rtl.css
  assets/css/minified/main.min.css
  assets/css/minified/style-flex.min.css
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  changelog.txt
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
  inc/customizer/extend-custom-controls/src/customizer-link/customizer-link-component.js
Labels: ready to merge
