Repository brainstormforce/astra, pull requests merged in 2021-05, with the labels that each got.

#2671 AST-389 - fix: All components are being used message shown up even though there is 1 component available in Desktop header builder
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
  inc/customizer/extend-custom-controls/src/builder-layout/add-component.js
Labels: needs-review

#2648 AST-374 - fix: Settings group control's label make vertically middle align
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/assets/css/unminified/settings-group-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/settings-group.css
Labels: needs-review

#2660 AST-391 - fix: PHP Error Uncaught Error: Class 'Astra_Icons' not found in searchform.php
  changelog.txt
  searchform.php
Labels: ready to merge

#2651 AST-371 - fix: Uneven spacing in between single post section has been corrected as per design perspective
  functions.php
  inc/class-astra-dynamic-css.php
  inc/core/class-astra-enqueue-scripts.php
  inc/core/class-astra-theme-options.php
  inc/customizer/class-astra-customizer.php
  inc/customizer/configurations/layout/class-astra-related-posts-configs.php
  inc/dynamic-css/comments-flex.php
  inc/dynamic-css/comments.php
  inc/modules/related-posts/class-astra-related-posts-loader.php
  inc/modules/related-posts/class-astra-related-posts-markup.php
  inc/modules/related-posts/class-astra-related-posts.php
  inc/modules/related-posts/css/dynamic-css.php
  inc/modules/related-posts/css/static-css.php
  inc/modules/related-posts/customizer/class-astra-related-posts-configs.php
  inc/modules/related-posts/related-posts.php
Labels: ready to merge

#2696 AST-416 - fix: Zero value not accepting in customizer slider control
  assets/js/minified/customizer-preview.min.js
  assets/js/unminified/customizer-preview.js
  changelog.txt
  inc/builder/type/header/above-header/assets/js/unminified/customizer-preview.js
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
  inc/customizer/extend-custom-controls/src/responsive-slider/responsive-slider-component.js
  inc/customizer/extend-custom-controls/src/slider/slider-component.js
  inc/theme-update/astra-update-functions.php
Labels: needs-review

#2697 AST-430 - fix: GB editor facing grey overlay in editor when layout is full-width
  changelog.txt
  inc/core/class-gutenberg-editor-css.php
Labels: needs-review

#2704 Build: Release PR v3.4.2
  README.md
  functions.php
  languages/astra.pot
  package-lock.json
  package.json
  readme.txt
  style.css
Labels: Release PR checklist, ready to merge

#2686 AST-271 - fix: Added accessibility for search button of search form
  changelog.txt
  searchform.php
Labels: ready to merge

#2687 AST-415 - feat: Added new options in Related Posts
  assets/js/minified/customizer-preview.min.js
  assets/js/unminified/customizer-preview.js
  changelog.txt
  inc/assets/css/customizer-preview-rtl.css
  inc/assets/css/customizer-preview.css
  inc/modules/related-posts/class-astra-related-posts-loader.php
  inc/modules/related-posts/class-astra-related-posts-markup.php
  inc/modules/related-posts/css/dynamic-css.php
  inc/modules/related-posts/css/static-css.php
  inc/modules/related-posts/customizer/class-astra-related-posts-configs.php
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-theme-background-updater.php
Labels: needs-review

#2715 AST-422 - fix: Text alignment issue for footer Widget 3 and Widget 4 when Astra Pro is deactivated
  changelog.txt
  inc/builder/type/footer/widget/class-astra-footer-widget-component-loader.php
Labels: ready to merge

#2670 Bug fixes, Reset Palette colors functionality and UI improvements in Global Palette
  inc/class-astra-global-palette.php
  inc/core/builder/class-astra-builder-options.php
  inc/core/common-functions.php
  inc/customizer/configurations/colors-background/class-astra-body-colors-configs.php
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/color-palette-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/color-palette.css
  inc/customizer/custom-controls/assets/css/unminified/color-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/color.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
  inc/customizer/extend-custom-controls/package-lock.json
  inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
  inc/customizer/extend-custom-controls/src/color-palette/control.js
  inc/customizer/extend-custom-controls/src/common/astra-color-picker-control.js
  inc/customizer/extend-custom-controls/src/customizer.js
  package.json
Labels: ready to merge

#2718 AST-464 - Fix: Block selection color(blue) not working in our recent versions.
  changelog.txt
  inc/core/class-gutenberg-editor-css.php
Labels: ready to merge

#2664 AST-402 - fix: Page Builder's menu elements shows double arrow icons when Astra's SVG icons are enabled.
  changelog.txt
  inc/extras.php
Labels: needs-review

#2720 AST-450 - fix: Shop & single product page column layout issue with grid based CSS
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce-layout-grid.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-layout-grid.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce-layout.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-layout.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-layout-grid-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-layout-grid.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-layout-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-layout.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce.css
  changelog.txt
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  sass/site/compatibility/woocommerce/woocommerce-grid.scss
  sass/site/compatibility/woocommerce/woocommerce-layout-grid.scss
  sass/site/compatibility/woocommerce/woocommerce-layout.scss
  sass/site/compatibility/woocommerce/woocommerce.scss
Labels: ready to merge

#2761 Cherry picked - #2720
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce-layout-grid.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-layout-grid.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce-layout.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-layout.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-layout-grid-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-layout-grid.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-layout-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-layout.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce.css
  changelog.txt
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  sass/site/compatibility/woocommerce/woocommerce-grid.scss
  sass/site/compatibility/woocommerce/woocommerce-layout-grid.scss
  sass/site/compatibility/woocommerce/woocommerce-layout.scss
  sass/site/compatibility/woocommerce/woocommerce.scss
Labels: needs-review

#2762 revert: Editor selection PR reverted as it will release in next version
  changelog.txt
  inc/core/class-gutenberg-editor-css.php
Labels: needs-review

#2712 AST-451 - feat: Added new border width option's compatibility for WooCommerce & EDD cart elements for style Outline
  changelog.txt
  functions.php
  inc/builder/type/header/edd-cart/dynamic-css/dynamic.css.php
  inc/builder/type/header/woo-cart/dynamic-css/dynamic.css.php
  inc/class-astra-dynamic-css.php
Labels: ready to merge

#2763 Cherry prick PR #2712
  changelog.txt
  functions.php
  inc/builder/type/header/edd-cart/dynamic-css/dynamic.css.php
  inc/builder/type/header/woo-cart/dynamic-css/dynamic.css.php
  inc/class-astra-dynamic-css.php
Labels: ready to merge

#2682 AST-413 - refactor: Removed extra CSS from dynamic CSS which loads already from static CSS
  changelog.txt
  inc/class-astra-dynamic-css.php
Labels: ready to merge

#2764 Cherry pick cart duplicate CSS #2682
  changelog.txt
  inc/class-astra-dynamic-css.php
Labels: needs-review

#2765 Build: Release PR v3.4.3
  README.md
  changelog.txt
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  languages/astra.pot
  package-lock.json
  package.json
  readme.txt
  style.css
Labels: Release PR checklist, ready to merge

#2758 v3.4.3 Release candidate
  README.md
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce-layout-grid.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-layout-grid.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce-layout.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-layout.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-layout-grid-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-layout-grid.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-layout-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-layout.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce.css
  assets/js/minified/frontend.min.js
  assets/js/minified/mobile-cart.min.js
  assets/js/unminified/frontend.js
  assets/js/unminified/mobile-cart.js
  changelog.txt
  composer.lock
  functions.php
  inc/builder/type/header/edd-cart/dynamic-css/dynamic.css.php
  inc/builder/type/header/woo-cart/dynamic-css/dynamic.css.php
  inc/class-astra-dynamic-css.php
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  inc/extras.php
  inc/theme-update/astra-update-functions.php
  languages/astra.pot
  package-lock.json
  package.json
  readme.txt
  sass/site/compatibility/woocommerce/woocommerce-grid.scss
  sass/site/compatibility/woocommerce/woocommerce-layout-grid.scss
  sass/site/compatibility/woocommerce/woocommerce-layout.scss
  sass/site/compatibility/woocommerce/woocommerce.scss
  style.css
Labels: ready to merge

#2752 AST-395 - fix: Dropdown menu disappears while scrolling on mobile device
  assets/js/minified/frontend.min.js
  assets/js/unminified/frontend.js
  changelog.txt
Labels: ready to merge

#2767 AST-464 - Fix: Editor selection color not working in after wp-5.7 versions.
  changelog.txt
  inc/core/class-gutenberg-editor-css.php
  inc/core/common-functions.php
Labels: ready to merge

#2775 Build: Release PR v3.4.4
  README.md
  functions.php
  languages/astra.pot
  package-lock.json
  package.json
  readme.txt
  style.css
Labels: Release PR checklist

#2784 Build: Release PR v3.4.5
  README.md
  changelog.txt
  functions.php
  languages/astra.pot
  package-lock.json
  package.json
  readme.txt
  style.css
Labels: Release PR checklist, ready to merge

#2785 Build: Release PR fix: Google Web Stories class exists check added before running the code.
  README.md
  changelog.txt
  functions.php
  inc/compatibility/class-astra-web-stories.php
  languages/astra.pot
  package.json
  readme.txt
  style.css
Labels: Release PR checklist, ready to merge

#2734 AST-465 - feat: Moved Site Tagline section's color controls from addon to theme
  assets/js/minified/customizer-preview.min.js
  assets/js/unminified/customizer-preview.js
  inc/builder/type/header/site-identity/assets/js/minified/customizer-preview.min.js
  inc/builder/type/header/site-identity/assets/js/unminified/customizer-preview.js
  inc/builder/type/header/site-identity/dynamic-css/dynamic.css.php
  inc/class-astra-dynamic-css.php
  inc/core/class-astra-theme-options.php
  inc/customizer/configurations/layout/class-astra-site-identity-configs.php
Labels: ready to merge

#2467 AST-153 - feat: Introduced new filter for updating Shopping Cart text in mobile flyout for Woo & EDD cart
  changelog.txt
  inc/blog/blog-config.php
  inc/builder/controllers/class-astra-builder-ui-controller.php
Labels: ready to merge

#2771 AST-481 - fix: Product Categories children li before icon broken when SVGs enabled
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce.css
  changelog.txt
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  sass/site/compatibility/woocommerce/woocommerce-grid.scss
  sass/site/compatibility/woocommerce/woocommerce.scss
Labels: ready to merge

#2769 AST-474 - fix: hide on mobile/tablet for above footer is not working on frontend.
  inc/builder/type/footer/above-footer/dynamic-css/dynamic.css.php
Labels: ready to merge

#2699 AST-432 - imprv: remove divider static CSS from the theme and added to add-on
  assets/css/minified/frontend.min-rtl.css
  assets/css/minified/frontend.min.css
  assets/css/minified/main.min-rtl.css
  assets/css/minified/main.min.css
  assets/css/unminified/frontend-rtl.css
  assets/css/unminified/frontend.css
  assets/css/unminified/main-rtl.css
  assets/css/unminified/main.css
  sass/site/builder/_header.scss
Labels: ready to merge

#2705 AST-439 - imprv: remove account related static css and move it to dynamic conditionally
  assets/css/minified/frontend.min-rtl.css
  assets/css/minified/frontend.min.css
  assets/css/minified/main.min-rtl.css
  assets/css/minified/main.min.css
  assets/css/unminified/frontend-rtl.css
  assets/css/unminified/frontend.css
  assets/css/unminified/main-rtl.css
  assets/css/unminified/main.css
  inc/builder/type/header/account/dynamic-css/dynamic.css.php
  sass/site/builder/_header.scss
Labels: ready to merge

#2717 AST-444 - imprv: removed unused css related to .nav-fallback-text
  assets/css/minified/frontend.min-rtl.css
  assets/css/minified/frontend.min.css
  assets/css/minified/main.min-rtl.css
  assets/css/minified/main.min.css
  assets/css/minified/style-flex.min.css
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  assets/css/unminified/frontend-rtl.css
  assets/css/unminified/frontend.css
  assets/css/unminified/main-rtl.css
  assets/css/unminified/main.css
  assets/css/unminified/style-flex-rtl.css
  assets/css/unminified/style-flex.css
  assets/css/unminified/style-rtl.css
  assets/css/unminified/style.css
  sass/site/header/_header-common.scss
Labels: ready to merge

#2719 AST-446 - imprv: remove default loading of above header CSS and make it conditional
  assets/css/minified/frontend.min-rtl.css
  assets/css/minified/frontend.min.css
  assets/css/minified/main.min-rtl.css
  assets/css/minified/main.min.css
  assets/css/unminified/frontend-rtl.css
  assets/css/unminified/frontend.css
  assets/css/unminified/main-rtl.css
  assets/css/unminified/main.css
  inc/builder/type/header/above-header/dynamic-css/dynamic.css.php
  inc/builder/type/header/primary-header/dynamic-css/dynamic.css.php
  sass/site/builder/_header.scss
Labels: ready to merge

#2799 AST-506 - Improvement: Increase max submenu width from 200 to 1920 same as the container.
  changelog.txt
  inc/customizer/configurations/builder/header/class-astra-header-menu-component-configs.php
Labels: ready to merge

#2796 Build: Release PR Update Screenshot of the Theme along with licenses
  README.md
  changelog.txt
  functions.php
  languages/astra.pot
  package.json
  readme.txt
  screenshot.jpg
  style.css
Labels: Release PR checklist, ready to merge

#2808 AST-522 - fix: JS Console error in blog/archive customizer settings in v3.5.0-beta-1 package
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
  inc/customizer/extend-custom-controls/src/customizer.js
Labels: ready to merge
