Repository brainstormforce/astra, pull requests merged in 2022-10, with the labels that each got.

#4651 AST-2230 - fix: visibility icon alignment issue
  inc/core/class-gutenberg-editor-css.php
Labels: ready to merge

#4664 AST-2269 - Remove related post border
  changelog.txt
  inc/modules/related-posts/css/static-css.php
Labels: bug, needs-review

#4665 AST-2268 - Removed sidebar from default layout while fresh install
  changelog.txt
  inc/core/class-astra-theme-options.php
  inc/core/common-functions.php
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-theme-background-updater.php
  tests/php/static-analysis-stubs/astra-stubs.php
Labels: enhancement, ready to merge

#4652 AST-2279 - Old HF string changes on the Astra setting page improve.
  inc/core/builder/class-astra-builder-admin.php
  inc/core/common-functions.php
Labels: hacktoberfest

#4659 AST-2250 - The cart icon size is not working for the customizer or even the front.
  changelog.txt
  inc/builder/type/header/woo-cart/assets/js/minified/customizer-preview.min.js
  inc/builder/type/header/woo-cart/assets/js/unminified/customizer-preview.js
  inc/builder/type/header/woo-cart/dynamic-css/dynamic.css.php
Labels: hacktoberfest

#4662 AST-2270 - remove input dotted focus
  changelog.txt
  inc/class-astra-dynamic-css.php
  inc/core/class-astra-theme-options.php
  inc/customizer/configurations/typography/class-astra-body-typo-configs.php
  inc/theme-update/astra-update-functions.php
Labels: enhancement, ready to merge

#4684 AST-2306 - Toggle controls position css affected for external toggle controls
  changelog.txt
  inc/metabox/extend-metabox/css/minified/metabox-rtl.min.css
  inc/metabox/extend-metabox/css/minified/metabox.min.css
  inc/metabox/extend-metabox/css/unminified/metabox-rtl.css
  inc/metabox/extend-metabox/css/unminified/metabox.css
Labels: ready to merge

#4676 AST-2294 - fix: list bullets block misaligned with page container.
  inc/dynamic-css/block-editor-compatibility.php
  inc/theme-update/astra-update-functions.php
Labels: ready to merge

#4650 AST-2228 - fix: page title misalignment with page container on full width stretched
  .gitignore
  inc/class-astra-dynamic-css.php
  inc/core/class-astra-wp-editor-css.php
  inc/core/class-gutenberg-editor-css.php
  inc/dynamic-css/block-editor-compatibility.php
  inc/theme-update/astra-update-functions.php
Labels: ready to merge

#4678 AST-1924 - Divider is not showing on footer customizer.
  changelog.txt
  inc/builder/type/footer/widget/dynamic-css/dynamic.css.php
Labels: hacktoberfest

#4675 AST-2288 - Margin top and bottom while using Full Width / Contained layout
  changelog.txt
  inc/class-astra-dynamic-css.php
Labels: hacktoberfest
