Repository brainstormforce/astra, pull requests merged in 2022-08, with the labels that each got.

#4525 AST-2047 - Plugin compatibility issues near add to cart
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce.css
  changelog.txt
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  sass/site/compatibility/woocommerce/woocommerce-grid.scss
  sass/site/compatibility/woocommerce/woocommerce.scss
Labels: bug, ready to merge

#4540 AST-2113 - Deprecated function warning on elementor install
  changelog.txt
  inc/compatibility/class-astra-elementor.php
  inc/dynamic-css/container-layouts.php
Labels: bug

#4528 AST-2063 - view cart link added back when ajax add to cart enabled
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce.css
  changelog.txt
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  sass/site/compatibility/woocommerce/woocommerce-grid.scss
  sass/site/compatibility/woocommerce/woocommerce.scss
Labels: ready to merge

#4511 AST-2025 - Moved design 3 from addons to theme
  assets/css/minified/customizer-controls.min-rtl.css
  assets/css/minified/customizer-controls.min.css
  assets/css/unminified/customizer-controls-rtl.css
  assets/css/unminified/customizer-controls.css
  changelog.txt
  functions.php
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  inc/compatibility/woocommerce/customizer/sections/layout/class-astra-woo-shop-layout-configs.php
  inc/compatibility/woocommerce/customizer/sections/layout/class-astra-woo-shop-single-layout-configs.php
  inc/compatibility/woocommerce/woocommerce-common-functions.php
  inc/extras.php
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-theme-background-updater.php
Labels: ready to merge

#4522 AST-2034 - Hide cart total if cart is empty
  changelog.txt
  inc/builder/type/header/woo-cart/assets/js/minified/customizer-preview.min.js
  inc/builder/type/header/woo-cart/assets/js/unminified/customizer-preview.js
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  inc/customizer/configurations/builder/header/class-astra-customizer-woo-cart-configs.php
Labels: enhancement, needs-review

#4508 AST-2028 - Added sticky add to cart to astra theme
  assets/css/minified/compatibility/woocommerce/sticky-add-to-cart.min.css
  assets/css/unminified/compatibility/woocommerce/sticky-add-to-cart-rtl.css
  assets/css/unminified/compatibility/woocommerce/sticky-add-to-cart.css
  assets/js/minified/customizer-preview.min.js
  assets/js/minified/sticky-add-to-cart.min.js
  assets/js/unminified/customizer-preview.js
  assets/js/unminified/sticky-add-to-cart.js
  changelog.txt
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  inc/compatibility/woocommerce/customizer/sections/layout/class-astra-woo-shop-single-layout-configs.php
  inc/core/class-astra-enqueue-scripts.php
  sass/site/compatibility/woocommerce/sticky-add-to-cart.scss
Labels: enhancement, ready to merge, needs-review

#4520 AST-2043 - Customizer button takes user to it's respected customizer section
  changelog.txt
  inc/compatibility/woocommerce/class-astra-woocommerce.php
Labels: enhancement, needs-review

#4517 AST-2027 - Single product structure from addons to theme
  changelog.txt
  functions.php
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  inc/compatibility/woocommerce/customizer/sections/layout/class-astra-woo-shop-single-layout-configs.php
Labels: ready to merge

#4541 AST-1893 - Fix: Show password option is not visible on My Account page
  changelog.txt
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  inc/core/common-functions.php
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-theme-background-updater.php
  tests/php/static-analysis-stubs/astra-stubs.php
Labels: bug

#4164 AST-1606 - Footer builder global background color and padding not working below and above section in the frontend
  changelog.txt
  inc/builder/type/footer/primary-footer/dynamic-css/dynamic.css.php
  inc/core/common-functions.php
  tests/php/static-analysis-stubs/astra-stubs.php
Labels: Stale

#4537 AST-2100 - Fix active filter alignment
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce.css
  changelog.txt
  sass/site/compatibility/woocommerce/woocommerce-grid.scss
  sass/site/compatibility/woocommerce/woocommerce.scss
Labels: bug, needs-review

#4526 AST-2046 - Added condition to check if Brizy is activated for CSS exclusion
  changelog.txt
  inc/dynamic-css/container-layouts.php
Labels: ready to merge

#4548 AST-2134 - Spectra plugin admin redirection url corrected & added highlight label for plugin
  changelog.txt
  inc/assets/css/astra-admin-menu-settings-rtl.css
  inc/assets/css/astra-admin-menu-settings.css
  inc/core/class-astra-admin-settings.php
  tests/php/static-analysis-stubs/astra-stubs.php
Labels: ready to merge

#4558 AST-2140 - fix: Brizy Full/Width Layout is containing extra padding which needs …
  inc/dynamic-css/container-layouts.php
Labels: bug

#4563 AST-2145 - Free shipping position issue when astra addon is disabled
  inc/compatibility/woocommerce/class-astra-woocommerce.php
Labels: bug, needs-review

#4565 AST-2148 - Moved product link mark-up to theme
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  inc/compatibility/woocommerce/customizer/sections/layout/class-astra-woo-shop-layout-configs.php
Labels: bug, ready to merge
