Repository brainstormforce/astra, pull requests merged in 2022-09, with the labels that each got.

#4555 AST-2141 - Product image for tablet view
  assets/css/minified/compatibility/woocommerce/woocommerce-smallscreen-grid.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-smallscreen-grid.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce-smallscreen.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-smallscreen.min.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-smallscreen-grid-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-smallscreen-grid.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-smallscreen-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-smallscreen.css
  changelog.txt
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  sass/site/compatibility/woocommerce/woocommerce-smallscreen-grid.scss
  sass/site/compatibility/woocommerce/woocommerce-smallscreen.scss
Labels: bug, ready to merge

#4576 AST-2186 - Url encoding issue for customizer url
  inc/core/common-functions.php
Labels: bug, needs-review

#4553 AST-1578 - Pencil edit icon for sticky add to cart and shop filter
  assets/css/minified/compatibility/woocommerce/sticky-add-to-cart.min.css
  assets/css/unminified/compatibility/woocommerce/sticky-add-to-cart-rtl.css
  assets/css/unminified/compatibility/woocommerce/sticky-add-to-cart.css
  changelog.txt
  inc/assets/css/customizer-preview-rtl.css
  inc/assets/css/customizer-preview.css
  inc/assets/js/customizer-preview.js
  inc/builder/controllers/class-astra-builder-ui-controller.php
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  inc/markup-extras.php
  sass/site/compatibility/woocommerce/sticky-add-to-cart.scss
  tests/php/static-analysis-stubs/astra-stubs.php
Labels: enhancement, needs-review

#4581 AST-1978 - Recently Viewed products module
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/assets/css/unminified/divider-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/divider.css
Labels: enhancement, needs-review

#4579 AST-2176 - Moved payment option from pro to free
  assets/js/minified/customizer-preview.min.js
  assets/js/unminified/customizer-preview.js
  assets/svg/svgs.json
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  inc/compatibility/woocommerce/customizer/sections/layout/class-astra-woo-shop-single-layout-configs.php
Labels: needs-review

#4578 AST-2187 - Moved add to cart Quantity button from pro to free
  assets/js/minified/add-to-cart-quantity-btn.min.js
  assets/js/unminified/add-to-cart-quantity-btn.js
  changelog.txt
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  inc/compatibility/woocommerce/customizer/sections/layout/class-astra-woo-shop-misc-layout-configs.php
  inc/compatibility/woocommerce/woocommerce-common-functions.php
  inc/core/class-astra-enqueue-scripts.php
Labels: needs-review

#4582 AST-2177 - Woo Cart icon fixes
  assets/js/minified/customizer-preview.min.js
  assets/js/unminified/customizer-preview.js
  inc/builder/type/header/woo-cart/assets/js/minified/customizer-preview.min.js
  inc/builder/type/header/woo-cart/assets/js/unminified/customizer-preview.js
  inc/builder/type/header/woo-cart/dynamic-css/dynamic.css.php
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  inc/compatibility/woocommerce/woocommerce-common-functions.php
  inc/core/class-astra-enqueue-scripts.php
  inc/core/common-functions.php
  inc/customizer/configurations/builder/header/class-astra-customizer-woo-cart-configs.php
  tests/php/static-analysis-stubs/astra-stubs.php
Labels: bug, ready to merge

#4586 Update changelog.txt
  changelog.txt
Labels: title needs formatting

#4588 AST-2190 - Remove tabs in woocommerce misc section when addons is disabled
  inc/compatibility/woocommerce/customizer/sections/layout/class-astra-woo-shop-misc-layout-configs.php
Labels: bug, needs-review

#4587 AST-2191 - Border not showing up when astra addon is disabled
  inc/builder/type/header/woo-cart/dynamic-css/dynamic.css.php
  inc/compatibility/woocommerce/class-astra-woocommerce.php
Labels: bug, needs-review

#4592 AST-2137 - Release PR v3.9.2
  README.md
  assets/fonts/google-fonts.json
  changelog.txt
  composer.lock
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  inc/compatibility/woocommerce/customizer/sections/layout/class-astra-woo-shop-misc-layout-configs.php
  inc/compatibility/woocommerce/woocommerce-common-functions.php
  inc/core/class-astra-admin-settings.php
  inc/core/common-functions.php
  inc/extras.php
  inc/google-fonts.php
  inc/theme-update/astra-update-functions.php
  languages/astra.pot
  package-lock.json
  package.json
  readme.txt
  style.css
  tests/php/static-analysis-stubs/astra-stubs.php
Labels: Release PR checklist

#4571 AST-2098 - Sale text alignment should be center aligned
  changelog.txt
  inc/compatibility/woocommerce/class-astra-woocommerce.php
Labels: bug, needs-review

#4570 AST-2101 - Active filter widget align clear button
  changelog.txt
  inc/compatibility/woocommerce/class-astra-woocommerce.php
Labels: bug, needs-review

#4549 AST-2102 - Added Back to cart button on checkout
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/assets/css/unminified/divider-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/divider.css
Labels: enhancement, needs-review

#4573 AST-1622 - fix: Astra Meta settings not saving when custom fields option is enabled in the preferences
  changelog.txt
  inc/assets/js/custom-fields-priority.js
  inc/metabox/class-astra-meta-boxes.php
  package-lock.json
Labels: bug, needs-review

#4589 AST-2015 - Flyout width responsive control
  functions.php
  inc/builder/controllers/class-astra-builder-ui-controller.php
  inc/builder/type/header/woo-cart/assets/js/minified/customizer-preview.min.js
  inc/builder/type/header/woo-cart/assets/js/unminified/customizer-preview.js
  inc/builder/type/header/woo-cart/dynamic-css/dynamic.css.php
  inc/core/builder/class-astra-builder-options.php
  inc/customizer/configurations/builder/header/class-astra-customizer-woo-cart-configs.php
  inc/lib/astra-notices/class-astra-notices.php
  inc/lib/astra-notices/composer.json
  inc/lib/astra-notices/notices.css
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-theme-background-updater.php
  package-lock.json
  package.json
  tests/php/static-analysis-stubs/astra-stubs.php
Labels: enhancement, ready to merge

#4634 AST-2233 - Default style seperator block displays "Wide Line" even when default with templates
  assets/css/minified/frontend.min-rtl.css
  assets/css/minified/frontend.min.css
  assets/css/minified/main.min-rtl.css
  assets/css/minified/main.min.css
  assets/css/minified/style-flex.min.css
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  assets/css/unminified/frontend-rtl.css
  assets/css/unminified/frontend.css
  assets/css/unminified/main-rtl.css
  assets/css/unminified/main.css
  assets/css/unminified/style-flex-rtl.css
  assets/css/unminified/style-flex.css
  assets/css/unminified/style-rtl.css
  assets/css/unminified/style.css
  inc/core/class-gutenberg-editor-css.php
  sass/admin/block-editor-styles.scss
  sass/site/primary/_posts-and-pages.scss
Labels: ready to merge

#4621 AST-2243 - Moved border width from pro to free
  changelog.txt
  inc/builder/type/header/woo-cart/assets/js/minified/customizer-preview.min.js
  inc/builder/type/header/woo-cart/assets/js/unminified/customizer-preview.js
  inc/builder/type/header/woo-cart/dynamic-css/dynamic.css.php
  inc/core/builder/class-astra-builder-options.php
  inc/customizer/configurations/builder/header/class-astra-customizer-woo-cart-configs.php
Labels: enhancement, needs-review

#4636 AST-2246 - Payment list styling broken inside quick view
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid.css
  changelog.txt
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  sass/site/compatibility/woocommerce/woocommerce-grid.scss
Labels: bug, needs-review

#4646 AST-2246 - Fix spacing between add to cart button and qty selector
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce.css
  sass/site/compatibility/woocommerce/woocommerce-grid.scss
  sass/site/compatibility/woocommerce/woocommerce.scss
Labels: bug, needs-review
