Repository brainstormforce/astra, pull requests merged in 2022-12, with the labels that each got.

#4794 AST-2207 - Gradient angle input field not visible in the block editor
  assets/js/minified/customizer-preview.min.js
  assets/js/minified/extend-customizer.min.js
  assets/js/minified/flexibility.min.js
  assets/js/minified/frontend-pro.min.js
  assets/js/minified/frontend.min.js
  assets/js/minified/mobile-cart.min.js
  assets/js/minified/navigation.min.js
  assets/js/minified/sticky-add-to-cart.min.js
  assets/js/minified/style.min.js
  changelog.txt
  inc/addons/transparent-header/assets/js/minified/customizer-preview.min.js
  inc/assets/css/wp-editor-styles-rtl.css
  inc/assets/css/wp-editor-styles.css
  inc/builder/type/header/woo-cart/assets/js/minified/customizer-preview.min.js
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  sass/admin/block-editor-styles.scss
  sass/admin/wp-editor-styles.scss
Labels: ready to merge

#4817 AST-2236 - sidebar design tab issue
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/assets/css/unminified/divider-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/divider.css
Labels: bug, needs-review

#4795 AST-1727 - Block Editor Experience Improvements
  changelog.txt
  inc/assets/css/block-editor-styles-rtl.css
  inc/assets/css/block-editor-styles.css
  inc/assets/css/wp-editor-styles-rtl.css
  inc/assets/css/wp-editor-styles.css
  inc/assets/js/block-editor-script.js
  inc/class-astra-dynamic-css.php
  inc/core/class-astra-wp-editor-css.php
  inc/dynamic-css/block-editor-compatibility.php
  inc/theme-update/astra-update-functions.php
  package-lock.json
  sass/admin/block-editor-styles.scss
  sass/admin/wp-editor-styles.scss
  tests/php/static-analysis-stubs/astra-stubs.php
Labels: enhancement

#4825 AST-2084 - Fix border for whats new icon in admin dashboard
  admin/assets/build/dashboard-app-rtl.css
  admin/assets/build/dashboard-app.asset.php
  admin/assets/build/dashboard-app.css
  admin/assets/build/dashboard-app.js
  admin/assets/src/dashboard-app/MainNav.js
  changelog.txt
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
Labels: bug, needs-review

#4827 AST-2690 - fix: Matching fallback values for frontend with editor.
  inc/core/class-astra-wp-editor-css.php
Labels: ready to merge

#4820 AST-2670 - Woocommerce compatibility with Variation Swatches for Woocommerce
  changelog.txt
  inc/class-astra-dynamic-css.php
Labels: bug, ready to merge

#4833 AST-2608 - fix: applied font properties to editor title
  inc/assets/css/wp-editor-styles-rtl.css
  inc/assets/css/wp-editor-styles.css
  inc/core/class-astra-wp-editor-css.php
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/assets/css/unminified/font-presets-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/font-presets.css
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
  inc/customizer/extend-custom-controls/src/ast-font-extras/ast-font-extras.js
  package-lock.json
  sass/admin/wp-editor-styles.scss
Labels: ready to merge

#4838 AST-2711 - Fixed single product underline issue
  inc/blog/blog.php
  inc/modules/posts-structures/assets/js/minified/customizer-preview.min.js
  inc/modules/posts-structures/assets/js/unminified/customizer-preview.js
  inc/modules/posts-structures/css/archive-dynamic.css.php
  inc/modules/posts-structures/css/single-dynamic.css.php
Labels: ready to merge

#4853 AST-2764 - Narrow width bugfixes
  inc/customizer/configurations/layout/class-astra-site-layout-configs.php
  inc/dynamic-css/block-editor-compatibility.php
  inc/dynamic-css/content-background.php
Labels: ready to merge

#4836 AST-2674 - Dynamic font-css specific code optimization wrt lines of code & removed old legacy code
  admin/assets/build/dashboard-app-rtl.css
  admin/assets/build/dashboard-app.asset.php
  admin/assets/build/dashboard-app.css
  admin/assets/build/dashboard-app.js
  admin/assets/src/dashboard-app/MainNav.js
  admin/assets/src/dashboard-app/pages/free-vs-pro/FreeVsPro.js
  admin/assets/src/dashboard-app/pages/starter-templates/StarterTemplates.js
  inc/addons/breadcrumbs/dynamic-css/dynamic.css.php
  inc/builder/type/base/dynamic-css/button/class-astra-button-component-dynamic-css.php
  inc/builder/type/header/above-header/dynamic-css/dynamic.css.php
  inc/builder/type/header/mobile-menu/dynamic-css/dynamic.css.php
  inc/class-astra-dynamic-css.php
  inc/core/class-astra-wp-editor-css.php
  inc/core/common-functions.php
  inc/core/deprecated/deprecated-functions.php
  inc/customizer/configurations/layout/class-astra-site-identity-configs.php
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/assets/css/unminified/sortable-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/sortable.css
  inc/extras.php
  inc/modules/posts-structures/assets/js/minified/customizer-preview.min.js
  inc/modules/posts-structures/assets/js/unminified/customizer-preview.js
  inc/modules/posts-structures/css/archive-dynamic.css.php
  inc/modules/posts-structures/css/single-dynamic.css.php
  inc/modules/related-posts/css/dynamic-css.php
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-theme-background-updater.php
  tests/php/static-analysis-stubs/astra-stubs.php
Labels: ready to merge

#4854 AST-2774 - fix: top spacing breaks UI, therefore needs to be removed.
  .github/workflows/theme-check.yml
  inc/builder/type/header/woo-cart/dynamic-css/dynamic.css.php
  inc/dynamic-css/block-editor-compatibility.php
Labels: ready to merge
