Repository brainstormforce/astra, pull requests merged in 2022-11, with the labels that each got.

#4725 AST-2364 - Button editor styles gets overridden by WP-6.1
  inc/core/class-astra-wp-editor-css.php
Labels: ready to merge

#4726 AST-2332 - Build release PR v3.9.3
  README.md
  assets/fonts/google-fonts.json
  changelog.txt
  functions.php
  inc/google-fonts.php
  languages/astra.pot
  package-lock.json
  package.json
  readme.txt
  style.css
Labels: Release PR checklist

#4717 AST-2362 - fix: spectra container blocks not matching frontend & backend on FW Contained on few layouts
  assets/css/minified/style-flex.min.css
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  assets/css/unminified/style-flex-rtl.css
  assets/css/unminified/style-flex.css
  assets/css/unminified/style-rtl.css
  assets/css/unminified/style.css
  inc/assets/css/wp-editor-styles-rtl.css
  inc/assets/css/wp-editor-styles.css
  inc/core/class-astra-wp-editor-css.php
  package-lock.json
  phpcs.xml.dist
  sass/admin/wp-editor-styles.scss
Labels: bug

#4734 AST-2401 - fix: issue with template kit alignment in editor
  assets/css/minified/style-flex.min.css
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  assets/css/unminified/style-flex-rtl.css
  assets/css/unminified/style-flex.css
  assets/css/unminified/style-rtl.css
  assets/css/unminified/style.css
  inc/assets/js/block-editor-script.js
  inc/core/class-astra-wp-editor-css.php
  package-lock.json
Labels: ready to merge

#4381 AST-1885 - Menu gets very long when Elementor plugin is active
  changelog.txt
  inc/class-astra-dynamic-css.php
  tests/php/static-analysis-stubs/astra-stubs.php
Labels: ready to merge, Stale

#4488 AST-2013 - Transparent Header Issue with Full Width/Stretched Layout
  changelog.txt
  inc/dynamic-css/container-layouts.php
Labels: hacktoberfest

#4745 AST-2414 - Release v3.9.4 checklist PR
  assets/css/minified/style-flex.min.css
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  assets/css/unminified/style-flex-rtl.css
  assets/css/unminified/style-flex.css
  assets/css/unminified/style-rtl.css
  assets/css/unminified/style.css
  assets/fonts/google-fonts.json
  changelog.txt
  composer.lock
  inc/builder/controllers/class-astra-builder-ui-controller.php
  inc/builder/markup/class-astra-builder-header.php
  inc/builder/type/header/above-header/dynamic-css/dynamic.css.php
  inc/builder/type/header/below-header/dynamic-css/dynamic.css.php
  inc/builder/type/header/primary-header/dynamic-css/dynamic.css.php
  inc/class-astra-dynamic-css.php
  inc/compatibility/class-astra-gutenberg.php
  inc/compatibility/edd/edd-common-functions.php
  inc/compatibility/lifterlms/class-astra-lifterlms.php
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  inc/compatibility/woocommerce/customizer/sections/layout/class-astra-woo-shop-single-layout-configs.php
  inc/core/builder/class-astra-builder-admin.php
  inc/core/class-astra-admin-settings.php
  inc/core/class-astra-wp-editor-css.php
  inc/core/common-functions.php
  inc/customizer/class-astra-customizer-sanitizes.php
  inc/customizer/class-astra-customizer.php
  inc/dynamic-css/block-editor-compatibility.php
  inc/extras.php
  inc/google-fonts.php
  inc/markup-extras.php
  inc/metabox/class-astra-meta-boxes.php
  inc/theme-update/astra-update-functions.php
  languages/astra.pot
  package-lock.json
  package.json
  tests/php/static-analysis-stubs/astra-stubs.php
Labels: ready to merge, Release PR checklist

#4752 Fix: Updated site layout config & changed name of the NWL width slider
  inc/customizer/configurations/layout/class-astra-site-layout-configs.php
Labels: enhancement

#4751 Narrow container function
  inc/class-astra-dynamic-css.php
  inc/core/common-functions.php
  inc/customizer/configurations/layout/class-astra-blog-layout-configs.php
  inc/customizer/configurations/layout/class-astra-blog-single-layout-configs.php
Labels: enhancement, needs-review

#4723 AST-2196 - Mega menu revamp
  inc/assets/css/ast-builder-customizer-rtl.css
  inc/assets/css/ast-builder-customizer.css
  inc/assets/css/font-icon-picker-rtl.css
  inc/assets/css/font-icon-picker.css
  inc/customizer/class-astra-customizer.php
Labels: enhancement, ready to merge

#4754 AST-2280 - Narrow Width Container Layout
  assets/svg/svgs.json
  changelog.txt
  inc/assets/js/block-editor-script.js
  inc/assets/js/customizer-preview.js
  inc/builder/type/header/primary-header/class-astra-primary-header-loader.php
  inc/class-astra-dynamic-css.php
  inc/core/class-astra-theme-options.php
  inc/core/class-astra-wp-editor-css.php
  inc/core/class-gutenberg-editor-css.php
  inc/core/common-functions.php
  inc/customizer/configurations/layout/class-astra-blog-layout-configs.php
  inc/customizer/configurations/layout/class-astra-blog-single-layout-configs.php
  inc/customizer/configurations/layout/class-astra-sidebar-layout-configs.php
  inc/customizer/configurations/layout/class-astra-site-container-layout-configs.php
  inc/customizer/configurations/layout/class-astra-site-layout-configs.php
  inc/dynamic-css/block-editor-compatibility.php
  inc/metabox/class-astra-meta-boxes.php
  inc/metabox/extend-metabox/build/index.js
  inc/metabox/extend-metabox/src/settings.js
  package-lock.json
  package.json
  tests/php/static-analysis-stubs/astra-stubs.php
Labels: ready to merge

#4768 AST-2502 - console warning for core/editor about to deprecate in 6.2
  changelog.txt
  inc/assets/js/block-editor-script.js
Labels: ready to merge

#4661 AST-566 - starter content support added
  README.md
  assets/js/minified/frontend.min.js
  assets/js/minified/smooth-scroll.min.js
  assets/js/unminified/frontend.js
  changelog.txt
  functions.php
  inc/assets/images/starter-content/about-us.jpg
  inc/assets/images/starter-content/avatar.png
  inc/assets/images/starter-content/blog.svg
  inc/assets/images/starter-content/branding.jpg
  inc/assets/images/starter-content/building.svg
  inc/assets/images/starter-content/graphic.jpg
  inc/assets/images/starter-content/hero-img.svg
  inc/assets/images/starter-content/logo.png
  inc/assets/images/starter-content/passionate.svg
  inc/assets/images/starter-content/portfolio.svg
  inc/assets/images/starter-content/professional.svg
  inc/assets/images/starter-content/shopping-bag.svg
  inc/assets/images/starter-content/support.svg
  inc/assets/images/starter-content/web.jpg
  inc/class-astra-after-setup-theme.php
  inc/compatibility/class-astra-starter-content.php
  inc/compatibility/starter-content/astra-settings-export.json
  inc/compatibility/starter-content/home.php
  inc/core/class-astra-enqueue-scripts.php
  inc/core/class-astra-theme-options.php
  inc/customizer/class-astra-customizer-register-sections-panels.php
  inc/customizer/class-astra-customizer.php
  inc/customizer/configurations/global-misc/class-astra-global-misc-configs.php
  inc/extras.php
  inc/theme-update/astra-update-functions.php
  readme.txt
  screenshot.jpg
Labels: enhancement, needs-review

#4761 AST-2482 - Smooth scroll
  assets/js/minified/frontend.min.js
  assets/js/minified/smooth-scroll.min.js
  assets/js/unminified/frontend.js
  changelog.txt
  functions.php
  inc/core/class-astra-enqueue-scripts.php
  inc/core/class-astra-theme-options.php
  inc/customizer/configurations/performance/class-astra-performance-configs.php
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-theme-background-updater.php
Labels: enhancement, needs-review
