Repository brainstormforce/astra, pull requests merged in 2022-07, with the labels that each got.

#4445 Woocommerce fixes
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min.css
  assets/css/minified/frontend.min-rtl.css
  assets/css/minified/frontend.min.css
  assets/css/minified/main.min-rtl.css
  assets/css/minified/main.min.css
  assets/css/minified/style-flex.min.css
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce.css
  assets/css/unminified/frontend-rtl.css
  assets/css/unminified/frontend.css
  assets/css/unminified/main-rtl.css
  assets/css/unminified/main.css
  assets/css/unminified/style-flex-rtl.css
  assets/css/unminified/style-flex.css
  assets/css/unminified/style-rtl.css
  assets/css/unminified/style.css
  inc/class-astra-global-palette.php
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-theme-background-updater.php
  sass/site/compatibility/woocommerce/woocommerce-grid.scss
  sass/site/compatibility/woocommerce/woocommerce.scss
  sass/site/secondary/_widgets.scss
Labels: bug, needs-review

#4458 WooCommerce single product summary spacing
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min.css
  assets/css/unminified/compatibility/edd-grid.css
  assets/css/unminified/compatibility/edd.css
  assets/css/unminified/compatibility/lifterlms-flex.css
  assets/css/unminified/compatibility/lifterlms.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid.css
  assets/css/unminified/compatibility/woocommerce/woocommerce.css
  assets/css/unminified/frontend.css
  assets/css/unminified/main.css
  assets/css/unminified/menu-animation.css
  assets/css/unminified/style-flex.css
  assets/css/unminified/style.css
  sass/site/compatibility/woocommerce/woocommerce-grid.scss
  sass/site/compatibility/woocommerce/woocommerce.scss
Labels: enhancement, needs-review

#4459 Woocommerce shop page changes
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce.css
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  inc/compatibility/woocommerce/customizer/sections/layout/class-astra-woo-shop-cart-layout-configs.php
  inc/compatibility/woocommerce/customizer/sections/layout/class-astra-woo-shop-layout-configs.php
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/assets/css/unminified/divider-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/divider.css
  inc/customizer/custom-controls/assets/css/unminified/radio-image-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/radio-image.css
  inc/dynamic-css/block-editor-compatibility.php
  sass/site/compatibility/woocommerce/woocommerce-grid.scss
  sass/site/compatibility/woocommerce/woocommerce.scss
Labels: bug, needs-review

#4189 Fixed docs errors in development-workflow.md
  docs/development/development-workflow.md
Labels: Stale

#4462 AST-1969 - Woocommerce changes
  inc/compatibility/woocommerce/customizer/sections/layout/class-astra-woo-shop-layout-configs.php
  inc/compatibility/woocommerce/customizer/sections/layout/class-astra-woo-shop-single-layout-configs.php
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/assets/css/unminified/customizer-style-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/customizer-style.css
  inc/customizer/custom-controls/assets/css/unminified/divider-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/divider.css
  inc/customizer/custom-controls/assets/css/unminified/settings-group-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/settings-group.css
  inc/customizer/custom-controls/assets/css/unminified/sortable-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/sortable.css
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/custom-controls/customizer-style.scss
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
  inc/customizer/extend-custom-controls/src/sortable/control.js
  inc/customizer/override-defaults.php
Labels: bug, enhancement, ready to merge

#4470 AST-1973 - Fix Cart icon color when transparent header is enabled
  inc/builder/type/header/woo-cart/dynamic-css/dynamic.css.php
  inc/class-astra-global-palette.php
  inc/theme-update/astra-update-functions.php
Labels: bug, needs-review

#4474 Order button spacing issue
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce.css
  sass/site/compatibility/woocommerce/woocommerce-grid.scss
  sass/site/compatibility/woocommerce/woocommerce.scss
Labels: bug, needs-review

#3514 AST-1091 - E2E Test case for Single post title font
  tests/e2e/specs/customizer/blog/single-post/post-title-font.test.js
Labels: ready to merge, e2e-tests

#4475 AST-1980 - Skipped elementor onboarding process from theme
  inc/customizer/configurations/builder/header/class-astra-customizer-woo-cart-configs.php
  inc/markup-extras.php
  tests/php/static-analysis-stubs/astra-stubs.php
Labels: ready to merge

#4482 AST-1934 - Build: Release PR
  README.md
  assets/fonts/google-fonts.json
  functions.php
  inc/builder/controllers/class-astra-builder-ui-controller.php
  inc/builder/type/header/woo-cart/dynamic-css/dynamic.css.php
  inc/class-astra-global-palette.php
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  inc/compatibility/woocommerce/customizer/sections/class-astra-woo-store-notice-configs.php
  inc/google-fonts.php
  inc/markup-extras.php
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-theme-background-updater.php
  languages/astra.pot
  package-lock.json
  package.json
  readme.txt
  style.css
  tests/php/static-analysis-stubs/astra-stubs.php
Labels: Release PR checklist

#4492 AST-2021 - Row block keeps changing to Group block in the Block Editor
  assets/js/minified/customizer-preview.min.js
  assets/js/minified/extend-customizer.min.js
  assets/js/minified/flexibility.min.js
  assets/js/minified/frontend-pro.min.js
  assets/js/minified/frontend.min.js
  assets/js/minified/mobile-cart.min.js
  assets/js/minified/navigation.min.js
  assets/js/minified/skip-link-focus-fix.min.js
  assets/js/minified/style.min.js
  changelog.txt
  inc/assets/js/column-block-compatibility.js
  inc/builder/type/header/menu/assets/js/minified/customizer-preview.min.js
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
Labels: ready to merge

#4490 AST-2022 - Child theme's WC templates gets overridden by parent theme
  changelog.txt
  inc/class-astra-dynamic-css.php
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  inc/compatibility/woocommerce/templates/cart/mini-cart.php
  inc/theme-update/class-astra-theme-background-updater.php
Labels: ready to merge

#4487 AST-1992 - Changed Cart Click Action Option name from Offcanvas Cart to Slide In Cart
  inc/customizer/configurations/builder/header/class-astra-customizer-woo-cart-configs.php
Labels: ready to merge

#4495 AST-2023 - v3.9.1 Build: Release PR
  README.md
  assets/js/minified/customizer-preview.min.js
  assets/js/minified/extend-customizer.min.js
  assets/js/minified/flexibility.min.js
  assets/js/minified/frontend-pro.min.js
  assets/js/minified/frontend.min.js
  assets/js/minified/mobile-cart.min.js
  assets/js/minified/navigation.min.js
  assets/js/minified/skip-link-focus-fix.min.js
  assets/js/minified/style.min.js
  changelog.txt
  functions.php
  inc/builder/type/header/menu/assets/js/minified/customizer-preview.min.js
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  languages/astra.pot
  package-lock.json
  package.json
  readme.txt
  style.css
Labels: Release PR checklist

#4361 AQA-156 - E2E test case for astra meta setting disable header option
  tests/e2e/specs/customizer/astra-meta-settings/disable-header.test.js
Labels: ready to merge, e2e-tests

#4161 QAE-848 - E2E test case for header builder social icon spacing option
  tests/e2e/specs/customizer/header-builder/elements/social-icons/social-icon-spacing.test.js
Labels: ready to merge, e2e-tests

#3948 QAE-296 - E2E test case for related post structure
  tests/e2e/specs/customizer/blog/single-post/related-post-structure.test.js
Labels: ready to merge, e2e-tests

#4498 AST-2030 - WooCommerce cart Icon link is not working with the Dropdown cart
  changelog.txt
  inc/compatibility/woocommerce/class-astra-woocommerce.php
Labels: ready to merge

#4499 AST-2042 - Fix step count for range slider when em is selected
  changelog.txt
  inc/addons/breadcrumbs/customizer/class-astra-breadcrumbs-typo-configs.php
  inc/customizer/configurations/builder/base/class-astra-button-component-configs.php
  inc/customizer/configurations/builder/class-astra-builder-base-configuration.php
  inc/customizer/configurations/builder/footer/class-astra-customizer-footer-menu-configs.php
  inc/customizer/configurations/builder/header/class-astra-header-menu-component-configs.php
  inc/customizer/configurations/builder/header/class-astra-mobile-menu-component-configs.php
  inc/customizer/configurations/typography/class-astra-archive-typo-configs.php
  inc/customizer/configurations/typography/class-astra-header-typo-configs.php
  inc/customizer/configurations/typography/class-astra-headings-typo-configs.php
  inc/customizer/configurations/typography/class-astra-single-typo-configs.php
  inc/modules/related-posts/customizer/class-astra-related-posts-configs.php
Labels: bug, ready to merge
