Repository brainstormforce/astra, pull requests merged in 2022-06, with the labels that each got.

#4293 AST-1841 - W3 validator - background color property parse error
  changelog.txt
  inc/core/common-functions.php
Labels: ready to merge

#4308 AST-1854 - Added area label to link wave accessibility issue
  changelog.txt
  inc/modules/related-posts/class-astra-related-posts-markup.php
Labels: ready to merge

#4394 AST-1897 - v3.8.2 release-candidate to master
  README.md
  assets/fonts/google-fonts.json
  assets/js/minified/frontend.min.js
  assets/js/unminified/frontend.js
  changelog.txt
  functions.php
  inc/assets/js/block-editor-script.js
  inc/class-astra-dynamic-css.php
  inc/core/builder/class-astra-builder-helper.php
  inc/core/class-astra-enqueue-scripts.php
  inc/core/class-gutenberg-editor-css.php
  inc/core/common-functions.php
  inc/customizer/class-astra-customizer.php
  inc/customizer/class-astra-fonts.php
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/color-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/color.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/google-fonts.php
  inc/markup-extras.php
  inc/metabox/class-astra-meta-boxes.php
  inc/modules/related-posts/class-astra-related-posts-markup.php
  languages/astra.pot
  package-lock.json
  package.json
  readme.txt
  style.css
  tests/php/static-analysis-stubs/astra-stubs.php
Labels: ready to merge

#4386 AST-1894 - Primary submenus not expandable on mobile when toggle button element is not added.
  assets/js/minified/frontend-pro.min.js
  assets/js/minified/frontend.min.js
  assets/js/unminified/frontend-pro.js
  assets/js/unminified/frontend.js
  changelog.txt
  package-lock.json
  package.json
Labels: ready to merge

#4403 AST-1887 - Content not showing correctly when row block used in the block editor
  changelog.txt
  inc/compatibility/class-astra-gutenberg.php
  package-lock.json
Labels: ready to merge

#4402 AST-1909 - Compatibility with WordPress 6.0 - Image block not aligned center for old users when Legacy option set from the Block Editor.
  changelog.txt
  inc/class-astra-dynamic-css.php
Labels: ready to merge

#4251 AST-1888 - Fixed logo markup show without logo upload
  changelog.txt
  inc/markup-extras.php
Labels: ready to merge

#4364 AST-1861 - Blog Achieve layout 2 and layout 3 broken between 769px to 921px
  assets/css/minified/main.min-rtl.css
  assets/css/minified/main.min.css
  assets/css/minified/style-flex.min.css
  assets/css/unminified/main-rtl.css
  assets/css/unminified/main.css
  assets/css/unminified/style-flex-rtl.css
  assets/css/unminified/style-flex.css
  changelog.txt
  sass/grid/_grid-flex.scss
Labels: ready to merge

#4406 AST-1919 - Table block not aligned centrally for Legacy block editor setup.
  changelog.txt
  inc/class-astra-dynamic-css.php
Labels: ready to merge

#4418 AST-1926 - Reverted default updation for single container as this managed by basic CSS
  inc/class-astra-dynamic-css.php
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  inc/core/class-astra-theme-options.php
Labels: ready to merge

#4419 AST-1926 - Build: Release PR
  README.md
  changelog.txt
  functions.php
  inc/class-astra-dynamic-css.php
  inc/compatibility/class-astra-gutenberg.php
  inc/core/class-astra-wp-editor-css.php
  inc/dynamic-css/container-layouts.php
  inc/theme-update/astra-builder-migration-updater.php
  inc/theme-update/astra-update-functions.php
  languages/astra.pot
  package.json
  readme.txt
  style.css
  tests/php/static-analysis-stubs/astra-stubs.php
Labels: Release PR checklist

#4424 AST-1931 - v3.8.4 update next-release to rc
  changelog.txt
  inc/class-astra-dynamic-css.php
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  inc/core/builder/class-astra-builder-options.php
  inc/core/class-astra-theme-options.php
  inc/core/common-functions.php
  inc/dynamic-css/block-editor-compatibility.php
  inc/dynamic-css/comments-flex.php
  inc/dynamic-css/comments.php
  inc/dynamic-css/container-layouts.php
  inc/dynamic-css/content-background.php
  inc/metabox/class-astra-meta-boxes.php
  inc/modules/related-posts/css/static-css.php
  template-parts/404/404-layout.php
  tests/php/static-analysis-stubs/astra-stubs.php
Labels: ready to merge

#4425 AST-1931 - Build: Release PR
  README.md
  functions.php
  languages/astra.pot
  package-lock.json
  package.json
  readme.txt
  style.css
Labels: ready to merge, Release PR checklist

#4426 AST-1931 - Release candidate to master release of v3.8.4
  README.md
  changelog.txt
  functions.php
  inc/class-astra-dynamic-css.php
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  inc/core/builder/class-astra-builder-options.php
  inc/core/class-astra-theme-options.php
  inc/core/common-functions.php
  inc/dynamic-css/block-editor-compatibility.php
  inc/dynamic-css/comments-flex.php
  inc/dynamic-css/comments.php
  inc/dynamic-css/container-layouts.php
  inc/dynamic-css/content-background.php
  inc/metabox/class-astra-meta-boxes.php
  inc/modules/related-posts/css/static-css.php
  languages/astra.pot
  package-lock.json
  package.json
  readme.txt
  style.css
  template-parts/404/404-layout.php
  tests/php/static-analysis-stubs/astra-stubs.php
Labels: ready to merge

#4429 Refactor : Moved updater function into new version number array
  inc/theme-update/class-astra-theme-background-updater.php
Labels: bug, needs-review

#4427 Updated select and input styling
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce.css
  sass/site/compatibility/woocommerce/woocommerce-grid.scss
  sass/site/compatibility/woocommerce/woocommerce.scss
Labels: bug, needs-review

#4428 AST-1932 - 4em margin top added after the update on post/page when full width page layout set
  changelog.txt
  inc/dynamic-css/container-layouts.php
Labels: ready to merge

#4430 Woocommerce customizer ui fixes
  inc/compatibility/edd/customizer/sections/class-astra-edd-sidebar-configs.php
  inc/compatibility/edd/customizer/sections/layout/class-astra-edd-archive-layout-configs.php
  inc/compatibility/edd/customizer/sections/layout/class-astra-edd-single-product-layout-configs.php
  inc/compatibility/woocommerce/customizer/sections/layout/class-astra-woo-shop-single-layout-configs.php
  inc/customizer/configurations/block-editor/class-astra-block-editor-configs.php
  inc/customizer/configurations/builder/base/class-astra-button-component-configs.php
  inc/customizer/configurations/builder/base/class-astra-social-icon-component-configs.php
  inc/customizer/configurations/builder/header/class-astra-customizer-edd-cart-configs.php
  inc/customizer/configurations/builder/header/class-astra-header-account-component-configs.php
  inc/customizer/configurations/builder/header/class-astra-header-menu-component-configs.php
  inc/customizer/configurations/builder/header/class-astra-header-search-component-configs.php
  inc/customizer/configurations/buttons/class-astra-customizer-button-configs.php
  inc/customizer/configurations/layout/class-astra-blog-single-layout-configs.php
  inc/customizer/configurations/layout/class-astra-site-container-layout-configs.php
  inc/customizer/configurations/performance/class-astra-performance-configs.php
  inc/customizer/configurations/typography/class-astra-archive-typo-configs.php
  inc/customizer/configurations/typography/class-astra-body-typo-configs.php
  inc/customizer/configurations/typography/class-astra-single-typo-configs.php
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/alignment-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/alignment.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/assets/css/unminified/customizer-style-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/customizer-style.css
  inc/customizer/custom-controls/assets/css/unminified/group-title-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/group-title.css
  inc/customizer/custom-controls/assets/css/unminified/radio-image-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/radio-image.css
  inc/customizer/custom-controls/assets/css/unminified/responsive-background-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/responsive-background.css
  inc/customizer/custom-controls/assets/css/unminified/responsive-spacing-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/responsive-spacing.css
  inc/customizer/custom-controls/assets/css/unminified/settings-group-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/settings-group.css
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/custom-controls/customizer-style.scss
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
  inc/customizer/extend-custom-controls/src/common/responsive-device.js
Labels: bug, needs-review

#4433 AST-1932 - Release candidate to master release v3.8.5
  README.md
  assets/fonts/google-fonts.json
  changelog.txt
  functions.php
  inc/dynamic-css/container-layouts.php
  inc/google-fonts.php
  languages/astra.pot
  package-lock.json
  package.json
  readme.txt
  style.css
Labels: ready to merge

#4434 Astra woocommerce fixes
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/alignment-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/alignment.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
Labels: bug, needs-review
