Repository brainstormforce/astra, pull requests merged in 2022-01, with the labels that each got.

#3896 QAE-262 - E2E test case for transparent header logo width
  inc/addons/transparent-header/classes/class-astra-ext-transparent-header-markup.php
  tests/e2e/e2e-plugin/rest-api/namespace.php
  tests/e2e/specs/customizer/header-builder/logo/site-logo-width.test.js
  tests/e2e/specs/customizer/header-builder/transparent-header/logo-width.test.js
  tests/e2e/utils/set-browser-viewport.js
Labels: e2e-tests

#3968 QAE-309 - E2E test case for gutenberg list block
  tests/e2e/specs/block-editor/list-block/list-block-width.test.js
Labels: e2e-tests

#3836 QAE-247 - E2E test case for page meta option disabling title on page
  tests/e2e/specs/customizer/astra-meta-settings/disable-title.test.js
Labels: e2e-tests

#3887 QAE-258 - E2E test case for disabling footer on page
  package-lock.json
  tests/e2e/specs/customizer/astra-meta-settings/disable-footer.test.js
Labels: e2e-tests

#3899 QAE-266 - Test case for performance settings in customizer
  tests/e2e/specs/customizer/performance/load-google-fonts-locally.test.js
Labels: ready to merge

#3775 AST-1400 - Toggle button design test cases for all the styles.
  tests/e2e/specs/customizer/header-builder/mobile-header/toggle-button/toggle-fill.test.js
  tests/e2e/specs/customizer/header-builder/mobile-header/toggle-button/toggle-minimal.test.js
  tests/e2e/specs/customizer/header-builder/mobile-header/toggle-button/toggle-outline.test.js
Labels: e2e-tests

#3786 QAE-105 - E2E test case for Footer Builder > HTML1 element's font-size
  tests/e2e/specs/customizer/footer-builder/html/fontsize.test.js
Labels: e2e-tests

#3949 AST-1499 - Elementor Pro Products element issue, where customizing the product column is not working with our theme
  assets/css/minified/compatibility/woocommerce/woocommerce-layout-grid.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-layout-grid.min.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-layout-grid-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-layout-grid.css
  changelog.txt
  sass/site/compatibility/woocommerce/woocommerce-layout-grid.scss
Labels: ready to merge

#3998 AST-1516 - Removing unwanted padding which causes Gutenberg blocks jerks when clicked.
  changelog.txt
  inc/assets/css/block-editor-styles-rtl.css
  inc/assets/css/block-editor-styles.css
  sass/admin/block-editor-styles.scss
Labels: ready to merge

#3981 AST-1464 - Hide cart drawer (flyout) for mobile & tablet on checkout & cart page.
  assets/js/minified/mobile-cart.min.js
  assets/js/unminified/mobile-cart.js
  changelog.txt
  inc/builder/markup/class-astra-builder-header.php
Labels: needs-review

#3815 QAE-225 - Off canvas menu e2e test cases
  .eslintrc
  tests/e2e/specs/customizer/astra-meta-settings/disable-title.test.js
  tests/e2e/specs/customizer/header-builder/below-header/margin.test.js
  tests/e2e/specs/customizer/header-builder/below-header/padding.test.js
  tests/e2e/specs/customizer/header-builder/mobile-header/off-canvas-menu/dropdown-off-canvas-menu.test.js
  tests/e2e/specs/customizer/header-builder/mobile-header/off-canvas-menu/flyout-off-canvas-menu.test.js
  tests/e2e/specs/customizer/header-builder/mobile-header/off-canvas-menu/fullscreen-off-canvas-menu.test.js
  tests/e2e/specs/customizer/header-builder/primary-header/margin.test.js
  tests/e2e/specs/customizer/header-builder/primary-header/padding.test.js
  tests/e2e/specs/customizer/header-builder/search/margin.test.js
  tests/e2e/specs/customizer/related-posts/author.name.test.js
Labels: e2e-tests

#3987 QAE-315 - E2E test case for gutenberg Columns block full and wide width
  tests/e2e/specs/block-editor/columns-block/columns-block-width.test.js
Labels: e2e-tests

#4005 QAE-318 - E2E test case for gutenberg group block default width
  tests/e2e/specs/block-editor/group-block/group-block-width.test.js
Labels: e2e-tests

#4017 improvement: Exempt all the PRs where 'e2e-tests' label is added.
  .github/pr-title-checker-config.json
  .github/workflows/stale.yml
Labels: skip-title-validation

#4013 AST-1525 - JS Error - Uncaught ReferenceError: bodyElement is not defined
  assets/js/minified/frontend.min.js
  assets/js/unminified/frontend.js
  changelog.txt
Labels: ready to merge

#4027 AST-1464 - Fixing fatal error occurred after merging - Hide cart drawer (flyout) for mobile & tablet on checkout & cart page.
  inc/builder/markup/class-astra-builder-header.php
Labels: ready to merge

#4052 AST-1528 - Block Editor Layout Issue with Astra Parent Theme Editor layout issue
  changelog.txt
  inc/core/class-gutenberg-editor-css.php
Labels: ready to merge

#3564 QAE-271 - To test Container width for Page, post & archive
  tests/e2e/specs/customizer/global/container/boxed-width.test.js
  tests/e2e/specs/customizer/global/container/contained-width.test.js
  tests/e2e/specs/customizer/global/container/content-box-width.test.js
  tests/e2e/specs/customizer/global/container/stretched-width.test.js
Labels: e2e-tests

#4070 AST-1539 - Added color picker fix for wordpress 5.9
  changelog.txt
  inc/assets/css/block-editor-styles-rtl.css
  inc/assets/css/block-editor-styles.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/color-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/color.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  sass/admin/block-editor-styles.scss
Labels: bug, needs-review

#4069 AST-1541 - Column figure blocks overlapping on one another
  changelog.txt
  inc/core/class-gutenberg-editor-css.php
Labels: needs-review

#4065 AST-1542 - There is no any gap between post edit title & first content block in block editor
  changelog.txt
  inc/core/class-gutenberg-editor-css.php
Labels: needs-review

#4078 AST-1540 - var() colors code appearing in block editor theme palette picker.
  changelog.txt
  inc/assets/js/block-editor-script.js
  inc/core/class-astra-enqueue-scripts.php
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
Labels: needs-review

#4077 AST-1544 - Fixed gradient color picker
  changelog.txt
  inc/customizer/class-astra-customizer.php
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/color-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/color.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
  inc/customizer/extend-custom-controls/src/common/astra-color-picker-control.js
Labels: bug, needs-review

#4084 AST-1540 - Fixed contrast color issue with block ast-theme color name
  assets/css/unminified/compatibility/woocommerce/woocommerce-rtl.css
  inc/assets/css/block-editor-styles-rtl.css
  inc/assets/css/block-editor-styles.css
  inc/assets/js/block-editor-script.js
  sass/admin/block-editor-styles.scss
Labels: ready to merge

#4085 AST-1523 - Build: Release PR for v3.7.7
  README.md
  assets/fonts/google-fonts.json
  changelog.txt
  functions.php
  inc/google-fonts.php
  languages/astra.pot
  package-lock.json
  package.json
  readme.txt
  style.css
Labels: ready to merge, Release PR checklist

#4086 AST-1523 - WordPress 5.9 Compatibility update
  README.md
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce.css
  assets/fonts/google-fonts.json
  changelog.txt
  functions.php
  inc/assets/css/block-editor-styles-rtl.css
  inc/assets/css/block-editor-styles.css
  inc/assets/js/block-editor-script.js
  inc/core/class-astra-enqueue-scripts.php
  inc/core/class-gutenberg-editor-css.php
  inc/customizer/class-astra-customizer.php
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/color-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/color.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
  inc/customizer/extend-custom-controls/src/common/astra-color-picker-control.js
  inc/google-fonts.php
  languages/astra.pot
  package-lock.json
  package.json
  readme.txt
  sass/admin/block-editor-styles.scss
  sass/site/compatibility/woocommerce/woocommerce-grid.scss
  sass/site/compatibility/woocommerce/woocommerce.scss
  style.css
Labels: needs-review

#4011 AST-1467 - Accessibility issue with the search Icon.
  assets/css/minified/style-flex.min.css
  assets/css/unminified/style-flex-rtl.css
  assets/css/unminified/style-flex.css
  changelog.txt
  inc/builder/type/header/search/dynamic-css/dynamic.css.php
  inc/class-astra-dynamic-css.php
  inc/markup-extras.php
  sass/style-flex.scss
  tests/e2e/specs/customizer/header-builder/elements/search/size-color-space.test.js
  tests/e2e/specs/customizer/header-builder/header-types/above-header/search-icon.test.js
Labels: ready to merge

#4031 AST-1023 - Icon size option in Cart Tray Icon.
  assets/svg/svgs.json
  changelog.txt
  inc/builder/type/header/woo-cart/assets/js/unminified/customizer-preview.js
  inc/builder/type/header/woo-cart/dynamic-css/dynamic.css.php
  inc/core/builder/class-astra-builder-options.php
  inc/core/class-astra-icons.php
  inc/customizer/configurations/builder/header/class-astra-customizer-woo-cart-configs.php
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
Labels: ready to merge
