Repository brainstormforce/astra, pull requests merged in 2022-02, with the labels that each got.

#4106 Add referral code using option
  inc/core/common-functions.php
Labels: meta

#4117 AST-1042 - Added option to add free shipping text next to woo commerce price
  changelog.txt
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  inc/compatibility/woocommerce/customizer/sections/layout/class-astra-woo-shop-single-layout-configs.php
Labels: enhancement, needs-review

#4043 AST-1531 - Some of the Astra Meta Settings does not work with Classic Editor
  changelog.txt
  inc/metabox/class-astra-meta-boxes.php
Labels: ready to merge

#4113 AST-1560 - Hierarchy missing from Product Categories in the Frontend
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid.css
  changelog.txt
  sass/frontend.scss
  sass/main.scss
  sass/site/compatibility/woocommerce/woocommerce-grid.scss
  sass/site/compatibility/woocommerce/woocommerce.scss
Labels: ready to merge

#4055 AST-172 - Breadcrumb separator with icon selector
  assets/svg/svgs.json
  changelog.txt
  functions.php
  inc/addons/breadcrumbs/assets/js/minified/customizer-preview.min.js
  inc/addons/breadcrumbs/assets/js/unminified/customizer-preview.js
  inc/addons/breadcrumbs/class-astra-breadcrumbs-loader.php
  inc/addons/breadcrumbs/customizer/class-astra-breadcrumbs-configs.php
  inc/addons/breadcrumbs/dynamic-css/dynamic.css.php
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/assets/css/unminified/radio-image-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/radio-image.css
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
  inc/customizer/extend-custom-controls/src/radio-image/radio-image-component.js
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-theme-background-updater.php
Labels: enhancement, ready to merge

#4143 AST-1562 - Added four column layout attribute for radio image controller
  inc/addons/breadcrumbs/customizer/class-astra-breadcrumbs-configs.php
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
  inc/customizer/extend-custom-controls/src/radio-image/radio-image-component.js
Labels: enhancement, needs-review

#4131 AST-1584 - Dropdown menu gets disappears when scrolled on Android mobile.
  assets/js/minified/frontend.min.js
  assets/js/unminified/frontend.js
  changelog.txt
Labels: ready to merge

#4036 AST-1496 - Hiding before & after properties which was adding unnecessary oval shape when color control option was selected/clicked
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/assets/css/unminified/customizer-style-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/customizer-style.css
  inc/customizer/custom-controls/customizer-style.scss
Labels: ready to merge

#4092 AST-1024 - Added show hide cart count option
  changelog.txt
  inc/builder/type/header/woo-cart/assets/js/unminified/customizer-preview.js
  inc/builder/type/header/woo-cart/dynamic-css/dynamic.css.php
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  inc/core/builder/class-astra-builder-options.php
  inc/customizer/configurations/builder/header/class-astra-customizer-woo-cart-configs.php
Labels: ready to merge

#4152 AST-1560 - Changelog missing for Hierarchy missing from Product Categories in the Frontend
  changelog.txt
Labels: ready to merge

#3580 AST-1031 - WooCommerce - Cart - Label - Added Dynamic Shortcodes
  changelog.txt
  inc/builder/type/header/woo-cart/assets/js/minified/customizer-preview.min.js
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  inc/core/builder/class-astra-builder-options.php
  inc/customizer/configurations/builder/header/class-astra-customizer-woo-cart-configs.php
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/assets/css/unminified/input-with-dropdowm-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/input-with-dropdowm.css
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
  inc/customizer/extend-custom-controls/package-lock.json
  inc/customizer/extend-custom-controls/package.json
  inc/customizer/extend-custom-controls/src/ast-input-with-dropdown/control.js
  inc/customizer/extend-custom-controls/src/ast-input-with-dropdown/input-with-dropdown-component.js
  inc/customizer/extend-custom-controls/src/index.js
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-theme-background-updater.php
  package-lock.json
Labels: ready to merge, Stale

#3989 QAE-313 - E2E test case for Gutenberg Shortcode block default width
  tests/e2e/specs/block-editor/shortcode-block/width.test.js
Labels: ready to merge, e2e-tests

#3971 QAE-332 - added e2e test case for above header BG-gradient
  tests/e2e/specs/customizer/header-builder/above-header/bg-gradient.test.js
Labels: e2e-tests

#3789 AST-1405 - E2E test case for footer html2 margin
  tests/e2e/specs/customizer/footer-builder/html2/html2-margin.test.js
Labels: e2e-tests

#3788 QAE-127 - E2E test case for footer html 2 font size
  tests/e2e/specs/customizer/footer-builder/html2/html2-font-size.test.js
Labels: e2e-tests
