Repository brainstormforce/astra, pull requests merged in 2023-10, with the labels that each got.

#5426 AST-3533 - Select2 control
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/assets/css/unminified/select-multi-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/select-multi.css
Labels: bug, needs-review

#5456 AST-3569 - Package testing issues for v4.4.0
  inc/core/class-astra-enqueue-scripts.php
  inc/metabox/extend-metabox/css/minified/metabox-rtl.min.css
  inc/metabox/extend-metabox/css/minified/metabox.min.css
  inc/metabox/extend-metabox/css/unminified/metabox-rtl.css
  inc/metabox/extend-metabox/css/unminified/metabox.css
  inc/theme-update/astra-update-functions.php
Labels: ready to merge

#5449 AST-3568 - Double header causing CLS issue.
  inc/class-astra-dynamic-css.php
Labels: bug

#5464 AST-3580 - Live search issues
  inc/builder/type/header/search/assets/js/minified/customizer-preview.min.js
  inc/builder/type/header/search/assets/js/unminified/customizer-preview.js
  inc/class-astra-dynamic-css.php
  inc/extras.php
Labels: bug

#5472 AST-3583 - 4.4.0 reviews on search, featured image options
  assets/css/minified/frontend.min-rtl.css
  assets/css/minified/frontend.min.css
  assets/css/minified/main.min-rtl.css
  assets/css/minified/main.min.css
  assets/css/minified/style-flex.min.css
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  assets/css/unminified/frontend-rtl.css
  assets/css/unminified/frontend.css
  assets/css/unminified/main-rtl.css
  assets/css/unminified/main.css
  assets/css/unminified/style-flex-rtl.css
  assets/css/unminified/style-flex.css
  assets/css/unminified/style-rtl.css
  assets/css/unminified/style.css
  assets/js/minified/frontend.min.js
  assets/js/unminified/frontend.js
  inc/blog/blog.php
  inc/class-astra-dynamic-css.php
  inc/core/class-astra-theme-options.php
  inc/customizer/configurations/layout/class-astra-blog-single-layout-configs.php
  inc/dynamic-css/container-layouts.php
  inc/extras.php
  inc/markup-extras.php
  inc/modules/posts-structures/customizer/class-astra-posts-single-structures-configs.php
  inc/theme-update/astra-update-functions.php
  sass/site/blog/blog-layouts/_blog-common.scss
Labels: ready to merge

#5480 AST-3592 - Release checklist PR
  README.md
  assets/fonts/google-fonts.json
  changelog.txt
  inc/addons/transparent-header/classes/dynamic-css/dynamic.css.php
  inc/blog/blog.php
  inc/builder/type/header/search/class-astra-header-search-component.php
  inc/class-astra-dynamic-css.php
  inc/class-astra-global-palette.php
  inc/compatibility/class-astra-gutenberg.php
  inc/compatibility/class-astra-surecart.php
  inc/compatibility/starter-content/astra-settings-export.json
  inc/customizer/configurations/builder/header/class-astra-header-search-component-configs.php
  inc/dynamic-css/container-layouts.php
  inc/dynamic-css/live-search.php
  inc/extras.php
  inc/google-fonts.php
  inc/markup-extras.php
  inc/metabox/class-astra-meta-boxes.php
  inc/modules/posts-structures/css/single-dynamic.css.php
  inc/modules/posts-structures/customizer/class-astra-posts-archive-structures-configs.php
  inc/modules/posts-structures/customizer/class-astra-posts-single-structures-configs.php
  inc/theme-update/astra-update-functions.php
  languages/astra.pot
  package-lock.json
  package.json
  readme.txt
  tests/php/static-analysis-stubs/astra-stubs.php
Labels: Release PR checklist

#5452 AST-3514 - Featured image hover effects
  inc/assets/js/customizer-preview.js
  inc/class-astra-dynamic-css.php
  inc/core/class-astra-theme-options.php
  inc/customizer/configurations/layout/class-astra-blog-layout-configs.php
Labels: enhancement, needs-review

#5488 AST-3579 - Post reveal effect
  inc/modules/posts-structures/customizer/class-astra-posts-archive-structures-configs.php
Labels: enhancement, needs-review

#5492 AST-3570 - Fix: Duplicate 'No Products in the Cart' Message in WooCommerce Cart Widget.
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce.css
  changelog.txt
  sass/site/compatibility/woocommerce/woocommerce-grid.scss
  sass/site/compatibility/woocommerce/woocommerce.scss
Labels: bug
