Repository brainstormforce/astra, pull requests merged in 2023-08, with the labels that each got.

#5266 AST-3284 - Update cart quantity when input value is changed
  assets/js/minified/add-to-cart-quantity-btn.min.js
  assets/js/unminified/add-to-cart-quantity-btn.js
  changelog.txt
  inc/class-astra-dynamic-css.php
Labels: enhancement, needs-review

#5257 AST-3283 - fix:Sticky add to cart scroll is not working properly for mobile & tablet.
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min.css
  assets/js/minified/sticky-add-to-cart.min.js
  assets/js/unminified/sticky-add-to-cart.js
  changelog.txt
Labels: bug

#5281 AST-3321 - In all customizer color picker options circles showing in different format & Build: Release PR (WP6.3)
  README.md
  assets/fonts/google-fonts.json
  changelog.txt
  functions.php
  inc/compatibility/starter-content/astra-settings-export.json
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/color-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/color.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
  inc/customizer/extend-custom-controls/src/common/astra-color-picker-control.js
  inc/google-fonts.php
  languages/astra.pot
  package-lock.json
  package.json
  readme.txt
  style.css
Labels: Release PR checklist

#5290 AST-3369 - For Astra theme preview page in editor button is not properly align
  changelog.txt
  inc/compatibility/starter-content/home.php
Labels: enhancement

#5286 AST-3387 - Fix: WooCommerce feature removal filter causing site crashing issue.
  changelog.txt
  inc/builder/type/header/woo-cart/dynamic-css/dynamic.css.php
  inc/core/class-astra-enqueue-scripts.php
Labels: ready to merge

#5278 AST-3370 - Beta Release Feedback Bug Fixes
  README.md
  inc/class-astra-dynamic-css.php
  inc/core/common-functions.php
  inc/customizer/class-astra-customizer.php
  inc/dynamic-css/content-background.php
  inc/extras.php
  inc/markup-extras.php
  inc/metabox/class-astra-meta-boxes.php
  inc/modules/posts-structures/customizer/class-astra-posts-archive-structures-configs.php
  inc/modules/posts-structures/customizer/class-astra-posts-single-structures-configs.php
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-theme-background-updater.php
  package-lock.json
  package.json
  tests/php/static-analysis-stubs/astra-stubs.php
Labels: Release PR checklist

#5303 AST-3401 - Block editor WordPress 6-3 compatibility fixes
  README.md
  changelog.txt
  functions.php
  inc/assets/css/block-editor-styles-rtl.css
  inc/assets/css/block-editor-styles.css
  inc/assets/css/wp-editor-styles-rtl.css
  inc/assets/css/wp-editor-styles.css
  inc/assets/js/block-editor-script.js
  inc/compatibility/starter-content/astra-settings-export.json
  inc/core/class-astra-enqueue-scripts.php
  languages/astra.pot
  package-lock.json
  package.json
  readme.txt
  sass/admin/block-editor-styles.scss
  sass/admin/wp-editor-styles.scss
  style.css
Labels: ready to merge, Release PR checklist

#5320 AST-3316 - Release checklist PR for v4.2.0
  assets/fonts/google-fonts.json
  languages/astra.pot
  package-lock.json
  package.json
Labels: Release PR checklist

#5321 AST-3316 - v4.2.0 Release
  README.md
  assets/fonts/google-fonts.json
  assets/js/minified/customizer-preview.min.js
  assets/js/unminified/customizer-preview.js
  assets/svg/svgs.json
  changelog.txt
  functions.php
  inc/assets/js/block-editor-script.js
  inc/class-astra-dynamic-css.php
  inc/compatibility/edd/class-astra-edd.php
  inc/compatibility/edd/customizer/sections/class-astra-edd-container-configs.php
  inc/compatibility/edd/customizer/sections/class-astra-edd-sidebar-configs.php
  inc/compatibility/learndash/class-astra-learndash.php
  inc/compatibility/learndash/customizer/sections/class-astra-learndash-container-configs.php
  inc/compatibility/learndash/customizer/sections/class-astra-learndash-sidebar-configs.php
  inc/compatibility/lifterlms/class-astra-lifterlms.php
  inc/compatibility/lifterlms/customizer/sections/class-astra-lifter-container-configs.php
  inc/compatibility/lifterlms/customizer/sections/class-astra-lifter-sidebar-configs.php
  inc/compatibility/starter-content/astra-settings-export.json
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  inc/compatibility/woocommerce/customizer/sections/class-astra-woo-shop-container-configs.php
  inc/compatibility/woocommerce/customizer/sections/class-astra-woo-shop-sidebar-configs.php
  inc/core/class-astra-admin-settings.php
  inc/core/class-astra-enqueue-scripts.php
  inc/core/class-astra-theme-options.php
  inc/core/common-functions.php
  inc/core/sidebar-manager.php
  inc/customizer/class-astra-customizer.php
  inc/customizer/configurations/layout/class-astra-blog-single-layout-configs.php
  inc/customizer/configurations/layout/class-astra-sidebar-layout-configs.php
  inc/customizer/configurations/layout/class-astra-site-container-layout-configs.php
  inc/customizer/configurations/layout/class-astra-site-layout-configs.php
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
  inc/customizer/extend-custom-controls/package-lock.json
  inc/customizer/extend-custom-controls/package.json
  inc/customizer/extend-custom-controls/src/description/description-component.js
  inc/dynamic-css/content-background.php
  inc/extras.php
  inc/markup-extras.php
  inc/metabox/class-astra-meta-boxes.php
  inc/metabox/extend-metabox/build/index.js
  inc/metabox/extend-metabox/css/minified/metabox-rtl.min.css
  inc/metabox/extend-metabox/css/minified/metabox.min.css
  inc/metabox/extend-metabox/css/unminified/metabox-rtl.css
  inc/metabox/extend-metabox/css/unminified/metabox.css
  inc/metabox/extend-metabox/package-lock.json
  inc/metabox/extend-metabox/src/settings.js
  inc/modules/posts-structures/customizer/class-astra-posts-archive-structures-configs.php
  inc/modules/posts-structures/customizer/class-astra-posts-single-structures-configs.php
  inc/modules/posts-structures/customizer/class-astra-posts-structures-configs.php
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-theme-background-updater.php
  languages/astra.pot
  package-lock.json
  package.json
  readme.txt
  sass/site/layout/_layout-flex.scss
  style.css
  tests/php/static-analysis-stubs/astra-stubs.php
Labels: ready to merge

#5297 AST-3382 - Spectra's TOC anchor links conflict with Smooth Scroll to ID option
  assets/js/minified/frontend.min.js
  assets/js/minified/navigation.min.js
  assets/js/minified/style.min.js
  assets/js/unminified/frontend.js
  assets/js/unminified/navigation.js
  assets/js/unminified/style.js
  changelog.txt
Labels: ready to merge

#5319 AST-3380 - Values not unlinked when different values are selected
  changelog.txt
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
  inc/customizer/extend-custom-controls/src/border/border-component.js
  inc/customizer/extend-custom-controls/src/responsive-spacing/responsive-spacing-component.js
Labels: bug, needs-review

#5302 AST-3237 - Shop Archive page Product Category Background color issue
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce.css
  changelog.txt
  sass/site/compatibility/woocommerce/woocommerce-grid.scss
  sass/site/compatibility/woocommerce/woocommerce.scss
Labels: bug

#5298 AST-3243 - Fix: Pagination jump on mobile devices issue
  changelog.txt
  inc/dynamic-css/pagination.php
Labels: bug

#5329 AST-3412 - Release 4.2.1 checklist PR
  README.md
  changelog.txt
  inc/compatibility/starter-content/astra-settings-export.json
  languages/astra.pot
  package.json
  readme.txt
  style.css
Labels: ready to merge, Release PR checklist

#5342 AST-3434 - Title visibility meta option not working in Firefox browser
  changelog.txt
  inc/assets/js/block-editor-script.js
Labels: ready to merge

#5284 AST-3367 - Issues with Header & Footer Builder
  assets/css/minified/extend-customizer.min-rtl.css
  assets/css/minified/extend-customizer.min.css
  assets/css/unminified/extend-customizer-rtl.css
  assets/css/unminified/extend-customizer.css
  changelog.txt
  inc/builder/type/base/assets/js/customizer-preview.js
  inc/builder/type/base/dynamic-css/social/class-astra-social-component-dynamic-css.php
  inc/class-astra-dynamic-css.php
  inc/core/builder/class-astra-builder-options.php
  inc/customizer/configurations/builder/base/class-astra-social-icon-component-configs.php
Labels: bug, needs-review

#5341 AST-3432 - Fix: Issue with WooCommerce Single Product Layout not applying correctly.
  changelog.txt
  inc/class-astra-dynamic-css.php
  inc/dynamic-css/comments-flex.php
  inc/extras.php
  inc/metabox/extend-metabox/build/index.js
  inc/metabox/extend-metabox/src/settings.js
  package-lock.json
  package.json
Labels: ready to merge

#5352 AST-3442 - Fix - Update default layout to Page Builder when using Elementor
  changelog.txt
  inc/compatibility/class-astra-elementor.php
Labels: ready to merge

#5347 AST-3436 - Release checklist PR
  README.md
  changelog.txt
  functions.php
  inc/builder/type/footer/primary-footer/class-astra-primary-footer-component-loader.php
  inc/builder/type/header/woo-cart/dynamic-css/dynamic.css.php
  inc/compatibility/class-astra-elementor.php
  inc/compatibility/starter-content/astra-settings-export.json
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  inc/compatibility/woocommerce/woocommerce-common-functions.php
  inc/core/class-astra-admin-settings.php
  inc/extras.php
  languages/astra.pot
  package-lock.json
  package.json
  readme.txt
  style.css
  tests/php/static-analysis-stubs/astra-stubs.php
Labels: Release PR checklist
