Repository brainstormforce/astra, pull requests merged in 2023-09, with the labels that each got.

#5370 AST-3463 - Fix: Text color not inheriting in block editor
  changelog.txt
  inc/core/class-astra-wp-editor-css.php
Labels: ready to merge

#5364 AST-3464 - Widget list-style-type creates bullets visibility issue for some widgets
  assets/css/minified/frontend.min-rtl.css
  assets/css/minified/frontend.min.css
  assets/css/minified/main.min-rtl.css
  assets/css/minified/main.min.css
  assets/css/minified/style-flex.min.css
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  assets/css/unminified/frontend-rtl.css
  assets/css/unminified/frontend.css
  assets/css/unminified/main-rtl.css
  assets/css/unminified/main.css
  assets/css/unminified/style-flex-rtl.css
  assets/css/unminified/style-flex.css
  assets/css/unminified/style-rtl.css
  assets/css/unminified/style.css
  changelog.txt
  sass/site/secondary/_widgets.scss
Labels: ready to merge

#5371 AST-3462 - Release checklist 4.3.1
  README.md
  changelog.txt
  functions.php
  inc/compatibility/starter-content/astra-settings-export.json
  languages/astra.pot
  package-lock.json
  package.json
  readme.txt
  style.css
Labels: Release PR checklist

#5289 AST-3228 - Astra Sticky Sidebar
  assets/js/minified/sticky-sidebar.min.js
  assets/js/unminified/sticky-sidebar.js
  changelog.txt
  inc/class-astra-dynamic-css.php
  inc/core/class-astra-enqueue-scripts.php
  inc/core/class-astra-theme-options.php
  inc/customizer/configurations/layout/class-astra-sidebar-layout-configs.php
  inc/markup-extras.php
  tests/php/static-analysis-stubs/astra-stubs.php
Labels: ready to merge

#5351 AST-3325 - Social Icons Background Spacing Issue in the Customizer
  changelog.txt
  inc/builder/type/base/dynamic-css/social/class-astra-social-component-dynamic-css.php
  inc/lib/astra-notices/notices.css
Labels: bug

#5361 AST-3405 - SVG Icon Jerk
  changelog.txt
  inc/assets/js/block-editor-script.js
Labels: ready to merge

#5390 AST-3427 - Issue with Astra Pro Deactivated Modules Causing Blank Design Page
  changelog.txt
  inc/customizer/configurations/typography/class-astra-archive-typo-configs.php
Labels: bug, astra-pro

#5398 AST-3493 - Admin & customizer wpastra links should wrap within astra_get_pro_url function
  admin/assets/build/dashboard-app.asset.php
  admin/assets/build/dashboard-app.js
  admin/assets/src/dashboard-app/pages/free-vs-pro/FreeVsPro.js
  admin/package-lock.json
  functions.php
Labels: ready to merge

#5401 AST-3498 - Select multi control
  inc/customizer/class-astra-customizer.php
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/assets/css/unminified/select-multi-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/select-multi.css
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
  inc/customizer/extend-custom-controls/src/ast-select-multi/ast-select-multi.js
  inc/customizer/extend-custom-controls/src/ast-select-multi/control.js
  inc/customizer/extend-custom-controls/src/index.js
Labels: enhancement, needs-review

#5350 AST-3266 - Fix: Multiple layers colours issue for submenu background.
  changelog.txt
  functions.php
  inc/addons/transparent-header/classes/dynamic-css/dynamic.css.php
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-theme-background-updater.php
Labels: ready to merge
