Repository brainstormforce/astra, pull requests merged in 2023-05, with the labels that each got.

#5126 AST-2993 - Introducing new filter astra_rank_math_theme_support to enable/disable rank-math theme support
  changelog.txt
  inc/class-astra-after-setup-theme.php
Labels: ready to merge

#5034 AST-2717 - fix: Slider Jumps and Flashes white when Closing
  changelog.txt
  inc/builder/type/header/off-canvas/dynamic-css/dynamic.css.php
Labels: bug

#5133 AST-3170 - v4.1.4 Package Reported Bug-Fixes.
  assets/css/minified/compatibility/edd.min-rtl.css
  assets/css/minified/compatibility/edd.min.css
  assets/css/minified/compatibility/lifterlms-flex.min.css
  assets/css/minified/compatibility/lifterlms.min-rtl.css
  assets/css/minified/compatibility/lifterlms.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce-layout.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-layout.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min.css
  assets/css/minified/frontend.min-rtl.css
  assets/css/minified/frontend.min.css
  assets/css/minified/main.min-rtl.css
  assets/css/minified/main.min.css
  assets/css/minified/style-flex.min.css
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  inc/assets/css/wp-editor-styles-rtl.css
  inc/assets/css/wp-editor-styles.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  sass/admin/wp-editor-styles.scss
Labels: ready to merge

#5128 AST-3170 - Release v4.1.4
  README.md
  admin/includes/class-astra-menu.php
  assets/fonts/google-fonts.json
  changelog.txt
  functions.php
  header.php
  inc/addons/breadcrumbs/dynamic-css/dynamic.css.php
  inc/compatibility/starter-content/astra-settings-export.json
  inc/core/common-functions.php
  inc/customizer/configurations/builder/footer/class-astra-customizer-above-footer-configs.php
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/google-fonts.php
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-theme-background-updater.php
  languages/astra.pot
  package-lock.json
  package.json
  readme.txt
  style.css
Labels: Release PR checklist

#5151 AST-3196 - Build: Release PR
  README.md
  changelog.txt
  functions.php
  inc/compatibility/starter-content/astra-settings-export.json
  inc/core/class-astra-wp-editor-css.php
  inc/customizer/configurations/builder/footer/class-astra-customizer-below-footer-configs.php
  inc/customizer/configurations/builder/footer/class-astra-customizer-primary-footer-configs.php
  languages/astra.pot
  package-lock.json
  package.json
  readme.txt
  style.css
Labels: Release PR checklist

#5147 AST-571 - Fixed secondary menu issue and also on RTL version
  changelog.txt
  inc/builder/type/header/menu/dynamic-css/dynamic.css.php
Labels: ready to merge
