Repository brainstormforce/astra, pull requests merged in 2023-07, with the labels that each got.

#5226 AST-3270 - Cart button color issue
  changelog.txt
  inc/builder/type/header/woo-cart/dynamic-css/dynamic.css.php
Labels: ready to merge

#5190 AST-3280 - Fix:WC Endpoint page title not changing as per endpoint change.
  changelog.txt
  inc/compatibility/woocommerce/woocommerce-common-functions.php
Labels: ready to merge

#5238 AST-3308 - Release PR Checklist
  README.md
  assets/fonts/google-fonts.json
  changelog.txt
  inc/class-astra-dynamic-css.php
  inc/compatibility/edd/class-astra-edd.php
  inc/compatibility/edd/customizer/sections/class-astra-edd-container-configs.php
  inc/compatibility/edd/customizer/sections/class-astra-edd-sidebar-configs.php
  inc/compatibility/learndash/class-astra-learndash.php
  inc/compatibility/learndash/customizer/sections/class-astra-learndash-container-configs.php
  inc/compatibility/learndash/customizer/sections/class-astra-learndash-sidebar-configs.php
  inc/compatibility/lifterlms/class-astra-lifterlms.php
  inc/compatibility/lifterlms/customizer/sections/class-astra-lifter-container-configs.php
  inc/compatibility/lifterlms/customizer/sections/class-astra-lifter-sidebar-configs.php
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  inc/compatibility/woocommerce/customizer/sections/class-astra-woo-shop-container-configs.php
  inc/compatibility/woocommerce/customizer/sections/class-astra-woo-shop-sidebar-configs.php
  inc/core/class-astra-enqueue-scripts.php
  inc/core/class-astra-theme-options.php
  inc/customizer/configurations/layout/class-astra-sidebar-layout-configs.php
  inc/customizer/configurations/layout/class-astra-site-container-layout-configs.php
  inc/customizer/configurations/layout/class-astra-site-layout-configs.php
  inc/dynamic-css/content-background.php
  inc/extras.php
  inc/google-fonts.php
  inc/markup-extras.php
  inc/metabox/class-astra-meta-boxes.php
  inc/modules/posts-structures/customizer/class-astra-posts-archive-structures-configs.php
  inc/modules/posts-structures/customizer/class-astra-posts-single-structures-configs.php
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-theme-background-updater.php
  languages/astra.pot
  package-lock.json
  readme.txt
Labels: Release PR checklist

#5245 AST-3238 - BBPress widget loading issue
  changelog.txt
  inc/markup-extras.php
Labels: ready to merge

#5244 AST-3160 - Elementor Mini Cart Widget Conflict With Astra
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce.css
  changelog.txt
  inc/class-astra-dynamic-css.php
  inc/compatibility/class-astra-elementor.php
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  sass/site/compatibility/woocommerce/woocommerce-grid.scss
  sass/site/compatibility/woocommerce/woocommerce.scss
  tests/php/static-analysis-stubs/astra-stubs.php
Labels: ready to merge

#5254 AST-2889 - Duplicate id error for primary-site-navigation & ast-hf-menu
  changelog.txt
  inc/builder/type/header/menu/class-astra-header-menu-component.php
Labels: ready to merge

#5211 AST-3018 - Accessibility Improvements for Woocommerce
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min.css
  changelog.txt
  inc/class-astra-dynamic-css.php
  inc/compatibility/woocommerce/class-astra-woocommerce.php
Labels: ready to merge

#5263 AST-3298 - Swap Images feature shows uncropped image
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce.css
  changelog.txt
  sass/site/compatibility/woocommerce/woocommerce-grid.scss
  sass/site/compatibility/woocommerce/woocommerce.scss
Labels: bug, needs-review

#5268 AST-3355 - Font Weight Variation Dropdown Gets Trimmed
  changelog.txt
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/assets/css/unminified/font-varient-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/font-varient.css
Labels: ready to merge

#5255 AST-3307 - Slide in Cart not working
  assets/js/minified/shop-add-to-cart.min.js
  assets/js/unminified/shop-add-to-cart.js
  changelog.txt
Labels: bug

#5262 AST-3300 - Fix: WooCommerce: left margin from the "Add to cart" button when Sold Individually option is selected.
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce.css
  changelog.txt
  sass/site/compatibility/woocommerce/woocommerce-grid.scss
  sass/site/compatibility/woocommerce/woocommerce.scss
Labels: bug

#5265 AST-3260 - Issue with the logo height on both the normal header and transparent header
  changelog.txt
  inc/class-astra-dynamic-css.php
  inc/theme-update/astra-update-functions.php
Labels: bug, needs-review
