Repository brainstormforce/astra, pull requests merged in 2023-06, with the labels that each got.

#5162 AST-674 - fix identical code issue navigation js
  assets/js/minified/navigation.min.js
  assets/js/minified/style.min.js
  assets/js/unminified/frontend.js
  assets/js/unminified/navigation.js
  assets/js/unminified/style.js
  changelog.txt
Labels: ready to merge

#5179 AST-2914 - Fix:Incompatibility with PHP 8.1 errors.
  changelog.txt
  inc/core/builder/class-astra-builder-helper.php
  inc/core/class-astra-icons.php
  inc/core/common-functions.php
  inc/extras.php
Labels: bug, ready to merge

#5178 AST-2895 - Fix: Slide In cart triggers automatically while saving changes in elementor editor.
  assets/js/minified/shop-add-to-cart.min.js
  assets/js/unminified/shop-add-to-cart.js
  changelog.txt
  inc/compatibility/class-astra-elementor-pro.php
Labels: bug

#5155 AST-3199 - Fix: Post title & Featured image is not visible while editing in elementor with banner layout 2.
  changelog.txt
  inc/compatibility/class-astra-elementor.php
Labels: bug

#5180 AST-3218 - Fix:PHP 8.2 Compatibility Issues.
  changelog.txt
Labels: ready to merge

#5183 AST-3253 - Unnecessary http suffix for target attribute in read more button
  changelog.txt
  inc/modules/related-posts/class-astra-related-posts-markup.php
Labels: ready to merge

#5177 AST-3208 - Added SureCart product dynamic CPT sections on top level in the customizer
  changelog.txt
  inc/modules/posts-structures/customizer/class-astra-posts-archive-structures-configs.php
  inc/modules/posts-structures/customizer/class-astra-posts-structures-configs.php
Labels: ready to merge

#5185 AST-3227 - Lists vertical spacing issue.
  changelog.txt
  functions.php
  inc/class-astra-dynamic-css.php
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-theme-background-updater.php
  tests/php/static-analysis-stubs/astra-stubs.php
Labels: ready to merge

#5163 AST-3203 - Fix: Sticky Header feature is overwritten by the Checkout dropdown fields
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce.css
  changelog.txt
  sass/site/compatibility/woocommerce/woocommerce-grid.scss
  sass/site/compatibility/woocommerce/woocommerce.scss
Labels: bug, ready to merge
