Repository brainstormforce/astra, pull requests merged in 2023-03, with the labels that each got.

#5038 AST-2720 - Introduced new filter to remove gmpg link from link profile
  changelog.txt
  header.php
Labels: ready to merge

#5051 AST-2944 - fix: BBPress Compatibility with Astra Theme
  changelog.txt
  inc/markup-extras.php
Labels: bug

#5061 AST-3086 - Cart buttons preview not working in customizer
  Gruntfile.js
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce-layout-grid.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-layout-grid.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce-layout.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-layout.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-layout-grid-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-layout-grid.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-layout-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-layout.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce.css
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  sass/site/compatibility/woocommerce/woocommerce-grid.scss
  sass/site/compatibility/woocommerce/woocommerce-layout-grid.scss
  sass/site/compatibility/woocommerce/woocommerce-layout.scss
  sass/site/compatibility/woocommerce/woocommerce.scss
Labels: ready to merge

#4987 AST-3003 - Build: Release PR
  .github/workflows/code-analysis.yml
  .github/workflows/release-pr-template.yml
  README.md
  admin/assets/build/dashboard-app.asset.php
  admin/assets/build/dashboard-app.js
  admin/assets/src/dashboard-app/DocsPopup.js
  admin/assets/src/dashboard-app/pages/welcome/VideoPopup.js
  admin/assets/src/dashboard-app/pages/welcome/Welcome.js
  admin/includes/class-astra-api-init.php
  admin/includes/class-astra-menu.php
  assets/fonts/google-fonts.json
  changelog.txt
  composer.lock
  inc/assets/css/wp-editor-styles-rtl.css
  inc/assets/css/wp-editor-styles.css
  inc/blog/blog-config.php
  inc/compatibility/class-astra-elementor.php
  inc/compatibility/edd/class-astra-edd.php
  inc/compatibility/learndash/class-astra-learndash.php
  inc/compatibility/lifterlms/class-astra-lifterlms.php
  inc/compatibility/starter-content/astra-settings-export.json
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  inc/core/class-astra-wp-editor-css.php
  inc/core/class-gutenberg-editor-css.php
  inc/core/deprecated/deprecated-filters.php
  inc/customizer/class-astra-customizer-register-sections-panels.php
  inc/customizer/class-astra-customizer.php
  inc/customizer/configurations/accessibility/class-astra-accessibility-configs.php
  inc/google-fonts.php
  inc/markup-extras.php
  inc/theme-update/astra-update-functions.php
  languages/astra.pot
  package.json
  readme.txt
  sass/admin/wp-editor-styles.scss
  style.css
  tests/php/static-analysis-stubs/astra-stubs.php
Labels: ready to merge, Release PR checklist

#5072 AST-3107 - Array to string conversion PHP notice due to button responsive parsing CSS
  changelog.txt
  inc/class-astra-dynamic-css.php
Labels: ready to merge

#5074 AST-3107 - Version 4.1.1 release into master
  README.md
  admin/includes/class-astra-menu.php
  changelog.txt
  functions.php
  inc/class-astra-dynamic-css.php
  inc/compatibility/starter-content/astra-settings-export.json
  inc/modules/related-posts/css/dynamic-css.php
  languages/astra.pot
  package.json
  readme.txt
  style.css
  tests/php/static-analysis-stubs/astra-stubs.php
Labels: ready to merge

#5075 AST-3109 - Hotfixes for 4.1.1
  assets/css/minified/frontend.min-rtl.css
  assets/css/minified/frontend.min.css
  assets/css/minified/main.min-rtl.css
  assets/css/minified/main.min.css
  assets/css/minified/style-flex.min.css
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  assets/css/unminified/frontend-rtl.css
  assets/css/unminified/frontend.css
  assets/css/unminified/main-rtl.css
  assets/css/unminified/main.css
  assets/css/unminified/style-flex-rtl.css
  assets/css/unminified/style-flex.css
  assets/css/unminified/style-rtl.css
  assets/css/unminified/style.css
  changelog.txt
  sass/site/blog/blog-layouts/_blog-common.scss
Labels: ready to merge

#5077 AST-3109 - Build: Release PR 4.1.2
  README.md
  assets/css/minified/frontend.min-rtl.css
  assets/css/minified/frontend.min.css
  assets/css/minified/main.min-rtl.css
  assets/css/minified/main.min.css
  assets/css/minified/style-flex.min.css
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  assets/css/unminified/frontend-rtl.css
  assets/css/unminified/frontend.css
  assets/css/unminified/main-rtl.css
  assets/css/unminified/main.css
  assets/css/unminified/style-flex-rtl.css
  assets/css/unminified/style-flex.css
  assets/css/unminified/style-rtl.css
  assets/css/unminified/style.css
  changelog.txt
  functions.php
  inc/compatibility/starter-content/astra-settings-export.json
  inc/extras.php
  languages/astra.pot
  package-lock.json
  package.json
  readme.txt
  sass/site/blog/blog-layouts/_blog-common.scss
  style.css
Labels: ready to merge, Release PR checklist
