Repository brainstormforce/astra, pull requests merged in 2023-04, with the labels that each got.

#5065 AST-3081 - fix: Astra content box mode removes Spectra column or container left padding.
  changelog.txt
  inc/dynamic-css/block-editor-compatibility.php
Labels: bug, ready to merge

#5068 AST-3096 - Flyout menu issue with RTL version
  changelog.txt
  inc/builder/type/header/off-canvas/dynamic-css/dynamic.css.php
Labels: bug

#5087 AST-3131 - Fix: Widget's dropdown arrow is moving to top corner.
  changelog.txt
  inc/compatibility/woocommerce/class-astra-woocommerce.php
Labels: ready to merge

#5082 AST-3122 - Fix: Slide Cart Goes Blank when Elementor Pro is enabled.
  changelog.txt
  inc/compatibility/woocommerce/class-astra-woocommerce.php
Labels: bug

#5089 AST-3134 - Merging next-release to release-candidate for v4.1.3
  assets/js/minified/add-to-cart-quantity-btn.min.js
  assets/js/unminified/add-to-cart-quantity-btn.js
  changelog.txt
  inc/builder/type/header/off-canvas/dynamic-css/dynamic.css.php
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  inc/customizer/class-astra-builder-customizer.php
  inc/dynamic-css/block-editor-compatibility.php
  inc/markup-extras.php
Labels: ready to merge

#5090 AST-3134 - Release checklist PR for v4.1.3
  README.md
  changelog.txt
  functions.php
  inc/compatibility/starter-content/astra-settings-export.json
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  languages/astra.pot
  package-lock.json
  package.json
  readme.txt
  style.css
Labels: ready to merge, Release PR checklist

#5091 AST-3134 - Release PR v4.1.3
  README.md
  assets/js/minified/add-to-cart-quantity-btn.min.js
  assets/js/unminified/add-to-cart-quantity-btn.js
  changelog.txt
  functions.php
  inc/builder/type/header/off-canvas/dynamic-css/dynamic.css.php
  inc/compatibility/starter-content/astra-settings-export.json
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  inc/customizer/class-astra-builder-customizer.php
  inc/dynamic-css/block-editor-compatibility.php
  inc/markup-extras.php
  languages/astra.pot
  package-lock.json
  package.json
  readme.txt
  style.css
Labels: ready to merge

#5110 AST-3161 - UTM links updated as per the details provided
  admin/assets/build/dashboard-app.asset.php
  admin/assets/build/dashboard-app.js
  admin/assets/src/dashboard-app/pages/docs/Docs.js
  admin/assets/src/dashboard-app/pages/docs/SearchResults.js
  admin/assets/src/dashboard-app/pages/docs/SubSection.js
  admin/assets/src/dashboard-app/pages/free-vs-pro/FreeVsPro.js
  admin/assets/src/dashboard-app/pages/starter-templates/StarterTemplates.js
  admin/assets/src/dashboard-app/pages/welcome/Welcome.js
  admin/includes/class-astra-menu.php
  admin/package-lock.json
  functions.php
  inc/compatibility/edd/customizer/sections/layout/class-astra-edd-archive-layout-configs.php
  inc/compatibility/lifterlms/customizer/sections/layout/class-astra-lifter-general-configs.php
  inc/core/class-astra-admin-settings.php
  inc/customizer/astra-pro/class-astra-pro-upgrade-link-configs.php
  inc/customizer/class-astra-customizer.php
  inc/customizer/configurations/builder/header/class-astra-customizer-woo-cart-configs.php
  inc/customizer/configurations/layout/class-astra-footer-layout-configs.php
  inc/customizer/configurations/layout/class-astra-header-layout-configs.php
  inc/customizer/configurations/typography/class-astra-content-typo-configs.php
  inc/metabox/class-astra-meta-boxes.php
  languages/astra.pot
  tests/php/static-analysis-stubs/astra-stubs.php
  tests/php/static-analysis-stubs/constants.php
Labels: ready to merge

#5106 AST-3155 - Fix: Trigger to change event on the input.
  assets/js/minified/add-to-cart-quantity-btn.min.js
  assets/js/unminified/add-to-cart-quantity-btn.js
  changelog.txt
Labels: ready to merge
