Repository brainstormforce/astra, pull requests merged in 2023-02, with the labels that each got.

#4971 AST-2853 - fix: Footer Menu Alignment issue for responsive devices.
  changelog.txt
  inc/builder/type/footer/menu/assets/js/minified/customizer-preview.min.js
  inc/builder/type/footer/menu/assets/js/unminified/customizer-preview.js
  inc/builder/type/footer/menu/dynamic-css/dynamic.css.php
Labels: bug, ready to merge

#4864 AST-2287 - fix: Disable the title from elementor setting is not working as expected
  changelog.txt
  inc/compatibility/class-astra-elementor.php
Labels: bug

#4958 AST-2532 - fix: Spectra container spacing options not working
  changelog.txt
  inc/dynamic-css/block-editor-compatibility.php
Labels: ready to merge

#4637 AST-2096 - Changed Border radius control from slider to inputs values
  assets/js/minified/customizer-preview.min.js
  assets/js/unminified/customizer-preview.js
  inc/addons/scroll-to-top/assets/js/minified/customizer-preview.min.js
  inc/addons/scroll-to-top/assets/js/unminified/customizer-preview.js
  inc/addons/scroll-to-top/classes/class-astra-scroll-to-top-loader.php
  inc/addons/scroll-to-top/classes/customizer/class-astra-scroll-to-top-configs.php
  inc/addons/scroll-to-top/css/dynamic-css.php
  inc/builder/type/base/assets/js/customizer-preview.js
  inc/builder/type/base/dynamic-css/button/class-astra-button-component-dynamic-css.php
  inc/builder/type/base/dynamic-css/social/class-astra-social-component-dynamic-css.php
  inc/builder/type/header/menu/assets/js/minified/customizer-preview.min.js
  inc/builder/type/header/menu/assets/js/unminified/customizer-preview.js
  inc/builder/type/header/menu/dynamic-css/dynamic.css.php
  inc/builder/type/header/mobile-trigger/assets/js/minified/customizer-preview.min.js
  inc/builder/type/header/mobile-trigger/assets/js/unminified/customizer-preview.js
  inc/builder/type/header/mobile-trigger/dynamic-css/dynamic.css.php
  inc/builder/type/header/woo-cart/assets/js/minified/customizer-preview.min.js
  inc/builder/type/header/woo-cart/assets/js/unminified/customizer-preview.js
  inc/builder/type/header/woo-cart/dynamic-css/dynamic.css.php
  inc/class-astra-dynamic-css.php
  inc/core/builder/class-astra-builder-options.php
  inc/core/class-astra-theme-options.php
  inc/customizer/configurations/builder/base/class-astra-button-component-configs.php
  inc/customizer/configurations/builder/base/class-astra-social-icon-component-configs.php
  inc/customizer/configurations/builder/header/class-astra-customizer-mobile-trigger-configs.php
  inc/customizer/configurations/builder/header/class-astra-customizer-woo-cart-configs.php
  inc/customizer/configurations/builder/header/class-astra-header-menu-component-configs.php
  inc/customizer/configurations/buttons/class-astra-customizer-button-configs.php
  tests/e2e/specs/customizer/footer-builder/elements/social-icon/icon-radius.test.js
  tests/e2e/specs/customizer/global/scroll-to-top/border-radius.test.js
  tests/e2e/specs/customizer/header-builder/elements/social-icon/background-color.test.js
  tests/e2e/specs/customizer/header-builder/elements/social-icon/background-spacing.test.js
  tests/e2e/specs/customizer/header-builder/elements/social-icon/color.test.js
  tests/e2e/specs/customizer/header-builder/elements/social-icon/label-color.test.js
  tests/e2e/specs/customizer/header-builder/elements/social-icon/label-font-size.test.js
  tests/e2e/specs/customizer/header-builder/elements/social-icon/margin.test.js
  tests/e2e/specs/customizer/header-builder/elements/social-icon/radius.test.js
  tests/e2e/specs/customizer/header-builder/elements/social-icon/size.test.js
  tests/e2e/specs/customizer/header-builder/elements/social-icon/spacing.test.js
  tests/e2e/specs/customizer/header-builder/elements/social-icons/social-icon-hide-on-tablet-mobile.test.js
  tests/e2e/specs/customizer/header-builder/elements/social-icons/social-icon-radius.test.js
Labels: ready to merge

#4936 AST-2474 - Inside container spacing for single posts affecting the related posts section
  assets/css/minified/compatibility/edd.min-rtl.css
  assets/css/minified/compatibility/edd.min.css
  assets/css/minified/compatibility/lifterlms-flex.min.css
  assets/css/minified/compatibility/lifterlms.min-rtl.css
  assets/css/minified/compatibility/lifterlms.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce-layout.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-layout.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min.css
  assets/css/minified/frontend.min-rtl.css
  assets/css/minified/frontend.min.css
  assets/css/minified/main.min-rtl.css
  assets/css/minified/main.min.css
  assets/css/minified/style-flex.min.css
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  assets/js/minified/customizer-preview.min.js
  assets/js/unminified/customizer-preview.js
  changelog.txt
  inc/addons/scroll-to-top/assets/js/minified/customizer-preview.min.js
  inc/blog/single-blog.php
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
Labels: bug

#4863 AST-2081 - Transparent header new UI option can embed in Astra
  .github/workflows/tests.yml
  assets/css/minified/compatibility/edd.min-rtl.css
  assets/css/minified/compatibility/edd.min.css
  assets/css/minified/compatibility/lifterlms-flex.min.css
  assets/css/minified/compatibility/lifterlms.min-rtl.css
  assets/css/minified/compatibility/lifterlms.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce-layout.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-layout.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min.css
  assets/css/minified/frontend.min-rtl.css
  assets/css/minified/frontend.min.css
  assets/css/minified/main.min-rtl.css
  assets/css/minified/main.min.css
  assets/css/minified/style-flex.min.css
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/color-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/color.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/assets/css/unminified/customizer-style-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/customizer-style.css
  inc/customizer/custom-controls/customizer-style.scss
Labels: bug, needs-review

#4860 AST-2275 - Featured product when cart is empty
  assets/js/minified/mobile-cart.min.js
  assets/js/unminified/mobile-cart.js
  changelog.txt
  inc/builder/controllers/class-astra-builder-ui-controller.php
  inc/builder/type/header/woo-cart/assets/js/minified/customizer-preview.min.js
  inc/builder/type/header/woo-cart/assets/js/unminified/customizer-preview.js
  inc/builder/type/header/woo-cart/dynamic-css/dynamic.css.php
  inc/class-astra-dynamic-css.php
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  inc/customizer/configurations/builder/header/class-astra-customizer-woo-cart-configs.php
Labels: enhancement, ready to merge

#4862 AST-2007 - Add to cart actions for shop page
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce.css
  assets/js/minified/shop-add-to-cart.min.js
  assets/js/unminified/shop-add-to-cart.js
  assets/svg/svgs.json
  changelog.txt
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  inc/compatibility/woocommerce/customizer/sections/layout/class-astra-woo-shop-layout-configs.php
  inc/core/class-astra-enqueue-scripts.php
  sass/site/compatibility/woocommerce/woocommerce-grid.scss
  sass/site/compatibility/woocommerce/woocommerce.scss
Labels: enhancement, needs-review

#4806 AST-2319 - Site navigation accessibility
  assets/css/minified/frontend.min-rtl.css
  assets/css/minified/frontend.min.css
  assets/css/minified/main.min-rtl.css
  assets/css/minified/main.min.css
  assets/css/minified/style-flex.min.css
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  assets/css/unminified/frontend-rtl.css
  assets/css/unminified/frontend.css
  assets/css/unminified/main-rtl.css
  assets/css/unminified/main.css
  assets/css/unminified/style-flex-rtl.css
  assets/css/unminified/style-flex.css
  assets/css/unminified/style-rtl.css
  assets/css/unminified/style.css
  assets/js/minified/frontend.min.js
  assets/js/unminified/frontend.js
  changelog.txt
  inc/builder/type/header/off-canvas/dynamic-css/dynamic.css.php
  inc/class-astra-dynamic-css.php
  inc/core/builder/class-astra-builder-helper.php
  inc/core/class-astra-enqueue-scripts.php
  inc/extras.php
  sass/navigation/_links.scss
  sass/site/builder/_header.scss
  sass/site/forms/_common.scss
  sass/site/navigation/_primary-menu.scss
Labels: enhancement, ready to merge

#4753 AST-2270 - Accessibility option
  changelog.txt
  inc/class-astra-dynamic-css.php
  inc/core/class-astra-theme-options.php
  inc/customizer/class-astra-customizer-register-sections-panels.php
  inc/customizer/class-astra-customizer.php
  inc/customizer/configurations/accessibility/class-astra-accessibility-configs.php
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/assets/css/unminified/radio-icon-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/radio-icon.css
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
  inc/customizer/extend-custom-controls/src/ast-radio-icon/ast-radio-icon-component.js
  inc/customizer/extend-custom-controls/src/ast-radio-icon/control.js
  inc/customizer/extend-custom-controls/src/index.js
Labels: enhancement, ready to merge

#4985 AST-2959 - Single post title transformed to capitalize after 4.0 update.
  changelog.txt
  inc/blog/single-blog.php
  inc/builder/type/footer/menu/dynamic-css/dynamic.css.php
  inc/builder/type/footer/widget/dynamic-css/dynamic.css.php
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  inc/core/class-astra-wp-editor-css.php
  inc/dynamic-css/block-editor-compatibility.php
  inc/theme-update/astra-update-functions.php
Labels: ready to merge

#4991 AST-2963 - Removed extra spacing in date format in customizer
  assets/css/minified/compatibility/edd.min-rtl.css
  assets/css/minified/compatibility/edd.min.css
  assets/css/minified/compatibility/lifterlms-flex.min.css
  assets/css/minified/compatibility/lifterlms.min-rtl.css
  assets/css/minified/compatibility/lifterlms.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce-layout.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-layout.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min.css
  assets/css/minified/frontend.min-rtl.css
  assets/css/minified/frontend.min.css
  assets/css/minified/main.min-rtl.css
  assets/css/minified/main.min.css
  assets/css/minified/style-flex.min.css
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/assets/css/unminified/sortable-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/sortable.css
Labels: ready to merge

#4847 AST-2278 - Social sharing icon/options for single posts
  assets/css/minified/compatibility/edd.min-rtl.css
  assets/css/minified/compatibility/edd.min.css
  assets/css/minified/compatibility/lifterlms-flex.min.css
  assets/css/minified/compatibility/lifterlms.min-rtl.css
  assets/css/minified/compatibility/lifterlms.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce-layout.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-layout.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min.css
  assets/css/minified/frontend.min-rtl.css
  assets/css/minified/frontend.min.css
  assets/css/minified/main.min-rtl.css
  assets/css/minified/main.min.css
  assets/css/minified/style-flex.min.css
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  assets/svg/svgs.json
  inc/assets/css/ast-builder-customizer-rtl.css
  inc/assets/css/ast-builder-customizer.css
  inc/blog/blog.php
  inc/customizer/configurations/typography/class-astra-single-typo-configs.php
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/assets/css/unminified/tooltip-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/tooltip.css
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
  inc/customizer/extend-custom-controls/src/social-icons/item-component.js
  inc/customizer/extend-custom-controls/src/social-icons/social-component.js
Labels: enhancement, ready to merge

#4993 AST-2958 - fix: The Dev tool (console) is throwing an event listener error when a product has only 1 item in stock.
  assets/css/minified/compatibility/edd.min-rtl.css
  assets/css/minified/compatibility/edd.min.css
  assets/css/minified/compatibility/lifterlms-flex.min.css
  assets/css/minified/compatibility/lifterlms.min-rtl.css
  assets/css/minified/compatibility/lifterlms.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce-layout.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-layout.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min.css
  assets/css/minified/frontend.min-rtl.css
  assets/css/minified/frontend.min.css
  assets/css/minified/main.min-rtl.css
  assets/css/minified/main.min.css
  assets/css/minified/style-flex.min.css
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  assets/js/minified/add-to-cart-quantity-btn.min.js
  assets/js/unminified/add-to-cart-quantity-btn.js
  changelog.txt
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  tests/e2e/specs/customizer/footer-builder/footer-types/above-footer/inner-column-spacing.test.js
  tests/e2e/specs/customizer/footer-builder/footer-types/above-footer/vertical-alignment.test.js
Labels: bug

#5005 AST-2974 - Fixed single product add to cart button width issue
  assets/js/minified/customizer-preview.min.js
  assets/js/unminified/customizer-preview.js
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  inc/customizer/configurations/layout/class-astra-blog-layout-configs.php
  inc/modules/posts-structures/customizer/class-astra-posts-single-structures-configs.php
Labels: ready to merge

#4973 AST-2909 - Vipwpcs issues resolved
  admin/class-astra-admin-loader.php
  admin/includes/class-astra-api-init.php
  admin/includes/class-astra-menu.php
  admin/views/admin-base.php
  composer.json
  composer.lock
  header.php
  inc/addons/scroll-to-top/class-astra-scroll-to-top.php
  inc/addons/scroll-to-top/classes/class-astra-scroll-to-top-loader.php
  inc/blog/blog-config.php
  inc/blog/blog.php
  inc/compatibility/class-astra-yoast-seo.php
  inc/compatibility/edd/class-astra-edd.php
  inc/compatibility/edd/edd-common-functions.php
  inc/compatibility/lifterlms/class-astra-lifterlms.php
  inc/compatibility/starter-content/home.php
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  inc/core/class-astra-admin-settings.php
  inc/core/common-functions.php
  inc/core/deprecated/deprecated-filters.php
  inc/customizer/custom-controls/typography/class-astra-control-typography.php
  inc/extras.php
  inc/markup-extras.php
  inc/metabox/class-astra-meta-boxes.php
  inc/modules/posts-structures/class-astra-posts-structure-markup.php
  inc/modules/related-posts/class-astra-related-posts-markup.php
  inc/theme-update/astra-update-functions.php
  phpcs.xml.dist
  searchform.php
  template-parts/archive-banner.php
  template-parts/single-banner.php
  tests/php/static-analysis-stubs/astra-stubs.php
Labels: ready to merge

#4980 AST-2909 - Vipwpcs issues resolved
  inc/addons/transparent-header/classes/class-astra-ext-transparent-header-markup.php
  inc/metabox/class-astra-meta-boxes.php
Labels: enhancement, ready to merge

#5014 AST-2961 - fix : focus issue which effected select tags
  assets/css/minified/frontend.min-rtl.css
  assets/css/minified/frontend.min.css
  assets/css/minified/main.min-rtl.css
  assets/css/minified/main.min.css
  assets/css/minified/style-flex.min.css
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  assets/css/unminified/frontend-rtl.css
  assets/css/unminified/frontend.css
  assets/css/unminified/main-rtl.css
  assets/css/unminified/main.css
  assets/css/unminified/style-flex-rtl.css
  assets/css/unminified/style-flex.css
  assets/css/unminified/style-rtl.css
  assets/css/unminified/style.css
  composer.lock
  inc/class-astra-dynamic-css.php
  sass/navigation/_links.scss
Labels: bug, needs-review

#5016 AST-3004 - For toggle button accessibility global color is not working
  inc/class-astra-dynamic-css.php
Labels: bug, needs-review
