Repository brainstormforce/astra, pull requests merged in 2023-01, with the labels that each got.

#4865 AST-2796 - fix: Content bg color not working for all layouts
  assets/js/minified/customizer-preview.min.js
  assets/js/unminified/customizer-preview.js
  changelog.txt
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/assets/css/unminified/sortable-rtl.css
Labels: ready to merge

#4861 AST-2792 - fix: Support for button preset outline (buttons 4-6) styles in editor
  inc/core/class-astra-wp-editor-css.php
Labels: ready to merge

#4855 AST-2765 - Fixed site identity and header black screen on the editor
  inc/customizer/custom-controls/assets/js/minified/custom-controls.min.js
  inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
  inc/customizer/extend-custom-controls/build/index.asset.php
  inc/customizer/extend-custom-controls/build/index.js
  inc/customizer/extend-custom-controls/src/customizer.js
Labels: ready to merge

#4877 AST-2610 - fix: Real Time Quantity Updater not working when Woocommerce shortcode is added.
  assets/js/minified/add-to-cart-quantity-btn.min.js
  assets/js/unminified/add-to-cart-quantity-btn.js
  changelog.txt
Labels: bug

#4876 AST-2794 - Block editor fixes beta release
  inc/assets/css/wp-editor-styles-rtl.css
  inc/assets/css/wp-editor-styles.css
  inc/class-astra-dynamic-css.php
  inc/core/class-astra-wp-editor-css.php
  sass/admin/wp-editor-styles.scss
Labels: ready to merge

#4880 AST-2813 - fix: Content bg color not applying to posts / pages when Narrow conta…
  assets/js/minified/customizer-preview.min.js
  assets/js/unminified/customizer-preview.js
  inc/assets/js/block-editor-script.js
Labels: ready to merge

#4883 AST-2812 - Changelog update for 4.0
  changelog.txt
Labels: ready to merge

#4885 AST-2831 - Release 4.0.0 build
  README.md
  admin/class-astra-admin-loader.php
  admin/includes/class-astra-admin-ajax.php
  admin/includes/class-astra-api-init.php
  admin/includes/class-astra-menu.php
  admin/views/admin-base.php
  assets/fonts/google-fonts.json
  functions.php
  inc/addons/heading-colors/class-astra-heading-colors-loader.php
  inc/addons/scroll-to-top/class-astra-scroll-to-top.php
  inc/addons/scroll-to-top/classes/class-astra-scroll-to-top-loader.php
  inc/addons/scroll-to-top/classes/customizer/class-astra-scroll-to-top-configs.php
  inc/addons/scroll-to-top/css/static-css.php
  inc/blog/blog-config.php
  inc/blog/blog.php
  inc/class-astra-dynamic-css.php
  inc/class-astra-global-palette.php
  inc/compatibility/class-astra-amp.php
  inc/compatibility/class-astra-starter-content.php
  inc/compatibility/starter-content/home.php
  inc/core/builder/class-astra-builder-options.php
  inc/core/class-astra-theme-options.php
  inc/core/common-functions.php
  inc/core/deprecated/deprecated-hooks.php
  inc/core/theme-hooks.php
  inc/customizer/configurations/builder/class-astra-builder-base-configuration.php
  inc/customizer/configurations/global-misc/class-astra-global-misc-configs.php
  inc/extras.php
  inc/google-fonts.php
  inc/modules/posts-structures/class-astra-post-structures.php
  inc/modules/posts-structures/class-astra-posts-structure-loader.php
  inc/modules/posts-structures/class-astra-posts-structure-markup.php
  inc/modules/posts-structures/css/archive-dynamic.css.php
  inc/modules/posts-structures/css/single-dynamic.css.php
  inc/modules/posts-structures/customizer/class-astra-posts-archive-structures-configs.php
  inc/modules/posts-structures/customizer/class-astra-posts-single-structures-configs.php
  inc/modules/posts-structures/customizer/class-astra-posts-structures-configs.php
  inc/modules/related-posts/class-astra-related-posts-loader.php
  inc/template-parts.php
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-theme-background-updater.php
  languages/astra.pot
  package-lock.json
  package.json
  style.css
  template-parts/archive-banner.php
  template-parts/scroll-to-top.php
  template-parts/single-banner.php
  template-parts/single/content-header.php
  tests/php/static-analysis-stubs/astra-stubs.php
Labels: Release PR checklist

#4891 AST-2835 - Post title also effecting related post title
  inc/modules/posts-structures/assets/js/minified/customizer-preview.min.js
  inc/modules/posts-structures/assets/js/unminified/customizer-preview.js
  inc/modules/posts-structures/class-astra-posts-structure-loader.php
  inc/modules/posts-structures/css/single-dynamic.css.php
  inc/modules/related-posts/class-astra-related-posts-markup.php
Labels: bug, ready to merge

#4892 AST-2840 - Checkmark icon is not center align in color palette
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/color-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/color.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
Labels: bug, ready to merge

#4895 AST-2841 - In custom post type edit pencil icon is breaking
  inc/modules/posts-structures/css/archive-dynamic.css.php
  inc/modules/posts-structures/css/single-dynamic.css.php
Labels: bug, needs-review

#4894 AST-2837 - Fixed dynamic title font sizes and weight
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/modules/posts-structures/assets/js/minified/customizer-preview.min.js
  inc/modules/posts-structures/assets/js/unminified/customizer-preview.js
Labels: ready to merge

#4903 AST-2831 - Updated admin dashboard video & input-pre BG color default updated
  admin/assets/build/dashboard-app.asset.php
  admin/assets/build/dashboard-app.js
  admin/assets/src/dashboard-app/MainNav.js
  admin/assets/src/dashboard-app/pages/welcome/VideoPopup.js
  admin/assets/src/dashboard-app/pages/welcome/Welcome.js
  assets/css/minified/editor-style.min-rtl.css
  assets/css/minified/editor-style.min.css
  assets/css/minified/frontend.min-rtl.css
  assets/css/minified/frontend.min.css
  assets/css/minified/main.min-rtl.css
  assets/css/minified/main.min.css
  assets/css/minified/style-flex.min.css
  assets/css/minified/style.min-rtl.css
  assets/css/minified/style.min.css
  assets/css/unminified/editor-style-rtl.css
  assets/css/unminified/editor-style.css
  assets/css/unminified/frontend-rtl.css
  assets/css/unminified/frontend.css
  assets/css/unminified/main-rtl.css
  assets/css/unminified/main.css
  assets/css/unminified/style-flex-rtl.css
  assets/css/unminified/style-flex.css
  assets/css/unminified/style-rtl.css
  assets/css/unminified/style.css
  changelog.txt
  inc/assets/css/wp-editor-styles-rtl.css
  inc/assets/css/wp-editor-styles.css
  inc/class-astra-dynamic-css.php
  inc/core/class-astra-wp-editor-css.php
  inc/modules/posts-structures/css/archive-dynamic.css.php
  sass/admin/wp-editor-styles.scss
  sass/elements/_elements.scss
  sass/site/forms/_common.scss
Labels: ready to merge

#4905 AST-2849 - 4.0 Release Build
  assets/fonts/google-fonts.json
  inc/google-fonts.php
  languages/astra.pot
  package-lock.json
Labels: ready to merge, Release PR checklist

#4914 AST-2857 - scroll id issue
  assets/js/minified/frontend.min.js
  assets/js/minified/navigation.min.js
  assets/js/minified/style.min.js
  assets/js/unminified/frontend.js
  assets/js/unminified/navigation.js
  assets/js/unminified/style.js
  changelog.txt
Labels: bug, needs-review

#4911 AST-2854 - Visibility controls missing from header builder section & their dynamic CSS has display issue
  changelog.txt
  inc/assets/css/ast-builder-customizer-rtl.css
  inc/assets/css/ast-builder-customizer.css
  inc/builder/type/class-astra-builder-base-dynamic-css.php
  inc/customizer/configurations/builder/class-astra-builder-base-configuration.php
  inc/customizer/configurations/builder/header/class-astra-customizer-primary-header-configs.php
  inc/customizer/configurations/builder/header/class-astra-header-account-component-configs.php
  inc/modules/posts-structures/class-astra-posts-structure-loader.php
Labels: ready to merge

#4917 AST-2854 - Release checklist PR
  README.md
  admin/includes/class-astra-menu.php
  changelog.txt
  functions.php
  languages/astra.pot
  package.json
  readme.txt
  style.css
Labels: ready to merge, Release PR checklist

#4918 AST-2854 - Release PR of v4.0.1
  README.md
  admin/includes/class-astra-menu.php
  assets/js/minified/frontend.min.js
  assets/js/minified/navigation.min.js
  assets/js/minified/style.min.js
  assets/js/unminified/frontend.js
  assets/js/unminified/navigation.js
  assets/js/unminified/style.js
  changelog.txt
  functions.php
  inc/assets/css/ast-builder-customizer-rtl.css
  inc/assets/css/ast-builder-customizer.css
  inc/builder/type/class-astra-builder-base-dynamic-css.php
  inc/core/common-functions.php
  inc/customizer/configurations/builder/class-astra-builder-base-configuration.php
  inc/customizer/configurations/builder/header/class-astra-customizer-primary-header-configs.php
  inc/customizer/configurations/builder/header/class-astra-header-account-component-configs.php
  inc/modules/posts-structures/class-astra-posts-structure-loader.php
  languages/astra.pot
  package.json
  readme.txt
  style.css
Labels: ready to merge

#4937 AST-2875 - Starter content changing site title
  changelog.txt
  inc/compatibility/class-astra-starter-content.php
Labels: bug, ready to merge

#4935 AST-2862 - Theme preview not displaying properly on wordpress.org preview
  changelog.txt
  inc/compatibility/class-astra-starter-content.php
Labels: bug, needs-review

#4934 AST-2873 - Fixed UI glitch for firefox browser for typography control
  changelog.txt
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/border-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/border.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/assets/css/unminified/font-presets-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/font-presets.css
  inc/customizer/custom-controls/assets/css/unminified/responsive-spacing-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/responsive-spacing.css
Labels: ready to merge

#4947 AST-2884 - fix: Customizer preview reflections do not work wherever transport set to refresh.
  inc/core/class-astra-theme-options.php
  inc/customizer/configurations/builder/class-astra-builder-base-configuration.php
Labels: ready to merge

#4950 AST-2859 - Build: Release PR
  .github/workflows/release-pr-template.yml
  README.md
  assets/fonts/google-fonts.json
  changelog.txt
  inc/class-astra-dynamic-css.php
  inc/compatibility/class-astra-starter-content.php
  inc/compatibility/starter-content/astra-settings-export.json
  inc/core/class-astra-theme-options.php
  inc/core/deprecated/deprecated-filters.php
  inc/google-fonts.php
  inc/modules/posts-structures/class-astra-posts-structure-loader.php
  inc/modules/posts-structures/customizer/class-astra-posts-single-structures-configs.php
  inc/modules/posts-structures/customizer/class-astra-posts-structures-configs.php
  inc/theme-update/astra-update-functions.php
  languages/astra.pot
  package-lock.json
  package.json
  readme.txt
  style.css
  tests/php/static-analysis-stubs/astra-stubs.php
Labels: ready to merge, Release PR checklist

#4809 AST-1914 - fix: The off-canvas dropdown menu arrow is misplaced
  changelog.txt
  inc/builder/type/header/off-canvas/dynamic-css/dynamic.css.php
Labels: bug, ready to merge

#4881 feat : filter to add custom attributes to custom logo
  changelog.txt
  inc/markup-extras.php
Labels: enhancement, ready to merge

#4959 AST-1916 - fix: Content background color does not apply to Author Box in customizer preview.
  assets/js/minified/customizer-preview.min.js
  assets/js/unminified/customizer-preview.js
  changelog.txt
Labels: bug, ready to merge

#4900 AST-2542 - bugfix - Footer Widgets Dynamic CSS gets duplicated
  changelog.txt
  inc/builder/type/footer/widget/dynamic-css/dynamic.css.php
Labels: ready to merge

#4951 AST-2660 - Wordpress overriding outline button global styling
  assets/js/minified/customizer-preview.min.js
  assets/js/unminified/customizer-preview.js
  changelog.txt
  inc/class-astra-dynamic-css.php
Labels: bug, needs-review

#4902 AST-2829 - fix: Global buttons text and background hover color is not working in customizer preview
  assets/js/minified/customizer-preview.min.js
  assets/js/unminified/customizer-preview.js
  changelog.txt
Labels: ready to merge

#4946 AST-2810 - Woocommerce h2 not taking value from global fonts
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce-grid.min.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min-rtl.css
  assets/css/minified/compatibility/woocommerce/woocommerce.min.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-grid.css
  assets/css/unminified/compatibility/woocommerce/woocommerce-rtl.css
  assets/css/unminified/compatibility/woocommerce/woocommerce.css
  changelog.txt
  functions.php
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-theme-background-updater.php
  sass/site/compatibility/woocommerce/woocommerce-grid.scss
  sass/site/compatibility/woocommerce/woocommerce.scss
Labels: bug, ready to merge

#4969 AST-2601 - compatibility with cost calculator range slider
  changelog.txt
  inc/class-astra-dynamic-css.php
Labels: bug, needs-review

#4970 AST-835 - Removed extra divider from Site Title & Logo section.
  inc/customizer/configurations/layout/class-astra-site-identity-configs.php
Labels: bug, ready to merge

#4961 AST-1920 - Fix Woocommerce
  changelog.txt
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  inc/core/class-astra-wp-editor-css.php
Labels: bug, needs-review
