Repository brainstormforce/astra, pull requests merged in 2024-01, with the labels that each got.

#5653 AST-3773 - Fix: Design tweaks for cart & checkout Woo blocks
  changelog.txt
  inc/assets/js/column-block-compatibility.js
  inc/class-astra-dynamic-css.php
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  inc/core/class-astra-wp-editor-css.php
Labels: ready to merge

#5656 AST-3776 - Fix: secondary button background color style not working
  assets/js/minified/customizer-preview.min.js
  assets/js/unminified/customizer-preview.js
  changelog.txt
  inc/class-astra-dynamic-css.php
Labels: ready to merge

#5664 AST-3769 - Build: Release PR
  README.md
  assets/fonts/google-fonts.json
  changelog.txt
  inc/blog/blog-config.php
  inc/blog/blog.php
  inc/blog/single-blog.php
  inc/class-astra-dynamic-css.php
  inc/compatibility/woocommerce/class-astra-woocommerce.php
  inc/customizer/configurations/builder/class-astra-builder-base-configuration.php
  inc/customizer/configurations/comments/class-astra-comments-configs.php
  inc/dynamic-css/navigation.php
  inc/dynamic-css/single-post.php
  inc/extras.php
  inc/google-fonts.php
  inc/lib/docs/class-astra-docs-loader.php
  inc/lib/webfont/class-astra-webfont-loader.php
  inc/metabox/class-astra-meta-boxes.php
  inc/modules/posts-structures/class-astra-posts-structure-loader.php
  inc/modules/posts-structures/css/single-dynamic.css.php
  inc/modules/posts-structures/css/special-dynamic.css.php
  inc/modules/posts-structures/customizer/class-astra-posts-single-structures-configs.php
  inc/modules/posts-structures/customizer/class-astra-posts-special-archive-structures-configs.php
  inc/modules/related-posts/class-astra-related-posts-markup.php
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-theme-background-updater.php
  languages/astra.pot
  package-lock.json
  package.json
  readme.txt
  template-parts/blog/blog-layout-4.php
  template-parts/blog/blog-layout-6.php
  tests/php/static-analysis-stubs/astra-stubs.php
Labels: Release PR checklist

#5665 AST-3787 - PHP fatal error with "Uncaught Error: Class 'Astra_Builder_Base_Dynamic_CSS' not found" when old header-footer is active.
  README.md
  changelog.txt
  functions.php
  inc/class-astra-dynamic-css.php
  inc/compatibility/starter-content/astra-settings-export.json
  inc/customizer/configurations/builder/header/configs/search.php
  inc/customizer/configurations/comments/class-astra-comments-configs.php
  inc/extras.php
  inc/modules/posts-structures/customizer/class-astra-posts-single-structures-configs.php
  inc/modules/related-posts/css/dynamic-css.php
  inc/modules/related-posts/customizer/class-astra-related-posts-configs.php
  languages/astra.pot
  package.json
  readme.txt
  style.css
Labels: ready to merge, Release PR checklist

#5669 AST-3788 - Hot-fix update v4.6.2
  changelog.txt
  functions.php
  inc/blog/blog.php
  inc/class-astra-dynamic-css.php
  inc/compatibility/starter-content/astra-settings-export.json
  inc/markup-extras.php
  inc/theme-update/astra-update-functions.php
  inc/theme-update/class-astra-theme-background-updater.php
  languages/astra.pot
  package-lock.json
  package.json
  style.css
Labels: ready to merge, Release PR checklist

#5673 AST-3792 - Primary menu last item padding is missing in latest update.
  changelog.txt
  inc/class-astra-dynamic-css.php
Labels: ready to merge

#5679 AST-3796 - Single post and page horizontal alignment is not working for banner layout 2
  changelog.txt
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/assets/css/unminified/number-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/number.css
  inc/modules/posts-structures/assets/js/minified/customizer-preview.min.js
  inc/modules/posts-structures/assets/js/unminified/customizer-preview.js
  inc/modules/posts-structures/css/single-dynamic.css.php
Labels: ready to merge

#5682 AST-3800 - Release v4.6.3
  README.md
  changelog.txt
  functions.php
  inc/blog/blog.php
  inc/class-astra-dynamic-css.php
  inc/compatibility/starter-content/astra-settings-export.json
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/modules/posts-structures/css/single-dynamic.css.php
  languages/astra.pot
  package-lock.json
  package.json
  readme.txt
  style.css
Labels: Release PR checklist

#5683 AST-3800 - Astra v4.6.3 Release
  README.md
  changelog.txt
  functions.php
  inc/blog/blog.php
  inc/class-astra-dynamic-css.php
  inc/compatibility/starter-content/astra-settings-export.json
  inc/core/markup/class-astra-markup.php
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min-rtl.css
  inc/customizer/custom-controls/assets/css/minified/custom-controls.min.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
  inc/customizer/custom-controls/assets/css/unminified/number-rtl.css
  inc/customizer/custom-controls/assets/css/unminified/number.css
  inc/markup-extras.php
  inc/modules/posts-structures/assets/js/minified/customizer-preview.min.js
  inc/modules/posts-structures/assets/js/unminified/customizer-preview.js
  inc/modules/posts-structures/css/single-dynamic.css.php
  languages/astra.pot
  package-lock.json
  package.json
  readme.txt
  style.css
Labels: ready to merge
